force-app/main/default/objects/ConstructionMeasureSets__x/ConstructionMeasureSets__x.object-meta.xml
<CustomObject>
    <description>ConstructionMeasureSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>ConstructionMeasureSets</externalName>
    <label>ConstructionMeasureSets</label>
    <pluralLabel>ConstructionMeasureSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/Cmnum__c.field-meta.xml
<CustomField>
    <fullName>Cmnum__c</fullName>
    <description>Cmnum</description>
    <externalDeveloperName>Cmnum</externalDeveloperName>
    <label>Cmnum</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/Cmtxt__c.field-meta.xml
<CustomField>
    <fullName>Cmtxt__c</fullName>
    <description>Cmtxt</description>
    <externalDeveloperName>Cmtxt</externalDeveloperName>
    <label>Cmtxt</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzAccc__c.field-meta.xml
<CustomField>
    <fullName>ZzAccc__c</fullName>
    <description>ZzAccc</description>
    <externalDeveloperName>ZzAccc</externalDeveloperName>
    <label>ZzAccc</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzContestability__c.field-meta.xml
<CustomField>
    <fullName>ZzContestability__c</fullName>
    <description>ZzContestability</description>
    <externalDeveloperName>ZzContestability</externalDeveloperName>
    <label>ZzContestability</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzCrab__c.field-meta.xml
<CustomField>
    <fullName>ZzCrab__c</fullName>
    <description>ZzCrab</description>
    <externalDeveloperName>ZzCrab</externalDeveloperName>
    <label>ZzCrab</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzLodgeSpear__c.field-meta.xml
<CustomField>
    <fullName>ZzLodgeSpear__c</fullName>
    <description>ZzLodgeSpear</description>
    <externalDeveloperName>ZzLodgeSpear</externalDeveloperName>
    <label>ZzLodgeSpear</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzPrjOfficer__c.field-meta.xml
<CustomField>
    <fullName>ZzPrjOfficer__c</fullName>
    <description>ZzPrjOfficer</description>
    <externalDeveloperName>ZzPrjOfficer</externalDeveloperName>
    <label>ZzPrjOfficer</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzSubDivi__c.field-meta.xml
<CustomField>
    <fullName>ZzSubDivi__c</fullName>
    <description>ZzSubDivi</description>
    <externalDeveloperName>ZzSubDivi</externalDeveloperName>
    <label>ZzSubDivi</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzSubdivision__c.field-meta.xml
<CustomField>
    <fullName>ZzSubdivision__c</fullName>
    <description>ZzSubdivision</description>
    <externalDeveloperName>ZzSubdivision</externalDeveloperName>
    <label>ZzSubdivision</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzTownPermit__c.field-meta.xml
<CustomField>
    <fullName>ZzTownPermit__c</fullName>
    <description>ZzTownPermit</description>
    <externalDeveloperName>ZzTownPermit</externalDeveloperName>
    <label>ZzTownPermit</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Progress__c/Progress__c.object-meta.xml
<CustomObject>
    <label>Progress</label>
    <nameField>
        <label>Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress__c/fields/CMUserStatus__c.field-meta.xml
<CustomField>
    <fullName>CMUserStatus__c</fullName>
    <label>CM User Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Progresses</relationshipLabel>
    <relationshipName>Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Progress__c/fields/ProjectAssignee__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssignee__c</fullName>
    <label>ProjectAssignee</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress__c/fields/SAPContestability__c.field-meta.xml
<CustomField>
    <fullName>SAPContestability__c</fullName>
    <label>SAPContestability</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress__c/fields/SAPStatus__c.field-meta.xml
<CustomField>
    <fullName>SAPStatus__c</fullName>
    <label>SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CMStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress__c/fields/SAPStatusFlag__c.field-meta.xml
<CustomField>
    <fullName>SAPStatusFlag__c</fullName>
    <label>Status Flag</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>SAP Start Date of the CM status</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ACCC_Form__c.field-meta.xml
<CustomField>
    <fullName>ACCC_Form__c</fullName>
    <label>ACCC Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ContestabilityType__c.field-meta.xml
<CustomField>
    <fullName>ContestabilityType__c</fullName>
    <label>Contestability Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDIC</fullName>
            </value>
            <value>
                <fullName>EDEC</fullName>
            </value>
            <value>
                <fullName>IDEC</fullName>
            </value>
            <value>
                <fullName>IDEC-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/CRAB_Form__c.field-meta.xml
<CustomField>
    <fullName>CRAB_Form__c</fullName>
    <label>CRAB Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/PlaningPermitNumber__c.field-meta.xml
<CustomField>
    <fullName>PlaningPermitNumber__c</fullName>
    <label>Planing Permit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectAssignee__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Assignee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Project Assignee must have &quot;DER TVE-11 Unified User&quot; or &quot;TVE-11 AST Standard User&quot; profile</errorMessage>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>DER TVE-11 Unified User, TVE-11 AST Standard User, DSP User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsAssigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <description>Project name</description>
    <label>Project Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatus__c.field-meta.xml
<CustomField>
    <fullName>SAPStatus__c</fullName>
    <defaultValue>&quot;REGI&quot;</defaultValue>
    <description>Display of where the project is up to</description>
    <label>SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CMStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatusFlag__c.field-meta.xml
<CustomField>
    <fullName>SAPStatusFlag__c</fullName>
    <label>Status Flag</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SpearReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SpearReferenceNumber__c</fullName>
    <label>Spear Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subdivision__c.field-meta.xml
<CustomField>
    <fullName>Subdivision__c</fullName>
    <label>Subdivision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SubdivisionPlanNumber__c.field-meta.xml
<CustomField>
    <fullName>SubdivisionPlanNumber__c</fullName>
    <label>Subdivision Plan Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Updated_By_Integration__c.field-meta.xml
<CustomField>
    <fullName>Updated_By_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated By Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_GetCMToSAP.cls
/*
  @author  : harshad.kumbhar@ausnetservices.com.au
  @created : 03 Mar 2020
  @Description : Class for Get CM to SAP system
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/
public without sharing class TVE_SAPInteg_GetCMToSAP implements Queueable{
    
    @TestVisible private static List<ConstructionMeasureSets__x> mockedExtCM = new List<ConstructionMeasureSets__x>();    
    
    private static final String CREATECUST_CALLOUT = 'GetCM';
    public static Map<String,Id> mapAccUniqueIdProjId = new Map<String,Id>();
    
    public void execute(QueueableContext qc)
    {        
        List<Integration_Task__c> lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Get','Project__c','GetCM','In Progress');
		System.debug('Integration Task : ' + lstIntgTask);
      
        Boolean queryException = false;
        List<Project__c> ProjToUpdate = new List<Project__c>();
        List<Progress__c> ProgToUpdate = new List<Progress__c>();

        Map<Id, Id> parentToTask = new Map<Id, Id>();
        Map<String,Project__c> oldmapProj = new Map<String,Project__c>();
        Map<String,Project__c> newmapProj = new Map<String,Project__c>();

        Map<String,Progress__c> oldmapProg = new Map<String,Progress__c>();
        Map<Id,Progress__c> newmapProg = new Map<Id,Progress__c>();

        Map<Id,String> successMap = new Map<Id,String>();
        Map<Id,String> failureMap = new Map<Id,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMapFail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();

        for(Integration_Task__c item: lstIntgTask)
        {
            Boolean checkId = (item.ParentId__c InstanceOf Id);
            if(checkId)
            {
                parentToTask.put(item.ParentId__c, item.Id);
            }
            else {
                failureMap.put(item.Id, 'Error: invalid ParentId on Integration Task');
            }
        }

        try {
            List<Project__c> lstProj = [SELECT Id,CMNumber__c,ProjectName__c,ContestabilityType__c,PlaningPermitNumber__c,SpearReferenceNumber__c,
                                        SubdivisionPlanNumber__c,Subdivision__c,ACCC_Form__c,CRAB_Form__c,SAPStatus__c,SAPStatusFlag__c
                                        FROM Project__c WHERE Id in: parentToTask.keySet() AND CmNumber__c != null];
            for(Project__c proj : lstProj) {
                oldmapProj.put(proj.CMNumber__c,proj);
            }
            
            wrapProjNProg wrapClass = getCMMapping(oldmapProj);

            newmapProj = wrapClass.project;           
            newmapProg = wrapClass.progress;


        } catch (Exception e) {
            queryException = true;
            //Fail all Integration_Task__c
            for(Integration_Task__c task : lstIntgTask) {
                failureMap.put(task.Id, e.getMessage() + '\r\n' + e.getStackTraceString());                
            }

        }

        if(!queryException) {
            for(String extId : oldmapProj.keySet()) {
                System.debug('External Id : '+ extId);
                System.debug('newMapProj :' + newmapProj);
                if(newmapProj.containsKey(extId)) {
                    //Compare newmapWorkOrder with oldmapWorkOrder
                    Project__c newProj = newmapProj.get(extId);
                    Project__c oldProj = oldmapProj.get(extId);
                
                    if(newProj.ProjectName__c == oldProj.ProjectName__c 
                    && newProj.PlaningPermitNumber__c == oldProj.PlaningPermitNumber__c 
                    && newProj.SpearReferenceNumber__c == oldProj.SpearReferenceNumber__c
                    && newProj.SubdivisionPlanNumber__c == oldProj.SubdivisionPlanNumber__c
                    && newProj.Subdivision__c == oldProj.Subdivision__c
                    && newProj.ContestabilityType__c == oldProj.ContestabilityType__c
                    && newProj.ACCC_Form__c == oldProj.ACCC_Form__c
                    && newProj.CRAB_Form__c == oldProj.CRAB_Form__c
                    && newProj.SAPStatus__c == oldProj.SAPStatus__c
                    && newProj.SAPStatusFlag__c == oldProj.SAPStatusFlag__c
                    ) {
                        //If no changes are required, set Integration_Task__c successful
                        successMap.put(parentToTask.get(newProj.Id), newProj.Id);
                    } else {
                        //To update
                        ProjToUpdate.add(newProj);
                    }
                } else {
                    //OrderNumber not found in SAP
                    failureMap.put(parentToTask.get(oldmapProj.get(extId).Id), 'Project related fields are not found in SAP');
                }
            }

            if(!ProjToUpdate.isEmpty()) {
                List<Database.SaveResult> lstSR = Database.update(ProjToUpdate, false);
                System.debug('lstSR Project:' + lstSR);
                List<Progress__c> lstProgInsert = new List<Progress__c>();
                for(Database.SaveResult res : lstSR) {
                    if (res.isSuccess()) {
                        System.debug('Project getId :' +parentToTask.get(res.getId()));
                        successMap.put(parentToTask.get(res.getId()), res.getId());
                        if(!newmapProg.isEmpty() && newmapProg.containsKey(res.getId()))
                        {
                            lstProgInsert.add(newmapProg.get(res.getId()));
                        }
                    } else {
                        List<String> errorMsg = new List<String>();
                        for(Database.Error err : res.getErrors()) {
                            errorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
                        }
                        for (Project__c proj : ProjToUpdate) {                            
                            failureMap.put(parentToTask.get(proj.Id), String.join(errorMsg, '\r\n'));                        
                        }                        
                        
                    }                    
                }
                if(!lstProgInsert.isEmpty())
                {
                    insert lstProgInsert;
                }
            }          
        }        
        for (Integration_Task__c task : lstIntgTask) {
            if(!successMap.containsKey(task.Id) && !failureMap.containsKey(task.Id)) {
                failureMap.put(task.Id,'Error: Integration Task could not proceed');
            }
        }
        if(!successMap.isEmpty()) {
            updateIntTaskMap.put('Status__c','Successful');
            createIntglogmapS.put('Status__c','Successful');
            System.System.debug('GetCMToSAP SuccessMap :' + successMap);    
            TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
            TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
        }
        if(!failureMap.isEmpty()) {
            updateIntTaskMapFail.put('Status__c','Failed');
            createIntglogmapF.put('Status__c','Failed');
                
            TVE_IntegUtility.UpdateInteTask(failureMap,updateIntTaskMapFail);
            TVE_IntegUtility.createIntegLog(failureMap,createIntglogmapF);
        }

        lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Get','Project__c','GetCM','In Progress');
        if(!lstIntgTask.isEmpty()){
            TVE_SAPInteg_GetCMToSAP getCM = new TVE_SAPInteg_GetCMToSAP();
                        ID jobID = System.enqueueJob(getCM);  
        }

    }
    public class wrapProjNProg {
        public Map<String,Project__c> project {get; set;}
        public Map<Id,Progress__c> progress {get; set;} 
    }


   public static String getSplitStatus(String UserStatus)
   {
      String splitedstatus;
        if(String.isNotEmpty(UserStatus))
        {
            Integer lenOfStatus = UserStatus.length();
            if(lenOfStatus <= 4)
            {
                splitedstatus = UserStatus.substring(0, 4);                
            }
            if (lenOfStatus > 4){
                splitedstatus = UserStatus.left(4);                
            }
        }
        return splitedstatus;
   }
   public static String getSplitStatusLast(String UserStatus)
   {
      String splitedstatus;
        if(String.isNotEmpty(UserStatus))
        {
            Integer lenOfStatus = UserStatus.length();
            
            if (lenOfStatus > 4){
                splitedstatus = UserStatus.right(4);                
            }
        }
        return splitedstatus;
   }
    public static wrapProjNProg getCMMapping(Map<String,Project__c> mapProject)
    {
        
       List<ConstructionMeasureSets__x> lstCMs = new List<ConstructionMeasureSets__x>();
       Map<String, Project__c> newmapProj = new Map<String, Project__c>();
       Map<Id, Progress__c> newmapProg = new Map<Id, Progress__c>();
       
       List<String> CMNumbers = new List<String>();
        for (String Id : mapProject.keySet()) {
            CMNumbers.add(Id);
        }
        if(Test.isRunningTest())
        {
            lstCMs = (mockedExtCM.size() > 0) ? mockedExtCM : lstCMs; 
        }
        else {
            lstCMs = TVE_IntegUtility.GetCMs(CMNumbers);
        }
       
        List<Progress__c> lstProgress = new List<Progress__c>();
        wrapProjNProg wrapClass = new wrapProjNProg();
        wrapClass.progress = new Map<Id,Progress__c>();
        wrapClass.project = new Map<String,Project__c>();
        for (ConstructionMeasureSets__x cm : lstCMs) {
            if(mapProject.containsKey(cm.Cmnum__c))
            {
                System.debug('CMnumber :' + cm.Cmnum__c);
                Project__c newItem = new Project__c(
                    Id = mapProject.get(cm.Cmnum__c).Id
                );

                if(String.isNotBlank(cm.Cmnum__c))
                {
                    newItem.CMNumber__c = cm.Cmnum__c;    
                }
                
                if(String.isNotBlank(cm.Cmtxt__c))
                {
                    newItem.ProjectName__c = cm.Cmtxt__c;    
                }
                if(String.isNotBlank(cm.ZzTownPermit__c))
                {
                    newItem.PlaningPermitNumber__c = cm.ZzTownPermit__c;
                }
                if(String.isNotBlank(cm.ZzContestability__c))
                {
                    newItem.ContestabilityType__c = TVE_IntegUtility.getContesabilityInbound(cm.ZzContestability__c);
                }
                if(String.isNotBlank(cm.ZzLodgeSpear__c))
                {
                    newItem.SpearReferenceNumber__c = cm.ZzLodgeSpear__c;
                }
                if(String.isNotBlank(cm.ZzSubdivision__c))
                {
                    newItem.SubdivisionPlanNumber__c = cm.ZzSubdivision__c;
                }
                if(String.isNotBlank(cm.ZzSubDivi__c))
                {
                    newItem.Subdivision__c = cm.ZzSubDivi__c == 'Y' ? 'Yes' : 'No';
                }
                if(String.isNotBlank(cm.ZzAccc__c))
                {
                    newItem.ACCC_Form__c = cm.ZzAccc__c == 'Y' ? 'Yes' : 'No';
                }                        
                if(String.isNotBlank(cm.ZzCrab__c))
                {
                    newItem.CRAB_Form__c = cm.ZzCrab__c == 'Y' ? 'Yes' : 'No';
                } 
                if(String.isNotBlank(cm.UserStatus__c))
                {
                    //Updated by JTan on 20/04/2020 for TV-2883
                    newItem.SAPStatusFlag__c = (cm.UserStatus__c.length() > 4) ? getSplitStatusLast(cm.UserStatus__c) : '';

                    String newSAPStatus = (cm.UserStatus__c.length() >= 4) ? getSplitStatus(cm.UserStatus__c) : '';
                    String oldSAPStatus = mapProject.get(cm.Cmnum__c).SAPStatus__c;
                    Set<String> statusToPause = new Set<String>{'PREQ', 'DSNG', 'COMT'};
                    if(oldSAPStatus == 'REGI' && statusToPause.contains(newSAPStatus) && newItem.SAPStatusFlag__c != 'PREC') {
                        //Do Nothing
                    } else {
                        newItem.SAPStatus__c = newSAPStatus;
                    }
                }

                newItem.Updated_By_Integration__c = true;
                            
                Progress__c progress = new Progress__c();
                if(String.isNotBlank(cm.UserStatus__c))
                {
                    progress.SAPStatus__c = (cm.UserStatus__c.length() >= 4) ? getSplitStatus(cm.UserStatus__c) : '';               
                    progress.SAPStatusFlag__c = (cm.UserStatus__c.length() > 4) ? getSplitStatusLast(cm.UserStatus__c) : ''; 
                    progress.CMUserStatus__c = cm.UserStatus__c; 
                } 
                
                
                progress.StartDate__c =  Date.today();
                progress.Project__c = mapProject.get(cm.Cmnum__c).Id;
                if(String.isNotBlank(cm.ZzPrjOfficer__c))
                {
                    progress.ProjectAssignee__c = cm.ZzPrjOfficer__c;
                }
                if(String.isNotBlank(cm.ZzContestability__c))
                {
                    progress.SAPContestability__c = TVE_IntegUtility.getContesabilityInbound(cm.ZzContestability__c);
                }
                //lstProgress.add(progress);

                System.debug('GetCMToSAP Error Project:'+ newItem);
                System.debug('GetCMToSAP Error Progress:'+ progress);
                
                wrapClass.progress.put(progress.Project__c,progress); 
                
                wrapClass.project.put(newItem.CMNumber__c,newItem);              
                System.debug('GetCMToSAP CMNumber:'+ newItem.CMNumber__c);
                System.debug('GetCMToSAP Error wrap Progress:'+ wrapClass.project.size());
            }

            
        }
        System.debug('GetCMToSAP Wrap Project:'+ wrapClass.project);
        System.debug('GetCMToSAP Wrap Progress:'+ wrapClass.progress);
        return wrapClass;
    }
}