force-app/main/default/objects/ConstructionMeasureSets__x/ConstructionMeasureSets__x.object-meta.xml
<CustomObject>
    <description>ConstructionMeasureSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>ConstructionMeasureSets</externalName>
    <label>ConstructionMeasureSets</label>
    <pluralLabel>ConstructionMeasureSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/Cmnum__c.field-meta.xml
<CustomField>
    <fullName>Cmnum__c</fullName>
    <description>Cmnum</description>
    <externalDeveloperName>Cmnum</externalDeveloperName>
    <label>Cmnum</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/Cmtxt__c.field-meta.xml
<CustomField>
    <fullName>Cmtxt__c</fullName>
    <description>Cmtxt</description>
    <externalDeveloperName>Cmtxt</externalDeveloperName>
    <label>Cmtxt</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzAccc__c.field-meta.xml
<CustomField>
    <fullName>ZzAccc__c</fullName>
    <description>ZzAccc</description>
    <externalDeveloperName>ZzAccc</externalDeveloperName>
    <label>ZzAccc</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzContestability__c.field-meta.xml
<CustomField>
    <fullName>ZzContestability__c</fullName>
    <description>ZzContestability</description>
    <externalDeveloperName>ZzContestability</externalDeveloperName>
    <label>ZzContestability</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzCrab__c.field-meta.xml
<CustomField>
    <fullName>ZzCrab__c</fullName>
    <description>ZzCrab</description>
    <externalDeveloperName>ZzCrab</externalDeveloperName>
    <label>ZzCrab</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzLodgeSpear__c.field-meta.xml
<CustomField>
    <fullName>ZzLodgeSpear__c</fullName>
    <description>ZzLodgeSpear</description>
    <externalDeveloperName>ZzLodgeSpear</externalDeveloperName>
    <label>ZzLodgeSpear</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzPrjOfficer__c.field-meta.xml
<CustomField>
    <fullName>ZzPrjOfficer__c</fullName>
    <description>ZzPrjOfficer</description>
    <externalDeveloperName>ZzPrjOfficer</externalDeveloperName>
    <label>ZzPrjOfficer</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzSubDivi__c.field-meta.xml
<CustomField>
    <fullName>ZzSubDivi__c</fullName>
    <description>ZzSubDivi</description>
    <externalDeveloperName>ZzSubDivi</externalDeveloperName>
    <label>ZzSubDivi</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzSubdivision__c.field-meta.xml
<CustomField>
    <fullName>ZzSubdivision__c</fullName>
    <description>ZzSubdivision</description>
    <externalDeveloperName>ZzSubdivision</externalDeveloperName>
    <label>ZzSubdivision</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/fields/ZzTownPermit__c.field-meta.xml
<CustomField>
    <fullName>ZzTownPermit__c</fullName>
    <description>ZzTownPermit</description>
    <externalDeveloperName>ZzTownPermit</externalDeveloperName>
    <label>ZzTownPermit</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ACCC_Form__c.field-meta.xml
<CustomField>
    <fullName>ACCC_Form__c</fullName>
    <label>ACCC Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ContestabilityType__c.field-meta.xml
<CustomField>
    <fullName>ContestabilityType__c</fullName>
    <label>Contestability Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDIC</fullName>
            </value>
            <value>
                <fullName>EDEC</fullName>
            </value>
            <value>
                <fullName>IDEC</fullName>
            </value>
            <value>
                <fullName>IDEC-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/CRAB_Form__c.field-meta.xml
<CustomField>
    <fullName>CRAB_Form__c</fullName>
    <label>CRAB Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/PlaningPermitNumber__c.field-meta.xml
<CustomField>
    <fullName>PlaningPermitNumber__c</fullName>
    <label>Planing Permit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <description>Project name</description>
    <label>Project Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatus__c.field-meta.xml
<CustomField>
    <fullName>SAPStatus__c</fullName>
    <defaultValue>&quot;REGI&quot;</defaultValue>
    <description>Display of where the project is up to</description>
    <label>SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CMStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatusFlag__c.field-meta.xml
<CustomField>
    <fullName>SAPStatusFlag__c</fullName>
    <label>Status Flag</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SpearReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>SpearReferenceNumber__c</fullName>
    <label>Spear Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subdivision__c.field-meta.xml
<CustomField>
    <fullName>Subdivision__c</fullName>
    <label>Subdivision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SubdivisionPlanNumber__c.field-meta.xml
<CustomField>
    <fullName>SubdivisionPlanNumber__c</fullName>
    <label>Subdivision Plan Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_GetCMToSAPTest.cls
/*
  @author  : harshad.kumbhar@ausnetservices.com.au
  @created : 04 Mar 2020
  @Description : Test Class for Get CM to SAP system
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/

@isTest
private class TVE_SAPInteg_GetCMToSAPTest{

	public static final string testUserEmail = 'testuser@TVECustomerDetailsSAP.com';
    public static final string CON_TYPE = 'IDIC';
	public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
	public  static String CM_RT   = 'Project';
    private static Id  CM_RTId = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByDeveloperName().get(CM_RT).getRecordTypeId();
  
	@testSetup static void setup(){

		//Create User
		User testUser = TVE_TestUtility.createTestUser(testUserEmail);
		insert testUser;

		Account testAccount = TVE_TestUtility.createPersonAccount('acctName', testUserEmail);
		insert testAccount;
		
		eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
		eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
		insert eSignObj;
			
		List<Project__c> lstProj = new List<Project__c>();
		lstProj.add(TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE));
		lstProj[0].ProjectName__c = 'ProjTest';				
		lstProj[0].CMNumber__c = '11111';				
		lstProj[0].PlaningPermitNumber__c = 'AAA';
		lstProj[0].SpearReferenceNumber__c ='34324';
		lstProj[0].SubdivisionPlanNumber__c = '4343';
		lstProj[0].Subdivision__c = 'Yes';
		lstProj[0].ACCC_Form__c = 'Yes';
		lstProj[0].CRAB_Form__c = 'No';
		lstProj[0].SAPStatus__c = 'PREQ';
		lstProj[0].SAPStatusFlag__c = 'CLSE';
		lstProj[0].ContestabilityType__c = 'IDIC';
		lstProj.add(TVE_TestUtility.createProject('test1',PROGRESS_BAR_STATUS,CON_TYPE));
		lstProj[1].ProjectName__c = 'ProjTest1';	
		lstProj[1].CMNumber__c = '22222';	
		lstProj[1].ContestabilityType__c = 'IDIC';
		lstProj[1].PlaningPermitNumber__c = 'AAA';
		lstProj[1].SpearReferenceNumber__c ='34324';
		lstProj[1].SubdivisionPlanNumber__c = 'dsdsf';
		lstProj[1].Subdivision__c = 'No';
		lstProj[1].ACCC_Form__c = 'No';
		lstProj[1].CRAB_Form__c = 'Yes';
		lstProj[1].SAPStatus__c = 'PRLP';
		lstProj[1].SAPStatusFlag__c = 'CLSE';
		Insert lstProj;
        
		Map<Id,String> recordMap = new Map<Id,String>(); 
		for (Project__c proj : lstProj) {
			recordMap.put(Proj.id, Proj.id);	
		}        
        Map<String,String> creatIntTaskMap = new Map<String,String>();
        creatIntTaskMap.put('Operation__c', 'Get');
        creatIntTaskMap.put('SObject__c', 'Project__c');       
        creatIntTaskMap.put('Type__c', 'GetCM');
		creatIntTaskMap.put('Status__c', 'In Progress');        
		creatIntTaskMap.put('RecordTypeID', CM_RTId);        
        TVE_IntegUtility.CreateInteTask(recordMap,creatIntTaskMap); 
		 
	}

	@isTest static void testMethod1() {
		User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];

		ConstructionMeasureSets__x mockedCM1 = new ConstructionMeasureSets__x(
							Cmnum__c = '11111',
							Cmtxt__c = 'Test',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'IDIC',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE CERC CERE PPRC'
		);

		ConstructionMeasureSets__x mockedCM2 = new ConstructionMeasureSets__x(
							Cmnum__c = '22222',
							Cmtxt__c = 'Test',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'IDIC',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE'
		);

		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM1);
		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM2);

		TVE_SAPInteg_GetCMToSAP getCM =  new TVE_SAPInteg_GetCMToSAP();       
            system.runas(testUser){                        
                System.enqueueJob(getCM);
			}  
			
	}

	@isTest static void testMethod2() {
		User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];

		ConstructionMeasureSets__x mockedCM1 = new ConstructionMeasureSets__x(
							Cmnum__c = '55555',
							Cmtxt__c = 'Test11',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'IDIC',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE CERC CERE PPRC'
		);

		ConstructionMeasureSets__x mockedCM2 = new ConstructionMeasureSets__x(
							Cmnum__c = '44444',
							Cmtxt__c = 'Test22',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'IDIC',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE'
		);

		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM1);
		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM2);

		TVE_SAPInteg_GetCMToSAP getCM =  new TVE_SAPInteg_GetCMToSAP();       
            system.runas(testUser){                        
                System.enqueueJob(getCM);
			}  
			
	}

	@isTest static void testMethod3() {
		User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];

		ConstructionMeasureSets__x mockedCM1 = new ConstructionMeasureSets__x(
							Cmnum__c = '99999',
							Cmtxt__c = 'Test1',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'Invoice',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE CERC CERE PPRC'
		);

		ConstructionMeasureSets__x mockedCM2 = new ConstructionMeasureSets__x(
							Cmnum__c = '88888',
							Cmtxt__c = 'Test1',
							ZzPrjOfficer__c = 'ABC',
							ZzContestability__c = 'Invoice',
							ZzTownPermit__c = 'xxx',
							ZzLodgeSpear__c = 'DEF',
							ZzSubdivision__c = 'Y',
							ZzSubDivi__c = 'Y',
							ZzAccc__c = 'N',
							ZzCrab__c = 'Y',
							UserStatus__c = 'CLSE'
		);

		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM1);
		TVE_SAPInteg_GetCMToSAP.mockedExtCM.add(mockedCM2);

		TVE_SAPInteg_GetCMToSAP getCM =  new TVE_SAPInteg_GetCMToSAP();       
            system.runas(testUser){                        
                System.enqueueJob(getCM);
			}  
			
	}

}