force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master detail relationship between account and artefact</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Record type for contract</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Record type for other</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

force-app/main/default/classes/tveuploadcomponentController.cls
/*
@author  : lakshay.sharma@ausnetservices.com.au
@created : 3rd Jan 2020
@Description : Controller class for tveuploadcomponent
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
public with sharing class tveuploadcomponentController {
    
    @AuraEnabled
    public static id getArtefact (id projectId)
    {
        system.debug('in artefact method');
        Artefact__c artRec=new Artefact__c();
        artRec.Classification__c='Contract';
        artRec.Project__c=projectId;
        artRec.Name='Dummy';
        insert artRec;
        system.debug(artRec);
        return artRec.id;
            
    }
    @AuraEnabled
    public static boolean deleteArtefact(id projectId,string docId)
    {
        List<Artefact__c> dummyArtList = [SELECT Id, Name FROM Artefact__c WHERE project__c =: projectId AND Name = 'Dummy'];
        if(!dummyArtList.isEmpty())
            delete dummyArtList;
        if(String.isNotEmpty(docId)) {
            List<ContentDocument> cd = [SELECT Id FROM ContentDocument WHERE Id =: docId];
            if(!cd.isEmpty())
                delete cd;
        }
        
        return true;
    }
    
    @AuraEnabled
    public static Artefact__c saveFile(Id idParent, String strFileName,string artID,String classification,Id accountId) {
        // Decoding base64Data
        system.debug('idParent' +idParent);
        system.debug('accountId' +accountId);
        system.debug('classification' +classification);
        Artefact__c art = [select id,Classification__c,Account__c,Name,Project__c from Artefact__c where id=:artId];
        art.Classification__c= classification;
        art.Account__c=accountId;
        art.Project__c=idParent;
        art.Name=strFileName;
        //Record type has been handled using classification field in before insert/update artefact trigger 
        // art.RecordTypeId = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get('Other').getRecordTypeId();
        update art;
        system.debug('updated Artefact:'+art);
        return art;
 }
    @AuraEnabled 
    public static Id fetchProject(string recordId){
        Id ProjectId;
        Task t = [select id,WhatId from Task where id=:recordId];
        ProjectId=t.Whatid;
        return ProjectId;
    }
    
}