force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/ElectronicPaymentReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ElectronicPaymentReferenceNumber__c</fullName>
    <label>Electronic Payment Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Company name of the applicant if applicable</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/IsPropertyOwner__c.field-meta.xml
<CustomField>
    <fullName>IsPropertyOwner__c</fullName>
    <description>Property owner of the installation place</description>
    <label>Is Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerCompany__c.field-meta.xml
<CustomField>
    <fullName>OwnerCompany__c</fullName>
    <description>Name of owner company with which lead is affiliated. Up to 255 characters are allowed in this field.</description>
    <label>Owner Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerLastName__c.field-meta.xml
<CustomField>
    <fullName>OwnerLastName__c</fullName>
    <description>Last name of the property owner, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Owner Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PaymentReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>PaymentReferenceNumber__c</fullName>
    <label>Payment Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PropertyOwnerContact__c.field-meta.xml
<CustomField>
    <fullName>PropertyOwnerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Property Owner)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/RelationshipToOwner__c.field-meta.xml
<CustomField>
    <fullName>RelationshipToOwner__c</fullName>
    <label>Relationship To Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered Electrical Contractor (REC)</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Accredited Service Provider - AusNet Services</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Family Member/Friend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/Trig_ContentDocumentLink_Test.cls
/*
@author  : brajesh.tiwary@ausnetservices.com.au
@created : 27 Jan 2020
@Description : test class for Aura Trig_ContentDocumentLink
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public class Trig_ContentDocumentLink_Test {
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static final string testUserEmail = 'testuser@TVEArtefactControllerTest.com';
    public static testMethod void testDocCreation(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        eSignSettings__c eSign = [Select id, AES_Key__c from eSignSettings__c];
        Test.startTest();
        System.runAs(testUser){
            Project__c projObj = [select id from Project__c limit 1];
            Artefact__c artObj = [select id from Artefact__c LIMIT 1];
            system.debug('artObj'+artObj);
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguin.jpg',
                VersionData = Blob.valueOf('Test Content1'),
                IsMajorVersion = true,
                ContentLocation='S '
            );
            insert contentVersion;
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = artObj.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            Database.insert(cdl);
            test.stopTest();
        }
    }
    public static testMethod void testDocDeletion(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        eSignSettings__c eSign = [Select id, AES_Key__c from eSignSettings__c];
        Test.startTest();
        System.runAs(testUser){
            Project__c projObj = [select id from Project__c limit 1];
            Artefact__c artObj = [select id from Artefact__c LIMIT 1];
            system.debug('artObj'+artObj);
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins1.jpg',
                VersionData = Blob.valueOf('Test Content2'),
                IsMajorVersion = true,
                ContentLocation='S '
            );
            insert contentVersion; 
            List<ContentDocumentLink> linkToDel = new List<ContentDocumentLink>();
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = artObj.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            insert cdl;
            delete cdl;
            test.stopTest();
        }
    }
    @TestSetup
    public static void setup() {
        
        //Create User
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
		eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
        eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
        insert eSignObj;        
        //Create Business Account
        Account testInstaller = TVE_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;
        Contact con = new Contact();
        con.LastName = 'Test';
        insert con;
        
        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        projObj.OwnerLastName__c = 'testLastName2';
        projObj.OwnerCompany__c = 'testOwnerComp2';
        projObj.PropertyOwnerContact__c = con.Id;
        projObj.IsPropertyOwner__c = 'No';
        projObj.Company__c = 'Test12';
        projObj.PaymentReferenceNumber__c = '123';
        projObj.RelationshipToOwner__c = 'Developer';
        Insert projObj;
        
        Artefact__c artObj = TVE_TestUtility.createInvoiceArtefact('NameTest',projObj.Id,testInstaller.Id);
        artObj.Status__c='Pending Payment';
        artObj.InvoicePaidDate__c=null;
        artObj.ElectronicPaymentReferenceNumber__c=null;
        insert artObj;
        
    }  

}