force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Additional_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Additional_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine1ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine1ExGST__c</fullName>
    <label>Amount Line 1 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine2ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine2ExGST__c</fullName>
    <label>Amount Line 2 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine3ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine3ExGST__c</fullName>
    <label>Amount Line 3 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine1__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine1__c</fullName>
    <label>Invoice Type Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine2__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine2__c</fullName>
    <label>Invoice Type Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine3__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine3__c</fullName>
    <label>Invoice Type Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine1__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine1__c</fullName>
    <label>Material Code Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine2__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine2__c</fullName>
    <label>Material Code Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine3__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine3__c</fullName>
    <label>Material Code Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine3__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Salesforce Cloud</fullName>
            </value>
            <value>
                <fullName>SiteCore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Sales Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInt_RequestInvoiceTest.cls
@isTest
public with sharing class TVE_SAPInt_RequestInvoiceTest {

    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static final string CON_TYPE = 'IDIC';
    public static final string CLASSIFICATION_INVOICE = 'Invoice';
    public static ID invoiceRecordType = Schema.SObjectType.Artefact__c.getRecordTypeInfosByName().get('Invoice').getRecordTypeId();
    public static final string testUserEmail = 'testuser@TVEArtefactControllerTest.com';

    private class RestMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{\"status\":\"201\",\"statusMessage\":\"Created\",\"payload\":{\"d\":{\"NotificationNumber\":\"100108471\"}}}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }

    private class RestMockFailure implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{\"status\":\"400\"}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(401);
            res.setStatus('Unauthorized');
            return res;
        }
    }

    @TestSetup
    public static void setup() {
        
         //Create User
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;

        Account testInstaller = TVE_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;
        
        //Project__c projObj = TVE_TestUtility.createIntegrationProject('test',PROGRESS_BAR_STATUS,CON_TYPE,testInstaller.id);
        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        projObj.SalesOrder__c = '123456';
        insert projObj;

        List<Artefact__c> artObjList = new list<Artefact__c>();

        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test1',projObj.Id,testInstaller.id));
        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test2',projObj.Id,testInstaller.id));
        artObjList[0].Source__c='Salesforce Cloud';
        artObjList[0].MaterialCodeLine1__c='CCAAA001';
        artObjList[0].AmountLine1ExGST__c=123456;
        artObjList[0].InvoiceTypeLine1__c='Site Assessment Fee';
        artObjList[0].MaterialCodeLine2__c='CCAAA001';
        artObjList[0].AmountLine2ExGST__c=123456;
        artObjList[0].InvoiceTypeLine2__c='Site Assessment Fee';
        artObjList[0].MaterialCodeLine3__c='CCAAA001';
        artObjList[0].AmountLine3ExGST__c=123456;
        artObjList[0].InvoiceTypeLine3__c='Site Assessment Fee';
        artObjList[0].Bill_To__c='123456';
        artObjList[0].Additional_Invoice__c= true;
        artObjList[1].Source__c='Salesforce Cloud';
        artObjList[1].MaterialCodeLine1__c='CCAAA001';
        artObjList[1].AmountLine1ExGST__c=123456;
        artObjList[1].InvoiceTypeLine1__c='Site Assessment Fee';
        artObjList[1].MaterialCodeLine2__c='CCAAA001';
        artObjList[1].AmountLine2ExGST__c=123456;
        artObjList[1].InvoiceTypeLine2__c='Site Assessment Fee';
        artObjList[1].MaterialCodeLine3__c='CCAAA001';
        artObjList[1].AmountLine3ExGST__c=123456;
        artObjList[1].InvoiceTypeLine3__c='Site Assessment Fee';
        artObjList[1].Bill_To__c='123456';
        artObjList[1].Additional_Invoice__c= true;
        insert artObjList;

        List<Integration_Task__c> IntgnTsklist = [SELECT Operation__c, SObject__c, ParentId__c, Type__c, Status__c FROM Integration_Task__c
                                                  WHERE ParentId__c =:artObjList[0].Id OR ParentId__c =:artObjList[1].Id];
        
        IntgnTsklist[0].Status__c = 'In Progress';
        IntgnTsklist[1].Status__c = 'In Progress';
        update IntgnTsklist;
    }
    public static testMethod void RequestInvoiceSApInteg(){
        
        User testUser = UtilDatabase_Test.getTestUser();
        
        Test.startTest();
        System.runAs(testUser){            
            TVE_SAPInteg_RequestInvoice reqInv = new TVE_SAPInteg_RequestInvoice();
            
            Test.setMock(HttpCalloutMock.class, new RestMock());    
            // enqueue the job for processing                
            TVE_SAPInteg_RequestInvoice.requestInvoiceInteg();
            //System.debug('TVE_SAPInteg_RequestInvoice - Job Id : ' + jobID);  
        }
        Test.stopTest();
    }
    public static testMethod void RequestInvoiceSApIntegFailure(){
     User testUser = UtilDatabase_Test.getTestUser();
        Test.startTest();
        System.runAs(testUser){  
            TVE_SAPInteg_RequestInvoice reqInv = new TVE_SAPInteg_RequestInvoice();
            Test.setMock(HttpCalloutMock.class, new RestMockFailure());
            // enqueue the job for processing        
			TVE_SAPInteg_RequestInvoice.requestInvoiceInteg();
            //ID jobID = System.enqueueJob(reqInv);              
            //System.debug('TVE_SAPInteg_RequestInvoice - Job Id : ' + jobID);
        }
        Test.stopTest();
        
    }
}