force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/tvegetpicklistvaluesTest.cls
/*
@author  : lakshay.sharma@ausnetservices.com.au
@created : 21st Jan 2020
@Description : Test class for tveuploadcomponentController
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public class tvegetpicklistvaluesTest {
   
    Private static Account acc;
    Private static Project__c prj;
    Private static Artefact__c art;
    Private static string PROGRESS_BAR_STATUS = 'Allocated for initial assessment';
    Private static string CONTESTATIBILITY_TYPE = 'IDEC';
    
    @isTest static void getpicklistvaluestest(){
        eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
        eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
        insert eSignObj;
        acc=TVE_TestUtility.createBusinessAccount('TestAccount');
        insert acc;
    	prj=TVE_TestUtility.createProject('TestRef1',PROGRESS_BAR_STATUS,CONTESTATIBILITY_TYPE);
        insert prj;
        art=TVE_TestUtility.createOfferArtefact('TestArtefact',prj.Id,acc.Id);
        insert art;
        
		Test.startTest();
        tvegetpicklistvalues.getPickListValue(art,'Classification__c');
        Test.stopTest();
    }
   

}