force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Record type for contract</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/tveuploadcomponentControllerTest.cls
/*
@author  : lakshay.sharma@ausnetservices.com.au
@created : 7th Jan 2020
@Description : Test class for tveuploadcomponentController
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public with sharing class tveuploadcomponentControllerTest {
    
    Private static String strFileName = 'TestImage';
    Private static String base64Data='Testbase64Data';  
    Private static String Classification='Contract';
    Private static Account acc;
    Private static Project__c prj;
    Private static string PROGRESS_BAR_STATUS = 'Allocated for initial assessment';
    Private static string CONTESTATIBILITY_TYPE = 'IDEC';
    @istest static void tveuploadcomponentControllerTestForArtefact(){
        eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
        eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
        insert eSignObj;
		acc=TVE_TestUtility.createBusinessAccount('TestAccount');
        insert acc;
    	prj=TVE_TestUtility.createProject('TestRef1',PROGRESS_BAR_STATUS,CONTESTATIBILITY_TYPE);
        insert prj;
        Artefact__c art=TVE_TestUtility.createOfferArtefact('testArt',prj.id,acc.id);
        insert art;
        Task tsk= TVE_TestUtility.createTask(prj.id,userinfo.getUserId(),'test');
        insert tsk;
        TVE_TestUtility.insertFile(prj.id);
        id docId=[SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument limit 1].id;
        test.startTest();
        tveuploadcomponentController.saveFile(prj.Id,strFileName,art.id,Classification,acc.Id);
        tveuploadcomponentController.getArtefact(prj.id);
        tveuploadcomponentController.deleteArtefact(prj.id,docId);
        tveuploadcomponentController.fetchProject(tsk.id);
        
        test.stopTest();
        }
        
    }