force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/AmountLine1ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine1ExGST__c</fullName>
    <label>Amount Line 1 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine2ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine2ExGST__c</fullName>
    <label>Amount Line 2 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine3ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine3ExGST__c</fullName>
    <label>Amount Line 3 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine1__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine1__c</fullName>
    <label>Invoice Type Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine2__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine2__c</fullName>
    <label>Invoice Type Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine3__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine3__c</fullName>
    <label>Invoice Type Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine1__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine1__c</fullName>
    <label>Material Code Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine2__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine2__c</fullName>
    <label>Material Code Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine3__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine3__c</fullName>
    <label>Material Code Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine3__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Record type for other</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/WorkOrder.recordType-meta.xml
<RecordType>
    <fullName>WorkOrder</fullName>
    <active>true</active>
    <label>WorkOrder</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/CMnumber__c.field-meta.xml
<CustomField>
    <fullName>CMnumber__c</fullName>
    <label>CM number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Sales Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAP_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>SAP_Integration_Status__c</fullName>
    <label>SAP Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Create</fullName>
            </value>
            <value>
                <fullName>Ready to Update</fullName>
            </value>
            <value>
                <fullName>Ready to Get</fullName>
            </value>
            <value>
                <fullName>Pending Triage</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_InitiationTest.cls
/*
@author  : lakshay.sharma@ausnetservices.com.au
@created : 06 Mar 2020
@Description : Test Class for TVE_SAPInteg_Initiation
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------
*/
@isTest
public class TVE_SAPInteg_InitiationTest {
    public static final string testUserEmail = 'testuser@TVEIntegInitiationControllerTest.com';
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static ID invoiceRecordType = Schema.SObjectType.Artefact__c.getRecordTypeInfosByName().get('Invoice').getRecordTypeId();
    public static ID intTask_arte_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('Artefact').getRecordTypeId();
    public static ID intTask_opp_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
    public static ID intTask_workord_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('WorkOrder').getRecordTypeId();
    
    //public static final string myAssigneeId='';
    private class RestMock implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{\"status\":\"201\",\"statusMessage\":\"Created\",\"payload\":{\"d\":{\"NotificationNumber\":\"100108471\"}}}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    @testSetup
    public static void setup() {
    
        
        Account testAcc = TVE_TestUtility.createBusinessAccount('Business Account');
        
        List<Project__c> lstProj = new List<Project__c>();
		lstProj.add(TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE));
		lstProj[0].CMNumber__c = '12345';	
        lstProj[0].SalesOrder__c='123345';
        lstProj[0].sap_integration_status__c='Ready to Create';
        lstProj.add(TVE_TestUtility.createProject('test1',PROGRESS_BAR_STATUS,CON_TYPE));
        Insert lstProj;
        
        
        
        List<Artefact__c> lstArt=new List<Artefact__c>();
        lstArt.add(TVE_TestUtility.createArtefact('test',lstProj[0].Id,testAcc.Id));
        
        Insert lstArt;
        
        List<Artefact__c> atrlistproj= new List<Artefact__c>();
        atrlistproj=[SELECT Id,Project__c,RecordTypeId FROM Artefact__c WHERE Project__c=:lstProj[0].Id and RecordTypeId=:invoiceRecordType];
        for(Artefact__c item:atrlistproj){
            item.MaterialCodeLine1__c='CCAAA001';
        	item.InvoiceTypeLine1__c='Other';
            item.Bill_To__c='Test';
            item.AmountLine1ExGST__c=19.23;
            item.MaterialCodeLine2__c='CCAAA001';
            item.InvoiceTypeLine2__c='Other';
            item.AmountLine2ExGST__c=20.25;
            item.MaterialCodeLine3__c='CCAAA001';
            item.InvoiceTypeLine3__c='Other';
            item.AmountLine3ExGST__c=30.25;
        	system.debug('artforproj'+item);
            
            
        }
        update atrlistproj;
        
        
        
        Map<Id,String> recordMapReady = new Map<Id,String>(); 
        recordMapReady.put(lstProj[1].Id, 'ParentId');
        Map<String,String> creatIntTaskMapReady = new Map<String,String>();
        creatIntTaskMapReady.put('Operation__c', 'Get');
        creatIntTaskMapReady.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady.put('Type__c', 'CreateCustomer');
        creatIntTaskMapReady.put('Status__c', 'Ready');  
        
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady);
        
        Map<String,String> creatIntTaskMapReady1 = new Map<String,String>();
        creatIntTaskMapReady1.put('Operation__c', 'Get');
        creatIntTaskMapReady1.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady1.put('Type__c', 'CreateCustomer');
        creatIntTaskMapReady1.put('Status__c', 'Ready');  
       
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady1);
        
        
        
        Map<String,String> creatIntTaskMapReady3 = new Map<String,String>();
        creatIntTaskMapReady3.put('Operation__c', 'Get');
        creatIntTaskMapReady3.put('SObject__c', 'Artefact__c');       
        creatIntTaskMapReady3.put('Type__c', 'GetInvoice');
        creatIntTaskMapReady3.put('RecordTypeID',intTask_arte_Id);
        creatIntTaskMapReady3.put('Status__c', 'Ready');
        
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady3);
        
        Map<String,String> creatIntTaskMapReady4 = new Map<String,String>();
        creatIntTaskMapReady4.put('Operation__c', 'Get');
        creatIntTaskMapReady4.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady4.put('Type__c', 'CreateCustomer');
        creatIntTaskMapReady4.put('Status__c', 'Ready'); 
        
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady4);
        
        Map<String,String> creatIntTaskMapReady5 = new Map<String,String>();
        creatIntTaskMapReady5.put('Operation__c', 'Get');
        creatIntTaskMapReady5.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady5.put('Type__c', 'UpdateCM');
        creatIntTaskMapReady5.put('Status__c', 'Ready');
        
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady5);
        
        Map<String,String> creatIntTaskMapReady6 = new Map<String,String>();
        creatIntTaskMapReady6.put('Operation__c', 'Get');
        creatIntTaskMapReady6.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady6.put('Type__c', 'CreateMasterNoti');
        creatIntTaskMapReady6.put('Status__c', 'Ready'); 
        
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady6);
        
        Map<String,String> creatIntTaskMapReady7 = new Map<String,String>();
        creatIntTaskMapReady7.put('Operation__c', 'Create');
        creatIntTaskMapReady7.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady7.put('Type__c', 'CreateWork');
        creatIntTaskMapReady7.put('Status__c', 'Ready');  
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady7);
        
        Map<String,String> creatIntTaskMapReady8 = new Map<String,String>();
        creatIntTaskMapReady8.put('Operation__c', 'Get');
        creatIntTaskMapReady8.put('SObject__c', 'Artefact__c');       
        creatIntTaskMapReady8.put('Type__c', 'GetCMArtefact');
        creatIntTaskMapReady8.put('Status__c', 'Ready');
        creatIntTaskMapReady8.put('RecordTypeID',intTask_arte_Id);
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady8);
        
       
        
        Map<String,String> creatIntTaskMapReady12 = new Map<String,String>();
        creatIntTaskMapReady12.put('Operation__c', 'Get');
        creatIntTaskMapReady12.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady12.put('Type__c', 'GetCustomer');
        creatIntTaskMapReady12.put('Status__c', 'Ready');  
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady12);
        
        Map<String,String> creatIntTaskMapReady13 = new Map<String,String>();
        creatIntTaskMapReady13.put('Operation__c', 'Get');
        creatIntTaskMapReady13.put('SObject__c', 'Opportunity');       
        creatIntTaskMapReady13.put('Type__c', 'GetConstNoti');
        creatIntTaskMapReady13.put('Status__c', 'Ready');
        creatIntTaskMapReady13.put('RecordTypeID',intTask_opp_Id);
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady13);
        
        
        Map<String,String> creatIntTaskMapReady14 = new Map<String,String>();
        creatIntTaskMapReady14.put('Operation__c', 'Get');
        creatIntTaskMapReady14.put('SObject__c', 'WorkOrder');       
        creatIntTaskMapReady14.put('Type__c', 'GetConstWO');
        creatIntTaskMapReady14.put('Status__c', 'Ready');
        creatIntTaskMapReady14.put('RecordTypeID',intTask_workord_Id);
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady14);
        
        Map<String,String> creatIntTaskMapReady15 = new Map<String,String>();
        creatIntTaskMapReady15.put('Operation__c', 'Get');
        creatIntTaskMapReady15.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady15.put('Type__c', 'GetCM');
        creatIntTaskMapReady15.put('Status__c', 'Ready');
        //creatIntTaskMapReady15.put('RecordTypeID',intTask_workord_Id);
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady15);
        
        Map<String,String> creatIntTaskMapReady16 = new Map<String,String>();
        creatIntTaskMapReady16.put('Operation__c', 'Get');
        creatIntTaskMapReady16.put('SObject__c', 'Artefact');       
        creatIntTaskMapReady16.put('Type__c', 'RequestInvoice');
        creatIntTaskMapReady16.put('Status__c', 'Ready');
        creatIntTaskMapReady16.put('RecordTypeID',intTask_arte_Id);
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady16);
    }
   
    
    @istest public static void testInitiation(){
            
       

        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
        
        PermissionSet psa = [SELECT Id FROM PermissionSet WHERE Name = 'Execute_SAP_Integration'];
        insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = psa.Id);
        
        
        List<Integration_task__c> listintTask=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='In Progress'];
        List<Integration_task__c> listintTask2=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='Ready'];
        System.runAs(testUser){
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        TVE_SAPInteg_Initiation.startInitiation();
        test.stopTest();
        
        }
        
    }
    @istest static void testInitiationwithoutpermission(){
            
       

        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
		
  
        List<Integration_task__c> listintTask=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='In Progress'];
        List<Integration_task__c> listintTask2=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='Ready'];
        System.runAs(testUser){
        try {
             TVE_SAPInteg_Initiation.startInitiation();
        } catch(Exception e) {
            
        }
      
        
        
        }
        
    } 
    
}