force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master detail relationship between account and artefact</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Additional_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Additional_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Electronic_Payment_Link__c.field-meta.xml
<CustomField>
    <fullName>Electronic_Payment_Link__c</fullName>
    <label>Electronic Payment Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Salesforce Cloud</fullName>
            </value>
            <value>
                <fullName>SiteCore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Record type for other</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ApplicantContact__c.field-meta.xml
<CustomField>
    <fullName>ApplicantContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Applicant Contact)</relationshipLabel>
    <relationshipName>Projects_App_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/AuthorisedRepresentative__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TV-1422</description>
    <label>Authorised Representative</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Authorised Representative)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ElectronicPaymentLink__c.field-meta.xml
<CustomField>
    <fullName>ElectronicPaymentLink__c</fullName>
    <label>Electronic Payment Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/FirmOfferDueDate__c.field-meta.xml
<CustomField>
    <fullName>FirmOfferDueDate__c</fullName>
    <label>Firm Offer Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/InvoiceDueDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDueDate__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/IsPropertyOwner__c.field-meta.xml
<CustomField>
    <fullName>IsPropertyOwner__c</fullName>
    <description>Property owner of the installation place</description>
    <label>Is Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerCompany__c.field-meta.xml
<CustomField>
    <fullName>OwnerCompany__c</fullName>
    <description>Name of owner company with which lead is affiliated. Up to 255 characters are allowed in this field.</description>
    <label>Owner Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerLastName__c.field-meta.xml
<CustomField>
    <fullName>OwnerLastName__c</fullName>
    <description>Last name of the property owner, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Owner Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PropertyOwnerContact__c.field-meta.xml
<CustomField>
    <fullName>PropertyOwnerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Property Owner)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SiteOwner__c.field-meta.xml
<CustomField>
    <fullName>SiteOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TV-1422</description>
    <label>Site Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Site Owner)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/TVE_File_Classification_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>TVE File Classification Mapping</label>
    <pluralLabel>TVE File Classification Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
                <default>true</default>
                <label>Prelim Estimate</label>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_Artefact_Util_Test.cls
/*
@author  : pavan.dave@ausnetservices.com.au
@created : 13th Jan 2020
@Description : test class for TVE_Artefact_Util
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
12 March            Lakshay Sharma
-----------------------------------------------------------------------------------------
*/
@isTest
public with sharing class TVE_Artefact_Util_Test {
    public static final string testUserEmail = 'testuser@TVEArtefactUtilTest.com';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static final string CON_TYPE = 'IDIC';
    public static final string CLASSIFICATION_INVOICE = 'Invoice';
    public static final string CLASSIFICATION_TECH_SPEC = 'Technical Specs';
    public static ID invoiceRecordType = Schema.SObjectType.Artefact__c.getRecordTypeInfosByName().get('Invoice').getRecordTypeId();

    @TestSetup
    public static void setup() {
        
        //Create User
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
        
        //Create Business Account
        List<Account> lstAcc = new List<Account>();
        lstAcc.add(TVE_TestUtility.createBusinessAccount('John Smith'));
        lstAcc.add(TVE_TestUtility.createBusinessAccount('J Doe'));
        Insert lstAcc;

        eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
        eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
        insert eSignObj;
        contact con=TVE_TestUtility.createContact();
        insert con;
        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        projObj.OwnerLastName__c = 'testLastName';
        projObj.OwnerCompany__c = 'testOwnerComp';
        projObj.PropertyOwnerContact__c = con.Id;
        projObj.IsPropertyOwner__c = 'Yes';
        //projObj.AuthorisedRepresentative__c = lstAcc[0].Id;
        //projObj.SiteOwner__c = lstAcc[1].Id;
        projObj.ApplicantContact__c=con.id;
        Insert projObj;
        
    }

    // This test method covers both methods 
    // 1. PopulateAccount
    // 2. PopulateRecordTypeId
    public static testMethod void testPopulateAccount_BeforeInsert(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        Test.startTest();
        System.runAs(testUser){
            Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
            Account acc2 = [SELECT Id, Name FROM Account WHERE Name =: 'J Doe' LIMIT 1];
            Project__c projObj1 = [select id,AuthorisedRepresentative__c from Project__c ];
            Artefact__c artObj1 = new Artefact__c();
            artObj1.Project__c = projObj1.Id;
            artObj1.Classification__c = CLASSIFICATION_INVOICE;
            Insert artObj1;

            Artefact__c updatedArtefact = [SELECT id, Account__c FROM Artefact__c WHERE Id =: artObj1.Id LIMIT 1];
            System.assertEquals(projObj1.AuthorisedRepresentative__c, updatedArtefact.Account__c);
        }
        Test.stopTest();
    }

    // This test method covers both methods 
    // 1. PopulateAccount
    // 2. PopulateRecordTypeId
    public static testMethod void testPopulateRecordTypeId_BeforeUpdate(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
        Project__c projObj1 = [select id from Project__c ];
        Artefact__c artObj1 = new Artefact__c();
        artObj1.Project__c = projObj1.Id;
        artObj1.Classification__c = CLASSIFICATION_INVOICE;
        Insert artObj1;

        Test.startTest();
        System.runAs(testUser){

            Artefact__c updatedArtefact = [SELECT id, RecordType.Name FROM Artefact__c WHERE Id =: artObj1.Id LIMIT 1];
            // According to mapping TVE_File_Classification_Mapping__mdt
            System.assertEquals('Invoice', updatedArtefact.RecordType.Name);

            artObj1.Classification__c = CLASSIFICATION_TECH_SPEC;
            Update artObj1;

            updatedArtefact = [SELECT id, RecordType.Name FROM Artefact__c WHERE Id =: artObj1.Id LIMIT 1];
            // According to mapping TVE_File_Classification_Mapping__mdt
            System.assertEquals('Other', updatedArtefact.RecordType.Name);
        }
        Test.stopTest();
    }
    // This test method covers both methods 
    // 1. DueDatePopup
    // 2. EPaymentLinkPopup
    public static testMethod void testdueDatePopUp_AfterInsert(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
       
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
        Project__c projObj1 = [select id from Project__c ];
        
        List<Artefact__c> artObjList = new list<Artefact__c>();
        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test',projObj1.Id,acc1.id));
        artObjList.add(TVE_TestUtility.createOfferArtefact('test',projObj1.Id,acc1.id));
        artObjList[0].Status__c='Pending Payment';
        artObjList[0].DueDate__c=system.today();
        artObjList[0].Electronic_Payment_Link__c='www.test.com';
        artObjList[1].DueDate__c=system.today();
        Insert artObjList;

        Test.startTest();
        System.runAs(testUser){

            Project__c updatedProject = [SELECT id, InvoiceDueDate__c,ElectronicPaymentLink__c,FirmOfferDueDate__c   FROM Project__c];
           // According to mapping TVE_File_Classification_Mapping__mdt
            System.assertEquals(updatedProject.InvoiceDueDate__c, artObjList[0].DueDate__c);
            System.assertEquals(updatedProject.ElectronicPaymentLink__c, artObjList[0].Electronic_Payment_Link__c);
            System.assertEquals(updatedProject.FirmOfferDueDate__c, artObjList[1].DueDate__c);
        }
        Test.stopTest();
    }
    public static testMethod void testdeleteArtefact(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
       
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
        Project__c projObj1 = [select id from Project__c ];
        
        List<Artefact__c> artObjList = new list<Artefact__c>();
        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test',projObj1.Id,acc1.id));
        artObjList.add(TVE_TestUtility.createOfferArtefact('test',projObj1.Id,acc1.id));
        artObjList[0].Status__c='Pending Payment';
        artObjList[0].DueDate__c=system.today();
        artObjList[0].Electronic_Payment_Link__c='www.test.com';
        artObjList[1].DueDate__c=system.today();
        Insert artObjList;

        Test.startTest();
        Database.delete(artObjList);
        Test.stopTest();
    }

    //test class for TVE11-2047
    public static testMethod void testRequestInvoiceInteg_AfterInsert(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
       
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
        Project__c projObj1 = [select id from Project__c ];
        
        List<Artefact__c> artObjList = new list<Artefact__c>();

        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test1',projObj1.Id,acc1.id));
        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test2',projObj1.Id,acc1.id));
        artObjList[0].Source__c='Salesforce Cloud';
        artObjList[1].Source__c='Salesforce Cloud';
        artObjList[0].Additional_Invoice__c= true;
        artObjList[1].Additional_Invoice__c= true;        
        System.debug('artefact List before insertion'+artObjList);

        Test.startTest();
        System.runAs(testUser){
            Insert artObjList;
            List<Artefact__c> artfctLst = [SELECT Id FROM Artefact__c WHERE Source__c = 'SiteCore'];
            List<Integration_Task__c> IntgnTsklist = [SELECT Operation__c, SObject__c, ParentId__c, Type__c, Status__c FROM Integration_Task__c
                                                      WHERE ParentId__c =:artObjList[0].Id OR ParentId__c =:artObjList[1].Id];
            System.debug('########@@@@@@@'+IntgnTsklist);

           
            System.assertEquals(2, IntgnTsklist.size(), 'Proper Insertion of Integration Task did not happen');
            System.assertEquals(IntgnTsklist[0].Type__c, 'RequestInvoice','Type mismatch');
            System.assertEquals(IntgnTsklist[0].Status__c, 'Ready','Status mismatch');
            System.assertEquals(IntgnTsklist[0].SObject__c, 'Artefact__c','Sobject mismatch');
            System.assertEquals(IntgnTsklist[1].Type__c, 'RequestInvoice','Type mismatch');
            System.assertEquals(IntgnTsklist[1].Status__c, 'Ready','Status mismatch');
            System.assertEquals(IntgnTsklist[1].SObject__c, 'Artefact__c','Sobject mismatch');

        }
        Test.stopTest();
    }
    
    public static testMethod void testafterUpdateArtefact(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
       
        Account acc1 = [SELECT Id, Name FROM Account WHERE Name =: 'John Smith' LIMIT 1];
        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        projObj.ProjectAssigmentStatus__c='Payment Pending';
        List<Artefact__c> artObjList = new list<Artefact__c>();

        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test',projObj.Id,acc1.id));
        artObjList.add(TVE_TestUtility.createInvoiceArtefact('test',projObj.Id,acc1.id));
        Insert artObjList;
        
        Map<Id,List<Artefact__c>> mapofprojectandart= new Map<Id,List<Artefact__c>>();
        mapofprojectandart.put(projObj.Id,artObjList);
        
    }
}