force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <description>Invoice number</description>
    <label>Invoice number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_External_URL__mdt/TVE_External_URL__mdt.object-meta.xml
<CustomObject>
    <label>TVE External URL</label>
    <pluralLabel>TVE External URLs</pluralLabel>
</CustomObject>

force-app/main/default/classes/TVE_InvoicePreviewController.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 20th Dec 2019
  @Description : Controller class for Aura TVE_InvoicePreview
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  15 Apr 2020      dave.pavan@in.ibm.com            TV-2809: Dynamic Payment URL 
  -----------------------------------------------------------------------------------------
*/
public with sharing class TVE_InvoicePreviewController {
    public static String Artefact_Invoice_RT = 'Invoice';

    @AuraEnabled(cacheable=true)
    public static InvoiceWrapper getInvoices(string recordId) {
        id loggedInUser= UserInfo.getUserId();
        User u =[select isPortalenabled from user where id=:loggedInUser limit 1];
        System.debug('u.isPortalEnabled'+u.isPortalEnabled);
        InvoiceInfo invWrpItem = new InvoiceInfo();
        list<InvoiceInfo> listWrapper = new list<InvoiceInfo>();
        InvoiceWrapper invwrapper= new InvoiceWrapper();

        Id Artefact_Invoice_RT_Id = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get(Artefact_Invoice_RT).getRecordTypeId();

        List<Artefact__c> lstArtfct =  new List<Artefact__c>([SELECT Id, Name , Classification__c , DueDate__c, 
                                                                    InvoiceDate__c, TotalAmount__c,
                                                                    InvoiceNumber__c, Status__c
                                                                FROM Artefact__c 
                                                                WHERE Project__c = :recordId
                                                                AND RecordTypeId = :Artefact_Invoice_RT_Id
                                                                ]);
        System.debug('lstArtfct in class'+ lstArtfct+'record id'+recordId);
        
        if(!lstArtfct.isEmpty())
        {
            Set<id> artfctIds = new Set<id>();
            for(Artefact__c item: lstArtfct){
                artfctIds.add(item.Id);
            }

            List<ContentDocumentLink> lstConDocLink = [SELECT ContentDocumentId, LinkedEntityId 
                                                    FROM ContentDocumentLink 
                                                    WHERE LinkedEntityId IN: artfctIds];
                        
            for(Artefact__c artfcItem: lstArtfct)                 
            {
                for(ContentDocumentLink conDocLinkItem : lstConDocLink) 
                {
                    if(artfcItem.Id == conDocLinkItem.LinkedEntityId)
                    {
                        invWrpItem = new InvoiceInfo();
                        invWrpItem.invNumber = artfcItem.InvoiceNumber__c;
                        invWrpItem.status = artfcItem.Status__c;
                        invWrpItem.invDate = artfcItem.InvoiceDate__c;
                        invWrpItem.dueDate = artfcItem.DueDate__c;   
                        invWrpItem.totAmount = artfcItem.TotalAmount__c;                    
                        invWrpItem.contentDocId = conDocLinkItem.ContentDocumentId;
                        listWrapper.add(invWrpItem);
                        break;
                    }                    
                }                                                     
            }           
        }
        
        if(u.IsPortalEnabled==true)
            invwrapper.isPortalUser=true;
        else
            invwrapper.isPortalUser=false;
        invwrapper.invList=listWrapper;

        String pymtURL = [SELECT Id, URL__c FROM TVE_External_URL__mdt 
                            WHERE DeveloperName = 'TVE_Make_a_Payment_URL' LIMIT 1].URL__c;
        invwrapper.paymentURL = pymtURL;
        return invwrapper;
    }
    
    public class InvoiceWrapper{
        @AuraEnabled public Boolean isPortalUser{get; set;}
        @AuraEnabled public List<InvoiceInfo> invList{get;set;}
        @AuraEnabled public string paymentURL{get;set;}
    }
    public class InvoiceInfo{
        @auraEnabled public string invNumber {get; set;}
        @auraEnabled public Date invDate {get; set;}
        @auraEnabled public Decimal totAmount {get; set;}
        @auraEnabled public Date dueDate {get; set;}
        @auraEnabled public String status {get; set;}
        @AuraEnabled public string contentDocId {get; set;}   
        @AuraEnabled public Boolean isPortalUser{get; set;}
    }
  

}