force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_Initiation.cls
/*
@author  : pavan.dave@ausnetservices.com.au
@created : 10 Feb 2020
@Description : Class for executing SAP Integration - Initiation part
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
12 feb 2020           Lakshay Sharma                 Added next queueable task
-----------------------------------------------------------------------------------------
*/
public with sharing class TVE_SAPInteg_Initiation
{
	public static void startInitiation()
	{
		Boolean hasPermission = FeatureManagement.checkPermission('Execute_SAP_Integration');

		if (hasPermission)
		{
			WOS_Initiation WOS = new WOS_Initiation();
			WOS.startInitiation();
		}
		else
		{
			throw new TVE_ConfigurationException('The current user doesn’t have permission to execute SAP integration.');
		}
	}

	private without sharing class WOS_Initiation
	{
		private void startInitiation()
		{
			Map<String, String>              initAPIMap     = new Map<String, String>();
			List<Integration_Task__c>        newIntTaskList = new List<Integration_Task__c>();
			Map<Integration_Task__c, String> artIDlist      = new Map<Integration_Task__c, String>();
			Map<Id, Artefact__c>             artefactMap    = new Map<Id, Artefact__c>();
			List<Id>                         ArtefactIdList = new List<Id>();

			// Here we go......
			List<Integration_Task__c> lstIntgTask = new List<Integration_Task__c>([SELECT Id, Status__c,Type__c,ParentId__c
																				   FROM Integration_Task__c
																				   WHERE Status__c ='Ready']);

			for (Integration_Task__c item: lstIntgTask)
			{
				//item.Status__c = 'In Progress';

				if (item.Type__c=='GetCustomer')
					initAPIMap.put('CreateCustomer','CallAPI');
				if (item.Type__c=='CreateCustomer')
					initAPIMap.put('CreateCustomer','CallAPI');
				if (item.Type__c=='GetInvoice')
					initAPIMap.put('GetInvoice','CallAPI');
				if (item.Type__c=='UpdateCM')
					initAPIMap.put('UpdateCM','CallAPI');
				if (item.Type__c=='CreateMasterNoti')
					initAPIMap.put('CreateCustomer','CallAPI');
				if (item.Type__c=='CreateWork')
					initAPIMap.put('CreateCustomer','CallAPI');
			   	if (item.Type__c=='GetCMArtefact')
					initAPIMap.put('GetCMArtefact','CallAPI');
				if (item.Type__c=='GetCM')
					initAPIMap.put('GetCM','CallAPI');
				if (item.Type__c=='GetConstWO')
					initAPIMap.put('GetConstWO','CallAPI');
				if (item.Type__c=='GetConstNoti')
					initAPIMap.put('GetConstNoti','CallAPI');
				if (item.Type__c=='RequestInvoice')
					initAPIMap.put('RequestInvoice','CallAPI');
				if (item.Type__c!='CreateArtefact')
					newIntTaskList.add(item);
				if (item.Type__c=='CreateArtefact')
				{
					artIDlist.put(item,item.ParentId__c);
					ArtefactIdList.add(item.ParentId__c);
				}
			}

			if (artIDlist.size() > 0)
			{
				artefactMap=TVE_IntegUtility.getArtefact(ArtefactIdList);

				if (artefactMap.size() > 0)
				{
					List<Integration_Task__c> createArtefactList = new List<Integration_Task__c>();

					for (Integration_Task__c intTask:artIDlist.keySet()){
						if (artefactMap.containskey(artIDlist.get(intTask)))
							createArtefactList.add(intTask);
					}

					if (!createArtefactList.isEmpty()) {
						initAPIMap.put('CreateArtefact','CallAPI');
						newIntTaskList.addAll(createArtefactList);
					}
				}
			}

			if (!newIntTaskList.isEmpty())
			{
				for (Integration_Task__c item: newIntTaskList)
				{
					item.Status__c = 'In Progress';
				}
				update newIntTaskList;
			}

			if (initAPIMap.size()>0)
			{
				for (String key: initAPIMap.keySet())
				{
					if (key=='CreateCustomer')
					{
						TVE_SAPInteg_CreateCustomer createcustom = new TVE_SAPInteg_CreateCustomer();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(createcustom);
					}
					if (key=='GetInvoice')
					{
						TVE_SAP_Int_GetInvoice getInvoice = new TVE_SAP_Int_GetInvoice();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(getInvoice);
					}
					if (key=='UpdateCM')
					{
						TVE_SAPInteg_UpdateCMQue updateCM = new TVE_SAPInteg_UpdateCMQue();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(updateCM);
					}

					if (key=='GetCMArtefact')
					{
						TVE_SAP_Int_GetCMArtefact getCMArt = new TVE_SAP_Int_GetCMArtefact();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(getCMArt);
					}
					if (key=='GetCM')
					{
						TVE_SAPInteg_GetCMToSAP getCM = new TVE_SAPInteg_GetCMToSAP();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(getCM);
					}
					if (key=='GetConstWO')
					{
						TVE_SAPInteg_GetWorkOrderToSAP GetWO= new TVE_SAPInteg_GetWorkOrderToSAP();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(GetWO);
					}
					if (key=='GetConstNoti')
					{
						TVE_SAPInteg_GetNotificationToSAP GetPMNoti = new TVE_SAPInteg_GetNotificationToSAP();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(GetPMNoti);
					}
					if (key=='RequestInvoice')
					{
						TVE_SAPInteg_RequestInvoice reqInvoice = new TVE_SAPInteg_RequestInvoice();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(reqInvoice);
					}
					 if (key=='CreateArtefact')
					{
						TVE_SAPInt_CreateArtefact createArt = new TVE_SAPInt_CreateArtefact();
						if (!Test.isRunningTest())
							Id jobID = System.enqueueJob(createArt);
					}
				}
			}
		}
	}
}