force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/Upload_File.recordType-meta.xml
<RecordType>
    <fullName>Upload_File</fullName>
    <active>true</active>
    <label>Upload File</label>
</RecordType>

force-app/main/default/classes/TVEProjectActionControllerTest.cls
/*
@author  : pavan.dave@ausnetservices.com.au
@created : 23th Dec 2019
@Description : test class for Aura TVE_InvoicePreviewController
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public class TVEProjectActionControllerTest {
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static final string testUserEmail = 'testuser@TVEInvoicePreviewControllerTest.com';
    public static final string taskRT = 'Upload_File';
    public static testMethod void testGetTask(){
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        Test.startTest();
        System.runAs(testUser){
            Project__c projObj = [select id from Project__c limit 1];
            Task tsk =[select id from Task limit 1];
            TVEProjectActionController.TaskWrapper tskWrp=TVEProjectActionController.fetchTask(projObj.id, true);
            TVEProjectActionController.ProjectWrapper projID=TVEProjectActionController.fetchProject(tsk.id);
             }
    }
    @TestSetup
    public static void setup() {
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
        
        //Create Business Account
        Account testInstaller = TVE_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;
        
        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        Insert projObj;
        
        Artefact__c artObj = TVE_TestUtility.createInvoiceArtefact('NameTest',projObj.Id,testInstaller.Id);
        insert artObj;
        
        Task tsk = TVE_TestUtility.createTask(projObj.id,testUser.id,'Upload File');
        insert tsk;
        
    }  
}