force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Record type for contract</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Offer.recordType-meta.xml
<RecordType>
    <fullName>Offer</fullName>
    <active>true</active>
    <description>Record type for offer</description>
    <label>Offer</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Record type for other</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TVE_ArtefactController.cls
/*
@author  : brajesh.tiwary@ausnetservices.com.au
@created : 12th Dec 2019
@Description : Controller class for Aura TVE_FilePreview
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
public with sharing class TVE_ArtefactController {
    public static String Artefact_OFFER_RT = 'Offer';
    //public static String Artefact_Design_RT_Id = 'Design';
    public static String Artefact_Other_RT_Id = 'Other';
    public static String Artefact_Contract_RT_Id = 'Contract';
    
    @AuraEnabled(cacheable=true)
    public static list<wrapContentVersionDoc> getArtefactList(string recordId) {
        Id Artefact_Offer_RT_Id = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get(Artefact_OFFER_RT).getRecordTypeId();
       // Id Artefact_Design_RT_Id = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get(Artefact_Design_RT_Id).getRecordTypeId();
        Id Artefact_Other_RT_Id = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get(Artefact_Other_RT_Id).getRecordTypeId();
        Id Artefact_Contract_RT_Id = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get(Artefact_Contract_RT_Id).getRecordTypeId();
       

        wrapContentVersionDoc offerWrpItem = new wrapContentVersionDoc();
        list<wrapContentVersionDoc> listWrapper = new list<wrapContentVersionDoc>();
        set<id> conDocId = new set<id>();
        Set<id> artfctIds = new Set<id>();
        set<id> validRecordTypeIds = new set<id>{Artefact_Offer_RT_Id,Artefact_Other_RT_Id,Artefact_Contract_RT_Id };
        
        List<Artefact__c> lstArtfct =  new List<Artefact__c>([SELECT Id, Name , Classification__c,CreatedBy.Name,
                                                              Project__r.Name
                                                              FROM Artefact__c 
                                                              WHERE Project__c = :recordId
                                                              AND RecordTypeId IN :validRecordTypeIds
                                                             ]);
        if(!lstArtfct.isEmpty()) 
        {  
            for(Artefact__c item: lstArtfct){
                artfctIds.add(item.Id);
            }
            List<ContentDocumentLink> lstConDocLink = [SELECT ContentDocumentId, LinkedEntityId 
                                                       FROM ContentDocumentLink 
                                                       WHERE LinkedEntityId IN :artfctIds];
            for(Artefact__c artfcItem: lstArtfct)                 
            {
                for(ContentDocumentLink conDocLinkItem : lstConDocLink) 
                {
                    conDocId.add(conDocLinkItem.ContentDocumentId);
                    if(artfcItem.Id == conDocLinkItem.LinkedEntityId)
                    {
                        offerWrpItem = new wrapContentVersionDoc();
                        offerWrpItem.Classification = artfcItem.Classification__c;
                        offerWrpItem.Createdby= artfcItem.CreatedBy.Name;
                        offerWrpItem.contentDocObj = conDocLinkItem.ContentDocumentId;
                        listWrapper.add(offerWrpItem);
                    }                    
                }  
            }
        }
        map<id,ContentVersion> mapOfDoc = new map<id,ContentVersion>();
        for(ContentVersion cv: [SELECT VersionData ,Title,ContentDocumentId,CreatedDate
                                FROM ContentVersion 
                                WHERE ContentDocumentId IN:conDocId 
                                AND IsLatest = true
                               ]){
                                   mapOfDoc.put(cv.ContentDocumentId,cv);
                               }
        for(wrapContentVersionDoc wrap : listWrapper){
            if(mapOfDoc.containsKey(wrap.contentDocObj)){
                String splitedTitle = mapOfDoc.get(wrap.contentDocObj).Title;
                if (splitedTitle.contains('.')) { 
                wrap.Title = splitedTitle.split('\\.')[0];
                }
                else {
                    wrap.Title = mapOfDoc.get(wrap.contentDocObj).Title;
                }
                DateTime myDateTime;
                myDateTime = mapOfDoc.get(wrap.contentDocObj).CreatedDate;
                Date myDate = date.newinstance(myDateTime.year(), myDateTime.month(), myDateTime.day());
                wrap.CreatedDate = myDate;
            }
        }
     System.debug('listWrapper'+listWrapper);
        return listWrapper;
    }
    
    public class wrapContentVersionDoc{
        @AuraEnabled public string Name{get; set;}
        @AuraEnabled public string contentDocObj {get; set;}
        @auraEnabled public string Classification {get; set;}
        @auraEnabled public string projectName {get; set;}
        @auraEnabled public string Title {get; set;}
        @auraEnabled public Date CreatedDate {get; set;}
        @auraEnabled public String Createdby {get; set;}
    }
}