force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConstructionMeasureSets__x/ConstructionMeasureSets__x.object-meta.xml
<CustomObject>
    <description>ConstructionMeasureSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>ConstructionMeasureSets</externalName>
    <label>ConstructionMeasureSets</label>
    <pluralLabel>ConstructionMeasureSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/CMnumber__c.field-meta.xml
<CustomField>
    <fullName>CMnumber__c</fullName>
    <label>CM number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_File_ext_Mapping__c/TVE_File_ext_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TVE File ext Mapping</label>
</CustomObject>

force-app/main/default/classes/TVE_SAPInt_CreateArtefactTest.cls
@isTest
public class TVE_SAPInt_CreateArtefactTest  {
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
    public static final string testUserEmail = 'testuser@TVEInvoicePreviewControllerTest.com';
    private class RestMock implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{\"status\":\"201\",\"statusMessage\":\"Created\",\"payload\":{\"d\":{\"NotificationNumber\":\"100108471\"}}}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    @TestSetup
    public static void setup() {
        
        //Create Business Account
        Account testInstaller = TVE_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;
        Account personAccount = TVE_TestUtility.createPersonAccount('Person Account','Test@gmail.com');
        insert personAccount;
               
        List<Project__c> projObj = TVE_TestUtility.createMultipleIntegrationProject('test',PROGRESS_BAR_STATUS,CON_TYPE,testInstaller.id);
        Insert projObj;
        projObj[5].CMNumber__c='0076555';
        update projObj[5];
        List<Opportunity> opp = TVE_TestUtility.createMultipleOpportunity(projObj,testInstaller.id);
        insert opp;
        List<Integration_Task__c> intTask =TVE_TestUtility.createMultipleIntegrationTask
            (projObj,'Create','Project__c','In Progress','CreateMasterNoti');
        insert intTask;
        List<Project__c> projObjP = TVE_TestUtility.createMultipleIntegrationProject('test',PROGRESS_BAR_STATUS,CON_TYPE,personAccount.id);
        Insert projObjP;
        List<Opportunity> oppP = TVE_TestUtility.createMultipleOpportunity(projObjP,personAccount.id);
        insert oppP;
        List<Integration_Task__c> intTaskP =TVE_TestUtility.createMultipleIntegrationTask
            (projObjP,'Create','Project__c','In Progress','CreateMasterNoti');
        insert intTaskP;
        //ConstructionMeasureSets__x cmset = TVE_TestUtility.createConstMeasureSet();
		Artefact__c art = TVE_TestUtility.createArtefact('test artefact',projObj[5].id,testInstaller.id);
        insert art;
        System.debug('Aretefact in setup'+projObj[4].CMNumber__c);
        ContentVersion CV = TVE_TestUtility.createCV(art.id);
         insert CV;
        Id IntTaskRTId = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByDeveloperName().get('Artefact').getRecordTypeId();
        Integration_Task__c intTaskC =TVE_TestUtility.createIntegrationTask(art.id,'Create','Artefact__c','In Progress','CreateArtefact');
        intTaskC.RecordtypeID=IntTaskRTId;
        insert intTaskC;    
        TVE_File_ext_Mapping__c fileExt =new TVE_File_ext_Mapping__c();
        fileExt.name='pdf';
        fileExt.Type__c='application/pdf';
        insert fileExt;
      
        
    }  
    public static testMethod void callCreateWorkAPI(){
        
        TVE_CreateCMArtResponse CAW = new TVE_CreateCMArtResponse();
        CAW=(TVE_CreateCMArtResponse)JSON.deserialize('{\"status\":\"201\",\"statusMessage\":\"Created\",\"payload\":{\"d\":{\"NotificationNumber\":\"100108471\"}}}',TVE_CreateCMArtResponse.class);
        CAW.status='200';
        CAW.statusMessage='Created';
        CAW.payload.d.ArcDocId='005056AE1CCF1EEA97F4075DABCB16EE';
        CAW.payload.d.SapObject ='object';  
        CAW.payload.d.ObjectId ='1234';   
        CAW.payload.d.ArObject ='testobj';   
        CAW.payload.d.Filename ='testFile';    
        CAW.payload.d.FileContent ='Content';
        CAW.payload.d.FileDesc ='desc';   
        CAW.payload.d.MimeType ='EEEE';   
        CAW.payload.d.OriginalUrl ='URL';
        CAW.payload.d.Url='url';         
        CAW.payload.d.ThumbnailUrl='thumbnail';
        CAW.payload.d.FileSize ='20000';   
        CAW.payload.d.CreatedDate ='2020-02-12';
        CAW.payload.d.Creator ='test';    
        CAW.payload.d.ImageResize='1234'; 
        TVE_CreateCMArtResponse.parse('{\"status\":\"201\",\"statusMessage\":\"Created\",\"payload\":{\"d\":{\"NotificationNumber\":\"100108471\"}}}');
        TVE_SAP_Int_APICalls.CAW=CAW;
        TVE_SAPInt_CreateArtefact createNoti = new TVE_SAPInt_CreateArtefact();
        // enqueue the job for processing
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        ID jobID = System.enqueueJob(createNoti);  
        Test.stopTest();
        System.debug('TVE_SAPInteg_CreateWork - Job Id : ' + jobID);
        
    }
    
      
}