force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/SAPNumber__c.field-meta.xml
<CustomField>
    <fullName>SAPNumber__c</fullName>
    <externalId>true</externalId>
    <label>SAP Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AttachmentSets__x/AttachmentSets__x.object-meta.xml
<CustomObject>
    <description>AttachmentSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>AttachmentSets</externalName>
    <label>AttachmentSets</label>
    <pluralLabel>AttachmentSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/TVE_File_Classification_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>TVE File Classification Mapping</label>
    <pluralLabel>TVE File Classification Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
                <default>true</default>
                <label>Prelim Estimate</label>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>DocumentType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_SAP_Int_GetCMArtefact.cls
/*
  @author  : lakshay.sharma@ausnetservices.com.au
  @created : 2 March 2020
  @Description : Class for executing SAP Integration - Get CM Artefact to SAP
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/

public without sharing class TVE_SAP_Int_GetCMArtefact implements Queueable,Database.AllowsCallouts {
    public void execute(QueueableContext qc)
    {
        Map<String,String> arteInteMap = new Map<String,String>();

        Map<id,String> successMap = new Map<Id,String>();
        Map<id,String> failureMap = new Map<Id,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();
        Map<String,String> UpdateIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMapFail = new Map<String,String>();

        List<Integration_Task__c> lstIntgTask = TVE_IntegUtility.getIntegrationTask('Get','Artefact__c','GetCMArtefact','In Progress');
        if(!lstIntgTask.isEmpty()){
            
            for(Integration_Task__c intTask : lstIntgTask)
            {
                Boolean checkId = (intTask.ParentId__c InstanceOf Id);
                if(checkId)
                {
                    arteInteMap.put(intTask.ParentId__c, intTask.Id);
                }
                else    
                {
                    failureMap.put(intTask.Id, 'Invalid ParentId' + intTask.ParentId__c);
                }
            }

            if(!arteInteMap.isEmpty())
            {
                Map<Id, Artefact__c> arteMap = new Map<Id, Artefact__c>([SELECT Id,SAPNumber__c,Project__r.CMNumber__c,Classification__c FROM Artefact__c WHERE Id IN :arteInteMap.keySet()]);
                

                for(Id art : arteInteMap.keySet()){
                    if(!arteMap.keySet().contains(art)){
                        failureMap.put(arteInteMap.get(art), 'ParentId not found');
                    }
                }
                
                if(!arteMap.isEmpty()) {
                    Map<String,String> CMMap = new Map<String,String>();
                    for(TVE_File_Classification_Mapping__mdt key : [SELECT DocumentType__c ,Classification__c FROM TVE_File_Classification_Mapping__mdt]){
                        CMMap.put(key.Classification__c, key.documenttype__c);
                    }
                    
                    for(Artefact__c artefact : arteMap.values()){
                        try {
                            AttachmentSets__x attachsets = TVE_IntegUtility.getArtefact(artefact.SAPNumber__c,artefact.Project__r.CMNumber__c,CMMap.get(artefact.Classification__c));
                        } catch (Exception e) {
                            failureMap.put(arteInteMap.get(artefact.Id), e.getMessage());
                        }
                    }
                }
            }

            for(Integration_Task__c intTask : lstIntgTask) {
                if(!failureMap.containsKey(intTask.Id)) {
                    successMap.put(intTask.Id, intTask.ParentId__c);
                }
            }
        
            if(!successMap.isEmpty()) {
                updateIntTaskMap.put('Status__c','Successful');
                createIntglogmapS.put('Status__c','Successful');
            
                TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
                TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
            }
        
            if(!failureMap.isEmpty()) {
                updateIntTaskMapFail.put('Status__c','Failed');
                createIntglogmapF.put('Status__c','Failed');
                
                TVE_IntegUtility.UpdateInteTask(failureMap,updateIntTaskMapFail);
                TVE_IntegUtility.createIntegLog(failureMap,createIntglogmapF);
            }

            lstIntgTask = TVE_IntegUtility.getIntegrationTask('Get','Artefact__c','GetCMArtefact','In Progress');
            if(!lstIntgTask.isEmpty()){
                TVE_SAP_Int_GetCMArtefact getCMart = new TVE_SAP_Int_GetCMArtefact();
                ID jobID = System.enqueueJob(getCMart);
            }
        }
    }
}