force-app/main/default/objects/Case/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic Micro EG MSO</fullName>
            </value>
            <value>
                <fullName>Negotiated 0-5MW</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA&amp;NMA</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA</fullName>
            </value>
            <value>
                <fullName>Flexible &lt;30kW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Offer_URL__c.field-meta.xml
<CustomField>
    <fullName>DER_Offer_URL__c</fullName>
    <label>DER Offer URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Send_DER_Offer__c.field-meta.xml
<CustomField>
    <fullName>Send_DER_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To send offer.</description>
    <label>Send DER Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/DER_Agreement__c.object-meta.xml
<CustomObject>
    <label>DER Agreement</label>
    <nameField>
        <displayFormat>Agmt-{0000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Contract Active</fullName>
            </value>
            <value>
                <fullName>Contract Completed</fullName>
            </value>
            <value>
                <fullName>Contract Unauthorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DER_updateSendOffer.cls
public class DER_updateSendOffer {
    public static Id manualRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('DER Application - Manual').getRecordTypeId();
    public static string DER_AGREEMENT_STATUS = 'Offer Expired';
    @AuraEnabled
    public static string updateOfferOnManualPage(string recId){
        Boolean isError = false;
        set<id> appId = new set<id>();
        string errorOccured ='';
        List<Case> csList = [Select id, recordTypeId, DER_Application__c, isClosed, 
                                Agreement_Type__c, DER_Offer_URL__c, Send_DER_Offer__c
                                from Case 
                                where id=:recId
                                and DER_Application__c <> null];
        
        if(csList.isEmpty()){
            errorOccured = errorOccured +'DER Application not found <br/>';
        }else{
            Case cs = csList[0];       

            DER_Application__c dr = [select id, (Select id from DER_Agreements__r where Status__c !=:DER_AGREEMENT_STATUS) 
                                                from DER_Application__c 
                                                where id =: cs.DER_Application__c];

            if(cs.recordTypeId != manualRecordTypeId){
                    errorOccured = errorOccured +'Error: Generate Offer URL is only applicable for Manual cases.<br/>';
            }            
            if(cs.IsClosed ){
                errorOccured = errorOccured +'Error: DER Offer URL cannot be generated as this Case is Closed (Completed or Cancelled). <br/>';            
            }
            if(cs.DER_Offer_URL__c != null && dr != null && dr.DER_Agreements__r.size()==1){
                errorOccured = errorOccured +'Error: DER Offer URL has already been generated. See DER Offer URL field on the Case. <br/>';
            }   
            if(cs.Send_DER_Offer__c == true)
            {
                errorOccured = errorOccured +'Error: DER Offer URL cannot be generated as the offer has already been sent. <br/>';
            }
            if(dr != null && dr.DER_Agreements__r.size()>1){
                errorOccured = errorOccured +'Error: DER Offer URL cannot be generated as there are multiple DER Agreement records. <br/>';
            }            
         
            if(String.isBlank(errorOccured)){
                cs.Send_DER_Offer__c = true;
                update cs;
            }
        }
        
        return errorOccured;
    }
}