force-app/main/default/objects/Case/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic Micro EG MSO</fullName>
            </value>
            <value>
                <fullName>Negotiated 0-5MW</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA&amp;NMA</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA</fullName>
            </value>
            <value>
                <fullName>Flexible &lt;30kW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Cap__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Cap__c</fullName>
    <description>DER Register Level 2 – AC Connection
The rated AC output power that is listed in the product specified by the manufacturer.</description>
    <label>AC Equipment Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <description>Identifies the generation type for the equipment</description>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AEMO_Id__c.field-meta.xml
<CustomField>
    <fullName>AEMO_Id__c</fullName>
    <description>DER Register Level 2 – AC Connection</description>
    <label>AEMO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track Device history</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Decommission__c.field-meta.xml
<CustomField>
    <fullName>Decommission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Decommission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Phase__c.field-meta.xml
<CustomField>
    <fullName>Device_Phase__c</fullName>
    <description>Selection of the phase this device is on
If 3 Phase is selected, the Phase sits across Phase A, B, and C</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>3 Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Existing_Device__c.field-meta.xml
<CustomField>
    <fullName>Existing_Device__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing Device</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track Device history</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/NMI_AEMO_Id__c.field-meta.xml
<CustomField>
    <fullName>NMI_AEMO_Id__c</fullName>
    <label>NMI / AEMO Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Parent_Device__c.field-meta.xml
<CustomField>
    <fullName>Parent_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Requested__c.field-meta.xml
<CustomField>
    <fullName>Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track Device history</description>
    <inlineHelpText>This field denotes if this device was Requested on the original online application</inlineHelpText>
    <label>Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/SID__c.field-meta.xml
<CustomField>
    <fullName>SID__c</fullName>
    <label>Sitecore ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/recordTypes/Device_L2.recordType-meta.xml
<RecordType>
    <fullName>Device_L2</fullName>
    <active>true</active>
    <label>AC Equipment - L2</label>
</RecordType>

force-app/main/default/objects/Device__c/recordTypes/Device_L3.recordType-meta.xml
<RecordType>
    <fullName>Device_L3</fullName>
    <active>true</active>
    <label>DER Device - L3</label>
</RecordType>

force-app/main/default/objects/TrigSettings__c/fields/Device_Trigger_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Device_Trigger_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Device Trigger Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Trig_Device.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 20 Sep 2019
  @Description : Class for Device Trigger
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -------------------------------------------------------------------------------------------------------
  24/10/19          Palash Awasthi                Added method getDerAppForDefaults() on  After insert
  01/11/2019        Rohit Middha                      CMC-1499
  -------------------------------------------------------------------------------------------------------
*/
public with sharing class Trig_Device implements UtilTrigHandle{
	// *********************************************************************
	// *** Disable logic

	public static Boolean TrigDisabled = false;

	public Boolean IsDisabled()
	{
		if (TrigSettings__c.getInstance().Device_Trigger_Disabled__c)
			return true;
		else
			return TrigDisabled;
	}

	// *********************************************************************
	// *** Trigger contexts

	public void AfterInsert(Map<Id, SObject> newSObjs)
	{
		ValidateDevices_TotalCalc(newSObjs, null);
		//getDerAppForDefaults(newSObjs);
		ValidateDevices_GenerationTypesAndPhases(newSObjs, null);
		setKeyFields(newSObjs.values());
	}

	public void AfterUpdate(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		ValidateDevices_TotalCalc(newSObjs, oldSObjs);
		ValidateDevices_GenerationTypesAndPhases(newSObjs, oldSObjs);
		setL3DevicesStatusAsApproved(newSObjs, oldSObjs);
		setL3DevicesStatusAsDecomisssioned(newSObjs, oldSObjs);
	}

	public void AfterDelete(Map<Id, SObject> oldSObjs)
	{
		ValidateDevices_TotalCalc(null, oldSObjs);
		ValidateDevices_GenerationTypesAndPhases(null, oldSObjs);
	}

	public void AfterUndelete(Map<Id, SObject> newSObjs)
	{
		ValidateDevices_TotalCalc(newSObjs, null);
		ValidateDevices_GenerationTypesAndPhases(newSObjs, null);
	}

	public void BeforeInsert(List<SObject> newSObjs)
	{
		getDerDeviceForDefaults(newSObjs);
	}

	public void BeforeUpdate(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		setKeyFields(newSObjs.values());
		getDerDeviceForDefaults(newSObjs,oldSObjs);
	}


	// if context is not implemented, condense into one-liners
	public void BeforeDelete(Map<Id, SObject> oldSObjs) {}

	// *********************************************************************
	// *** Trigger methods

	private static Boolean isRunningSetKeyFields = false;
	private static void setKeyFields(List<SObject> newSObjs)
	{
		if (isRunningSetKeyFields) return;
		isRunningSetKeyFields = true;

		// Get NMIs for our devices
		Map<Id, String> DeviceNMIs = new Map<Id, String>();

		for (SObject sObjItem: newSObjs)
			DeviceNMIs.put(sObjItem.Id, null);

		for (Device__c newDevice: [SELECT Id, Name, RecordTypeId, DER_Application__c, Parent_Device__c,
								DER_Application__r.NMI__r.NMI__c,
								Parent_Device__r.DER_Application__r.NMI__r.NMI__c
								FROM Device__c
								WHERE Id IN :DeviceNMIs.keySet()])
		{
			String RTName = UtilDatabase.getRecordTypes().get(newDevice.RecordTypeId);

			if (RTName == 'Device_L2' && newDevice.DER_Application__r.NMI__r.NMI__c != null)
			{
				DeviceNMIs.put(newDevice.Id, newDevice.DER_Application__r.NMI__r.NMI__c);
			}
			else if (RTName == 'Device_L3' && newDevice.Parent_Device__r.DER_Application__r.NMI__r.NMI__c != null)
			{
				DeviceNMIs.put(newDevice.Id, newDevice.Parent_Device__r.DER_Application__r.NMI__r.NMI__c);
			}
		}

		// Process records
		Map<Id, SObject> updSObjs = new Map<Id, SObject>();

		// This trigger runs in Before Update and After Insert.
		//		Before Update context can update the triggered SObj directly.
		//		After Insert context cannot, and must issue an update to a separate SObj instance.
		for (SObject sObjItem: newSObjs)
		{
			Device__c device = (Device__c)sObjItem;
			String RTName = UtilDatabase.getRecordTypes().get(device.RecordTypeId);

			Device__c updDevice;

			// This code provides a single point of updating the record (updDevice)
			if (Trigger.operationType == System.TriggerOperation.BEFORE_UPDATE)
				updDevice = device;
			else if (Trigger.operationType == System.TriggerOperation.AFTER_INSERT)
			{
				if (!updSObjs.containsKey(device.Id))
					updSObjs.put(device.Id, new Device__c(Id = device.Id));

				updDevice = (Device__c)updSObjs.get(device.Id);
			}

			if (updDevice == null)
				continue;


			// Now we set the fields as desired.
			//	Note we run comparison/read fields on device instance, but only set fields on updDevice instance.
			if (device.Id != null && device.SID__c == null)
			{
				// Set Sitecore Id to SF Id
				updDevice.SID__c = device.Id;
			}

			if (device.AEMO_Id__c != null && device.NMI_AEMO_Id__c == null)
			{
				// Get NMI
				if (!DeviceNMIs.containsKey(device.Id) || DeviceNMIs.get(device.Id) == null)
					continue;
				
				String NMI = DeviceNMIs.get(device.Id);

				// Set the NMI_AEMO_Id
				updDevice.NMI_AEMO_Id__c = NMI + '-' + RTName.removeStart('Device_') + '-' + device.AEMO_Id__c;
			}
		}

		if (!updSObjs.isEmpty()) update updSObjs.values();
	}


	// Calculate totals and update the DER Applicaiton
	private void  ValidateDevices_TotalCalc(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		System.debug('*** Trig_Device.ValidateDevices_TotalCalc()');
		if (UtilFieldCalcs.isRunning_CalcDERAppPhaseTotals) return;

		Set<Id> validDERAppIds = new Set<Id>();
		Set<Id> allowedRTIds   = new Set<Id>();

		// Get the Record Type Ids.
		for (String RTName: UtilFieldCalcs.CalcTotalFields_AllowedRTs)
			allowedRTIds.add(UtilDatabase.getRecordTypeNames('Device__c').get(RTName));

		switch on Trigger.operationType
		{
			when AFTER_INSERT
			{
				for (SObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;

					if (!allowedRTIds.contains(newDeviceItem.RecordTypeId))
						continue;

					if (newDeviceItem.DER_Application__c != null && !newDeviceItem.Decommission__c)
						validDERAppIds.add(newDeviceItem.DER_Application__c);
				}
			}
			when AFTER_UPDATE
			{
				for (sObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					Device__c oldDeviceItem = (Device__c)oldSObjs.get(newDeviceItem.Id);

					if (!allowedRTIds.contains(newDeviceItem.RecordTypeId))
						continue;

					if (newDeviceItem.DER_Application__c != null &&
					   (newDeviceItem.DER_Application__c != oldDeviceItem.DER_Application__c ||
						newDeviceItem.RecordTypeId       != oldDeviceItem.RecordTypeId       ||
						newDeviceItem.Device_Phase__c    != oldDeviceItem.Device_Phase__c    ||
						newDeviceItem.AC_Equip_Cap__c    != oldDeviceItem.AC_Equip_Cap__c    ||
						newDeviceItem.Requested__c       != oldDeviceItem.Requested__c       ||
						newDeviceItem.Approved__c        != oldDeviceItem.Approved__c        ||
						newDeviceItem.Installed__c       != oldDeviceItem.Installed__c       ||
						newDeviceItem.Decommission__c    != oldDeviceItem.Decommission__c))
					{
						if (newDeviceItem.DER_Application__c != null)
							validDERAppIds.add(newDeviceItem.DER_Application__c);

						if (oldDeviceItem.DER_Application__c != null)
							validDERAppIds.add(oldDeviceItem.DER_Application__c);
					}
				}
			}
			when AFTER_DELETE
			{
				for (SObject sObjItem: oldSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;

					if (!allowedRTIds.contains(newDeviceItem.RecordTypeId))
						continue;

					if (newDeviceItem.DER_Application__c != null && !newDeviceItem.Decommission__c)
						validDERAppIds.add(newDeviceItem.DER_Application__c);
				}
			}
			when AFTER_UNDELETE
			{
				for (SObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;

					if (!allowedRTIds.contains(newDeviceItem.RecordTypeId))
						continue;

					if (newDeviceItem.DER_Application__c != null && !newDeviceItem.Decommission__c)
						validDERAppIds.add(newDeviceItem.DER_Application__c);
				}
			}
		}

		//-----------------------------------------------------------//
		//--------- Calculate DER Application Phase Total -----------//
		//-----------------------------------------------------------//

		if (!validDERAppIds.isEmpty())
			UtilFieldCalcs.CalcDERAppPhaseTotals(validDERAppIds);
	}

	private static void getDerDeviceForDefaults(List<SObject> newSObjs)
	{
		System.debug('******************Before device insert trigger logic*********************');
		Map<Device__c,String> deviceOfferTypeMap = new Map<Device__c,String>();
		Set<Id> derAppIdset = new Set<Id>();
		Map<Id,String> derIdCaseAggrementMap = new Map<Id,String>();
		for (SObject sObjItem: newSObjs)
		{
			Device__c newDevice = (Device__c)sObjItem;
			if (newDevice.DER_Application__c != null)
			{
				derAppIdset.add(newDevice.DER_Application__c);
			}
		}
		System.debug('############# DerAppIdset is ########'+derAppIdset);
		for (Case c : [Select Id,Agreement_Type__c,DER_Application__c from Case where DER_Application__c in : derAppIdset])
		{
			derIdCaseAggrementMap.put(c.DER_Application__c,c.Agreement_Type__c);
		}

		for (SObject sObjItem: newSObjs)
		{
			Device__c newDevice = (Device__c)sObjItem;
			String RTName = UtilDatabase.getRecordTypes().get(newDevice.RecordTypeId);
			if (newDevice.AC_Equip_Type__c != null && RTName == 'Device_L2' && newDevice.DER_Application__c != null
			 && derIdCaseAggrementMap.get(newDevice.DER_Application__c) != null )
			{
				 deviceOfferTypeMap.put(newDevice,derIdCaseAggrementMap.get(newDevice.DER_Application__c));
			}
		}

		if (deviceOfferTypeMap != null && !deviceOfferTypeMap.isEmpty())
		{
			DER_Defaults.applyDefault(deviceOfferTypeMap);
		}
	}

	private void  ValidateDevices_GenerationTypesAndPhases(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		System.debug('*** Trig_Device.ValidateDevices_GenerationTypesAndPhases()');
		Set<Id> validDERAppIds = new Set<Id>();
		switch on Trigger.operationType {
			when AFTER_INSERT {
				for (SObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					if (newDeviceItem.DER_Application__c != null && newDeviceItem.Decommission__c == false)
					{
						validDERAppIds.add(newDeviceItem.DER_Application__c);
					}

				}
			}
			when AFTER_UPDATE {
				for (sObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					if (newDeviceItem.DER_Application__c != null
					   && (
						   newDeviceItem.AC_Equip_Sub_Type__c != ((Device__c)oldSObjs.get(newDeviceItem.Id)).AC_Equip_Sub_Type__c
						   || newDeviceItem.Device_Phase__c != ((Device__c)oldSObjs.get(newDeviceItem.Id)).Device_Phase__c
						   || newDeviceItem.RecordTypeId != ((Device__c)oldSObjs.get(newDeviceItem.Id)).RecordTypeId
						   || newDeviceItem.DER_Application__c != ((Device__c)oldSObjs.get(newDeviceItem.Id)).DER_Application__c
						   || newDeviceItem.Decommission__c != ((Device__c)oldSObjs.get(newDeviceItem.Id)).Decommission__c
					   )
					  )
					{
						if (newDeviceItem.DER_Application__c != null)
							validDERAppIds.add(newDeviceItem.DER_Application__c);
						if (((Device__c)oldSObjs.get(newDeviceItem.Id)).DER_Application__c != null)
							validDERAppIds.add(((Device__c)oldSObjs.get(newDeviceItem.Id)).DER_Application__c);
					}
				}
			}
			when AFTER_DELETE {
				for (SObject sObjItem: oldSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					if (newDeviceItem.DER_Application__c != null && newDeviceItem.Decommission__c == false)
					{
						validDERAppIds.add(newDeviceItem.DER_Application__c);
					}
				}
			}
			when AFTER_UNDELETE {
				for (SObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					if (newDeviceItem.DER_Application__c != null && newDeviceItem.Decommission__c == false)
					{
						validDERAppIds.add(newDeviceItem.DER_Application__c);
					}
				}
			}
		}

		//-----------------------------------------------------------//
		//--------- Populate DER Application Phases and Generation Types -----------//
		//-----------------------------------------------------------//

		if (!validDERAppIds.isEmpty()){
		   UtilFieldCalcs.CalsGenerationTypesAndPhasesTotals(validDERAppIds);
		}
	}

	private static void getDerDeviceForDefaults(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		System.debug('******************Before device update trigger logic*********************');
		Map<Device__c,String> deviceOfferTypeMap = new Map<Device__c,String>();
		Set<Id> derAppIdset = new Set<Id>();
		Map<Id,String> derIdCaseAggrementMap = new Map<Id,String>();
		 for (SObject sObjItem: newSObjs.values())
		{
			Device__c newDevice = (Device__c)sObjItem;
			if (newDevice.DER_Application__c != null && newDevice.Existing_Device__c != true)
			{
				derAppIdset.add(newDevice.DER_Application__c);
			}

		}
		System.debug('############# DerAppIdset is ########'+derAppIdset);
		for (Case c : [Select Id,Agreement_Type__c,DER_Application__c from Case where DER_Application__c in : derAppIdset])
		{
			derIdCaseAggrementMap.put(c.DER_Application__c,c.Agreement_Type__c);
		}

		for (SObject sObjItem: newSObjs.values())
		{
			Device__c newDevice = (Device__c)sObjItem;
			String RTName = UtilDatabase.getRecordTypes().get(newDevice.RecordTypeId);
			if (newDevice.AC_Equip_Type__c != null && RTName == 'Device_L2' && newDevice.DER_Application__c != null
			 && derIdCaseAggrementMap.get(newDevice.DER_Application__c) != null &&
			   newDevice.AC_Equip_Type__c != ((Device__c)oldSObjs.get(newDevice.Id)).AC_Equip_Type__c &&
			   newDevice.Existing_Device__c != true)
			{
				 deviceOfferTypeMap.put(newDevice,derIdCaseAggrementMap.get(newDevice.DER_Application__c));
			}
		}

		if (deviceOfferTypeMap != null)
		{
			DER_Defaults.applyDefault(deviceOfferTypeMap);
		}

	}

	private static void setL3DevicesStatusAsApproved(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		Map<Id,Boolean> l2IdMap = new Map<Id,Boolean>();
		List<Device__c> l3IdSet = new List<Device__c>();
		switch on Trigger.operationType {
			when AFTER_UPDATE {
				for (sObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					Device__c oldDeviceItem = (Device__c)oldSObjs.get(newDeviceItem.Id);
					String RTName = UtilDatabase.getRecordTypes().get(newDeviceItem.RecordTypeId);

					if (newDeviceItem.Approved__c != oldDeviceItem.Approved__c &&  RTName == 'Device_L2' &&
						newDeviceItem.DER_Application__c != null)
					{
                      l2IdMap.put(newDeviceItem.Id,newDeviceItem.Approved__c);
					}
				}
                
			}

		}
		if(l2IdMap.size() > 0)
		{
          for(Device__c dev : [Select Id,Approved__c,Parent_Device__c from Device__c where 	Parent_Device__c in :l2IdMap.keySet()])
		  {
			  dev.Approved__c = l2IdMap.get(dev.Parent_Device__c);
              l3IdSet.add(dev);
		  }
		}
		if(!l3IdSet.isEmpty())
		{
          update l3IdSet;
		}
	}

	private static void setL3DevicesStatusAsDecomisssioned(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		Map<Id,Boolean> l2IdMap = new Map<Id,Boolean>();
		List<Device__c> l3IdSet = new List<Device__c>();
		switch on Trigger.operationType {
			when AFTER_UPDATE {
				for (sObject sObjItem: newSObjs.values())
				{
					Device__c newDeviceItem = (Device__c)sObjItem;
					Device__c oldDeviceItem = (Device__c)oldSObjs.get(newDeviceItem.Id);
					String RTName = UtilDatabase.getRecordTypes().get(newDeviceItem.RecordTypeId);

					if (newDeviceItem.Decommission__c != oldDeviceItem.Decommission__c &&  RTName == 'Device_L2')
					{
                      l2IdMap.put(newDeviceItem.Id,newDeviceItem.Decommission__c);
					}
				}
                
			}

		}
		if(l2IdMap.size() > 0)
		{
          for(Device__c dev : [Select Id,Decommission__c,Parent_Device__c from Device__c where 	Parent_Device__c in :l2IdMap.keySet()])
		  {
			  dev.Decommission__c = l2IdMap.get(dev.Parent_Device__c);
              l3IdSet.add(dev);
		  }
		}
		if(!l3IdSet.isEmpty())
		{
          update l3IdSet;
		}
	}


}