force-app/main/default/objects/Case/fields/Cancelled_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Reason__c</fullName>
    <label>Cancelled Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Not Received</fullName>
            </value>
            <value>
                <fullName>Applicant Declined</fullName>
            </value>
            <value>
                <fullName>AusNet Refused</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Unauthorised</fullName>
            </value>
            <value>
                <fullName>Flexible Exports Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Active_Date__c</fullName>
    <label>Contract Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <description>Criteria field for email notification</description>
    <label>Contract Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Offer_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Accepted_Date__c</fullName>
    <description>Email merge field</description>
    <label>Offer Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Offer_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Expiration_Date__c</fullName>
    <description>Email merge field</description>
    <label>Offer Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Offer_Made_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Made_Date__c</fullName>
    <label>Offer Made Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/DER_Agreement__c.object-meta.xml
<CustomObject>
    <label>DER Agreement</label>
    <nameField>
        <displayFormat>Agmt-{0000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/fields/Contract_Active_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Active_Date__c</fullName>
    <description>The date the offer is active i.e. when Post Installation forms are returned and validated</description>
    <label>Contract Active Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Offer_Accepted_By__c.field-meta.xml
<CustomField>
    <fullName>Offer_Accepted_By__c</fullName>
    <label>Offer Accepted By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Offer_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Expiration_Date__c</fullName>
    <description>Shows the Offer Expiry Date, based on the Date Offer Made, and the Offer Type</description>
    <formula>if(AND(Not(ISNULL(Offer_Made_Date__c)), OR( TEXT( Offer_Type__c ) = &apos;Negotiated 0-5MW&apos;,TEXT( Offer_Type__c ) = &apos;Negotiated &gt;5MW NEA&apos;,TEXT( Offer_Type__c ) = &apos;Negotiated &gt;5MW NEA&amp;NMA&apos;) ), CASE(
MOD(Offer_Made_Date__c - DATE(1900, 1, 7), 7),
0, (Offer_Made_Date__c) + 20 + FLOOR((20-1)/5)*2,
1, (Offer_Made_Date__c) + 20 + FLOOR((20)/5)*2,
2, (Offer_Made_Date__c) + 20 + FLOOR((20+1)/5)*2,
3, (Offer_Made_Date__c) + 20 + FLOOR((20+2)/5)*2,
4, (Offer_Made_Date__c) + 20 + FLOOR((20+3)/5)*2,
5, (Offer_Made_Date__c) + 20 + CEILING((20)/5)*2,
6, (Offer_Made_Date__c) - IF(20&gt;0,1,0) + 20 + CEILING((20)/5)*2,
null) , IF( AND(Not(ISNULL(Offer_Made_Date__c)),TEXT( Offer_Type__c ) = &apos;Basic Micro EG MSO&apos;) , CASE(
MOD(Offer_Made_Date__c - DATE(1900, 1, 7), 7),
0, (Offer_Made_Date__c) + 45 + FLOOR((45-1)/5)*2,
1, (Offer_Made_Date__c) + 45 + FLOOR((45)/5)*2,
2, (Offer_Made_Date__c) + 45 + FLOOR((45+1)/5)*2,
3, (Offer_Made_Date__c) + 45 + FLOOR((45+2)/5)*2,
4, (Offer_Made_Date__c) + 45 + FLOOR((45+3)/5)*2,
5, (Offer_Made_Date__c) + 45 + CEILING((45)/5)*2,
6, (Offer_Made_Date__c) - IF(45&gt;0,1,0) + 45 + CEILING((45)/5)*2,
null), null) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Offer Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Offer_Made_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Made_Date__c</fullName>
    <label>Offer Made Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Contract Active</fullName>
            </value>
            <value>
                <fullName>Contract Completed</fullName>
            </value>
            <value>
                <fullName>Contract Unauthorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Trig_DER_Agreement_Test.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 07 Oct 2019
  @Description : Test Class for Trig_DER_Agreement and DERAgreementTrigger
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                                 NA
  -----------------------------------------------------------------------------------------
*/
@isTest
private class Trig_DER_Agreement_Test
{
    private static String customerEmail = 'customer@test12345.com';
    private static String installerEmail = 'installer@test12345.com';
    private static String repEmail = 'rep@test12345.com';
	private static String DER_AGMT_STATUS_OFFER_MADE = 'Offer Made';
    private static String DER_AGMT_STATUS_OFFER_ACCPT = 'Offer Accepted';
    private static String DER_AGMT_STATUS_DECLINED = 'Offer Declined';
    private static String CASE_REASON_DECLINED = 'Applicant Declined';
    private static String CASE_STATUS_CANCELLED = 'Cancelled';
    private static String DER_AGMT_OFFERTYPE_BASIC_MICRO = 'Basic Micro EG MSO';
    private static String CASE_STATUS_INSTALLATION_PENDING = 'Installation Pending';
        
	@testSetup static void setup()
    {
		Id testDERAppId = DER_TestUtility.loadDERAppRecords(customerEmail, installerEmail, repEmail);
	}

	@isTest static void test_Agreement_INSERT()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  
		
		List<Case> lstCase = Database.query(queryCase);
		System.assertEquals(null, lstCase[0].Contract_Status__c);
        System.assertEquals(null, lstCase[0].Offer_Accepted_Date__c);
        System.assertEquals(null, lstCase[0].Offer_Expiration_Date__c);

        test.startTest();
	    
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5,
                                                                     System.today(), 
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
				
		test.stopTest();            
		
		lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                        FROM DER_Agreement__c 
                        WHERE Id =: testAgmnt.Id];

		System.assertEquals(DER_AGMT_STATUS_OFFER_MADE, lstCase[0].Contract_Status__c);
        System.assertEquals(System.today() + 5, lstCase[0].Offer_Accepted_Date__c);
        System.assertEquals(testAgmnt.Offer_Expiration_Date__c, lstCase[0].Offer_Expiration_Date__c);
	}
    
    @isTest static void test_Agreement_INSERT_OfferAccepted()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  
		
		List<Case> lstCase = Database.query(queryCase);
		System.assertEquals('New', lstCase[0].status);
        test.startTest();
	    
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_ACCPT, 
                                                                     System.today() + 5,
                                                                     System.today(), 
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
				
		test.stopTest();            
		
		lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                        FROM DER_Agreement__c 
                        WHERE Id =: testAgmnt.Id];

		System.assertEquals(CASE_STATUS_INSTALLATION_PENDING, lstCase[0].status);
        }
    
    @isTest static void test_Agreement_UPDATE_OFFER_ACCEPTED()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  

        List<Case> lstCase = Database.query(queryCase);
        
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5,
                                                                     System.today(), 
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
		
        test.startTest();
        
		DER_Agreement__c agmtUpd = [SELECT Id, Status__c, DER_Application__c, Offer_Accepted_Date__c, Offer_Made_Date__c
									FROM DER_Agreement__c 
									WHERE Id =: testAgmnt.Id LIMIT 1];
                
        agmtUpd.Status__c = DER_AGMT_STATUS_OFFER_ACCPT;
        update agmtUpd;
        
        agmtUpd.Contract_Active_Date__c = null;
        agmtUpd.Offer_Accepted_By__c = '';
        update agmtUpd;
        
		test.stopTest();            
		
        lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                                FROM DER_Agreement__c 
                                WHERE Id =: testAgmnt.Id];

		System.assertEquals(CASE_STATUS_INSTALLATION_PENDING, lstCase[0].status);
        }
	@isTest static void test_Agreement_INSERT_Offer_DECLINED()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  
		
		List<Case> lstCase = Database.query(queryCase);
		System.assertEquals('New', lstCase[0].status);
        System.assertEquals(null, lstCase[0].Cancelled_Reason__c);
        test.startTest();
	    
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_DECLINED, 
                                                                     System.today() + 5,
                                                                     System.today(), 
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
				
		test.stopTest();            
		
		lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                        FROM DER_Agreement__c 
                        WHERE Id =: testAgmnt.Id];

		System.assertEquals(CASE_STATUS_CANCELLED, lstCase[0].status);
        System.assertEquals(CASE_REASON_DECLINED, lstCase[0].Cancelled_Reason__c);
        }
    
    @isTest static void test_Agreement_UPDATE_OFFER_DECLINED()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  

        List<Case> lstCase = Database.query(queryCase);
        
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5,
                                                                     System.today(), 
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
		
        test.startTest();
        
		DER_Agreement__c agmtUpd = [SELECT Id, Status__c, DER_Application__c, Offer_Accepted_Date__c, Offer_Made_Date__c
									FROM DER_Agreement__c 
									WHERE Id =: testAgmnt.Id LIMIT 1];
                
        agmtUpd.Status__c = DER_AGMT_STATUS_DECLINED;
        update agmtUpd;
        
		test.stopTest();            
		
        lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                                FROM DER_Agreement__c 
                                WHERE Id =: testAgmnt.Id];

		System.assertEquals(CASE_STATUS_CANCELLED, lstCase[0].status);
        System.assertEquals(CASE_REASON_DECLINED, lstCase[0].Cancelled_Reason__c);
        }

    @isTest static void test_Agreement_UPDATE()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  

        List<Case> lstCase = Database.query(queryCase);
        
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5, 
                                                                     System.today(),
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
		
        test.startTest();
        
		DER_Agreement__c agmtUpd = [SELECT Id, Status__c, DER_Application__c, Offer_Accepted_Date__c, Offer_Made_Date__c
									FROM DER_Agreement__c 
									WHERE Id =: testAgmnt.Id LIMIT 1];
                
        agmtUpd.Status__c = DER_AGMT_STATUS_OFFER_ACCPT;
        agmtUpd.Offer_Accepted_Date__c = System.today() + 5;
        agmtUpd.Offer_Made_Date__c = System.today();
        update agmtUpd;
        
		test.stopTest();            
		
        lstCase = Database.query(queryCase);
        testAgmnt = [SELECT Id, Offer_Expiration_Date__c 
                                FROM DER_Agreement__c 
                                WHERE Id =: testAgmnt.Id];

		System.assertEquals(DER_AGMT_STATUS_OFFER_ACCPT, lstCase[0].Contract_Status__c);
        System.assertEquals(System.today() + 5, lstCase[0].Offer_Accepted_Date__c);
        System.assertEquals(testAgmnt.Offer_Expiration_Date__c, lstCase[0].Offer_Expiration_Date__c);
	}	

    @isTest static void test_Agreement_CLEAR_STATUS()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  

        List<Case> lstCase = Database.query(queryCase);
        
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5, 
                                                                     System.today(),
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
		
        test.startTest();

		DER_Agreement__c agmtUpd = [SELECT Id, Status__c, DER_Application__c, Offer_Accepted_Date__c, Offer_Made_Date__c
									FROM DER_Agreement__c 
									WHERE Id =: testAgmnt.Id LIMIT 1];
                
        agmtUpd.Status__c = null;
        agmtUpd.Offer_Accepted_Date__c = null;
        agmtUpd.Offer_Made_Date__c = null;
        update agmtUpd;
        
		test.stopTest();            
		
        lstCase = Database.query(queryCase);

		System.assertEquals(null, lstCase[0].Contract_Status__c);
        System.assertEquals(null, lstCase[0].Offer_Accepted_Date__c);
        System.assertEquals(null, lstCase[0].Offer_Expiration_Date__c);
	}	

    @isTest static void test_Agreement_CLEAR_DERAPP()
	{
		String queryCase = '';
            queryCase += UtilDatabase.getAllFields('Case');
            queryCase += ' FROM Case ';
			queryCase += ' WHERE ContactEmail =\''+ installerEmail + '\' LIMIT 1';  

        List<Case> lstCase = Database.query(queryCase);
        
        DER_Agreement__c testAgmnt = DER_TestUtility.createAgreement(lstCase[0].DER_Application__c, 
                                                                     lstCase[0].AccountId, 
                                                                     DER_AGMT_STATUS_OFFER_MADE, 
                                                                     System.today() + 5, 
                                                                     System.today(),
                                                                     DER_AGMT_OFFERTYPE_BASIC_MICRO);
        insert testAgmnt;
		
        test.startTest();

		DER_Agreement__c agmtUpd = [SELECT Id, Status__c, DER_Application__c
									FROM DER_Agreement__c 
									WHERE Id =: testAgmnt.Id LIMIT 1];
                
        agmtUpd.DER_Application__c = null;
        update agmtUpd;
        
		test.stopTest();            
		
        lstCase = Database.query(queryCase);

		System.assertEquals(null, lstCase[0].Contract_Status__c);
        System.assertEquals(null, lstCase[0].Offer_Accepted_Date__c);
        System.assertEquals(null, lstCase[0].Offer_Expiration_Date__c);
	}	
}