force-app/main/default/objects/Case/fields/Cancelled_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Reason__c</fullName>
    <label>Cancelled Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Not Received</fullName>
            </value>
            <value>
                <fullName>Applicant Declined</fullName>
            </value>
            <value>
                <fullName>AusNet Refused</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Unauthorised</fullName>
            </value>
            <value>
                <fullName>Flexible Exports Ineligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Used on Reconnect After Fault RT</description>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilCaseMatching.cls
/*
  @author  : brajesh.tiwary@ausnetservices.com.au
  @created : 31 Oct 2019
  @Description : Match NMI and meter and update case
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  31 Oct 2019           Brajesh                        Added method updateCaseMatchingNmiMeter
  -----------------------------------------------------------------------------------------
*/
public class UtilCaseMatching
{
	public static Boolean isRunning_casesMatched = false;
	private static Set<String> DER_RecordTypes = new Set<String>{DER_REST_Application_v1.CASE_RECORDTYPE_AUTO, DER_REST_Application_v1.CASE_RECORDTYPE_MANUAL};

	//----Update Case status and cancelled reason-----//
	public static void updateCaseMatchingNmiMeter(map<string,string> mapNMIMeter)
	{
		isRunning_casesMatched = true;
		List<Case> lstCaseUpd = new List<Case>();

		for(Case caseItem: [SELECT Id, Status, DER_Application__c, Cancelled_Reason__c,
							DER_Application__r.NMI__c, DER_Application__r.Meter_Number__c
							FROM Case
							WHERE DER_Application__r.NMI__c IN :mapNMIMeter.keySet()
							AND DER_Application__r.Meter_Number__c IN :mapNMIMeter.values()
							AND IsClosed = false
							AND RecordType.DeveloperName IN :DER_RecordTypes])
		{
			if (mapNMIMeter.containsKey(caseItem.DER_Application__r.NMI__c) &&
				mapNMIMeter.get(caseItem.DER_Application__r.NMI__c) != null &&
				mapNMIMeter.get(caseItem.DER_Application__r.NMI__c) == caseItem.DER_Application__r.Meter_Number__c)
			{
				Case updCase = new Case(Id = caseItem.Id);
				updCase.Status = 'Cancelled';
				updCase.Cancelled_Reason__c = 'Applicant Declined';
				lstCaseUpd.add(updCase);
			}
		}

		if (!lstCaseUpd.isEmpty()) update lstCaseUpd;
	}
}