force-app/main/default/objects/Case/fields/Case_Ready__c.field-meta.xml
<CustomField>
    <fullName>Case_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Indicates which region this Case / Application is part of. This will also be used to send emails to Design Engineers when a Case is assigned to the DER Apps - Design Team Queue</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/Haus_Num_2__c.field-meta.xml
<CustomField>
    <fullName>Haus_Num_2__c</fullName>
    <label>Haus Num 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/fields/House_Num_1__c.field-meta.xml
<CustomField>
    <fullName>House_Num_1__c</fullName>
    <label>House Num 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/fields/House_Num_2__c.field-meta.xml
<CustomField>
    <fullName>House_Num_2__c</fullName>
    <label>House Num 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Connection_Point__c/fields/NMI_Ref__c.field-meta.xml
<CustomField>
    <fullName>NMI_Ref__c</fullName>
    <label>NMI Ref</label>
    <length>255</length>
    <referenceTo>NmiDataSets__x</referenceTo>
    <relationshipLabel>Connection Points</relationshipLabel>
    <relationshipName>Connection_Points</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/NmiDataSets__x.object-meta.xml
<CustomObject>
    <description>NmiDataSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>NmiDataSets</externalName>
    <label>NmiDataSets</label>
    <pluralLabel>NmiDataSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/NmiDataSets__x/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <description>Building</description>
    <externalDeveloperName>Building</externalDeveloperName>
    <label>Building</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/City1__c.field-meta.xml
<CustomField>
    <fullName>City1__c</fullName>
    <description>City1</description>
    <externalDeveloperName>City1</externalDeveloperName>
    <label>City1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <description>Floor</description>
    <externalDeveloperName>Floor</externalDeveloperName>
    <label>Floor</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/HausNum2__c.field-meta.xml
<CustomField>
    <fullName>HausNum2__c</fullName>
    <description>HausNum2</description>
    <externalDeveloperName>HausNum2</externalDeveloperName>
    <label>HausNum2</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/HouseNum1__c.field-meta.xml
<CustomField>
    <fullName>HouseNum1__c</fullName>
    <description>HouseNum1</description>
    <externalDeveloperName>HouseNum1</externalDeveloperName>
    <label>HouseNum1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/HouseNum2__c.field-meta.xml
<CustomField>
    <fullName>HouseNum2__c</fullName>
    <description>HouseNum2</description>
    <externalDeveloperName>HouseNum2</externalDeveloperName>
    <label>HouseNum2</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/Nmistatuscode__c.field-meta.xml
<CustomField>
    <fullName>Nmistatuscode__c</fullName>
    <description>Nmistatuscode</description>
    <externalDeveloperName>Nmistatuscode</externalDeveloperName>
    <label>Nmistatuscode</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/PostCode1__c.field-meta.xml
<CustomField>
    <fullName>PostCode1__c</fullName>
    <description>PostCode1</description>
    <externalDeveloperName>PostCode1</externalDeveloperName>
    <label>PostCode1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/RegionalStructure__c.field-meta.xml
<CustomField>
    <fullName>RegionalStructure__c</fullName>
    <description>RegionalStructure</description>
    <externalDeveloperName>RegionalStructure</externalDeveloperName>
    <label>RegionalStructure</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Street</description>
    <externalDeveloperName>Street</externalDeveloperName>
    <label>Street</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/fields/StrSuppl1__c.field-meta.xml
<CustomField>
    <fullName>StrSuppl1__c</fullName>
    <description>StrSuppl1</description>
    <externalDeveloperName>StrSuppl1</externalDeveloperName>
    <label>StrSuppl1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DER_Connection_Point_Util.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 15 Oct 2019
  @Description : Util Class for Connection_Point__c Trigger
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  24/10/2019                    Brajesh                              CMC1401
  12-Nov-19            Pavan Dave                     Since Integration Profile user not able to query external object, chaning to 'without sharing' (CMC-1595)
  -----------------------------------------------------------------------------------------
*/

public without sharing class DER_Connection_Point_Util
{
	public static Boolean isRunning_PopulateExternalNMIRef = false;
	public static Boolean runAsFuture = true;
	public static Boolean updateCase = true;
	@TestVisible private static List<NmiDataSets__x> mockedExtNMI = new List<NmiDataSets__x>();

	@future
	public static void futurePopulateExternalNMIRef(Set<Id> validExtNMIRef_Pop, Set<Id> validExtNMIRef_Clear)
	{
		runAsFuture = false;
		PopulateExternalNMIRef(validExtNMIRef_Pop, validExtNMIRef_Clear);
	}

	public static void PopulateExternalNMIRef(Set<Id> validExtNMIRef_Pop, Set<Id> validExtNMIRef_Clear)
	{
		if (runAsFuture && !System.isFuture())
		{
			futurePopulateExternalNMIRef(validExtNMIRef_Pop, validExtNMIRef_Clear);
			return;
		}

		isRunning_PopulateExternalNMIRef = true;
		List<Connection_Point__c> lstConPointUpd = new List<Connection_Point__c>();
		Connection_Point__c conPoint;
		Set<Id> NMIIds = new Set<Id>();

		if (validExtNMIRef_Pop == null) validExtNMIRef_Pop = new Set<Id>();
		if (validExtNMIRef_Clear == null) validExtNMIRef_Clear = new Set<Id>();

		try
		{
			if (!validExtNMIRef_Pop.isEmpty())
			{
				Map<Id, Connection_Point__c> mapConPoints = new Map<Id, Connection_Point__c>([SELECT Id, NMI__c, Name,
																								Building_Name__c,House_Num_1__c,House_Num_2__c, Haus_Num_2__c,Floor__c,Street__c,
																								Post_Code__c,City__c,Country__c,State__c
																							FROM Connection_Point__c
																							WHERE Id IN :validExtNMIRef_Pop]);
				Set<String> lstExternalId = new Set<String>();
				for (Connection_Point__c item: mapConPoints.values())
				{
					if (item.NMI__c != null)
					{
						lstExternalId.add(item.NMI__c);
					}
				}

				if (!lstExternalId.isEmpty())
				{
					List <NmiDataSets__x> lstExtNMI;
					if (!mockedExtNMI.isEmpty())
					{
						// test data is set using test class
						lstExtNMI = mockedExtNMI;
					}
					else
					{
						lstExtNMI = new List<NmiDataSets__x> ([SELECT Id, ExternalId, Building__c, City1__c, Country__c,
																						Floor__c, HausNum2__c, HouseNum1__c,
																						HouseNum2__c, Location__c, Nmistatuscode__c,
																						Nmi__c, PostCode1__c, RegionalStructure__c,
																						Region__c, Street__c,StrSuppl1__c
																					FROM NmiDataSets__x
																					WHERE ExternalId IN: lstExternalId]);
					}

					Map<String, NmiDataSets__x> mapExtIdExtMtr = new Map<String, NmiDataSets__x>();
					for (NmiDataSets__x item: lstExtNMI)
					{
						mapExtIdExtMtr.put(item.ExternalId, item);
					}

					for (Id item: mapConPoints.keySet())
					{
						conPoint = mapConPoints.get(item);

						if (conPoint.NMI__c != null &&
							mapExtIdExtMtr.containsKey(conPoint.NMI__c) &&
							conPoint.NMI__c == (mapExtIdExtMtr.get(conPoint.NMI__c)).ExternalId)
						{
							conPoint.NMI_Ref__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).ExternalId;
							conPoint.Name = 'NMI: ' + conPoint.NMI__c;
							conPoint.Building_Name__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).StrSuppl1__c;
							conPoint.House_Num_1__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).HouseNum1__c;
							conPoint.House_Num_2__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).HouseNum2__c;
							conPoint.Haus_Num_2__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).HausNum2__c;
							conPoint.Floor__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).Floor__c;
							conPoint.Street__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).Street__c;
							conPoint.Post_Code__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).PostCode1__c;
							conPoint.City__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).City1__c;
							conPoint.Country__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).Country__c;
							conPoint.State__c = (mapExtIdExtMtr.get(conPoint.NMI__c)).Region__c;

							lstConPointUpd.add(conPoint);
							NMIIds.add(conPoint.Id);
						}
						else
						{
							conPoint.NMI_Ref__c = null;
							if (conPoint.NMI__c != null)
								conPoint.Name = 'NMI: ' + conPoint.NMI__c;

							lstConPointUpd.add(conPoint);
							NMIIds.add(conPoint.Id);
						}
					}


				}
			}

			if (!validExtNMIRef_Clear.isEmpty())
			{
				Map<Id, Connection_Point__c> mapConPoints = new Map<Id, Connection_Point__c>([SELECT Id, NMI__c, NMI_Ref__c, Name, Building_Name__c,House_Num_1__c,
																							House_Num_2__c, Haus_Num_2__c,Floor__c,Street__c,
																							Post_Code__c,City__c,Country__c,State__c
																							FROM Connection_Point__c
																							WHERE Id IN: validExtNMIRef_Clear]);

				for (Id item: mapConPoints.keySet())
				{
					conPoint = mapConPoints.get(item);
					conPoint.NMI_Ref__c = null;
					if (conPoint.NMI__c != null)
						conPoint.Name = 'NMI: ' + conPoint.NMI__c;
					conPoint.Building_Name__c = null;
					conPoint.House_Num_1__c = null;
					conPoint.House_Num_2__c = null;
					conPoint.Haus_Num_2__c = null;
					conPoint.Floor__c = null;
					conPoint.Street__c = null;
					conPoint.Post_Code__c = null;
					conPoint.City__c = null;
					conPoint.Country__c = null;
					conPoint.State__c = null;

					lstConPointUpd.add(conPoint);
					NMIIds.add(conPoint.Id);
				}
			}

			if (!lstConPointUpd.isEmpty()) update lstConPointUpd;

			if (!NMIIds.isEmpty() && updateCase)
			{
				List<Case> updCases = [SELECT Id FROM Case 
									   WHERE IsClosed=false 
									   AND DER_Application__r.NMI__c IN :NMIIds];

				if (updCases != null && !updCases.isEmpty())
				{
					for (Case c: updCases)
						c.Case_Ready__c = true;

					update updCases;
				}
			}
		}
		catch(Exception e)
		{
			system.debug('DER_Connection_Point_Util.PopulateExternalNMIRef'+'Exception Occurred. Message: ' + e.getMessage()
										+ ' StackTrace: ' + e.getStackTraceString()
										+ ' Type: ' + e.getTypeName()
										+ ' Cause: ' + e.getCause());
		}
	}
}