force-app/main/default/objects/Case/fields/dcp_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>dcp_Applicant_Email__c</fullName>
    <description>Captures applicant&apos;s email from Storm Relief form</description>
    <label>Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Assisted_Referral_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Assisted_Referral_Date__c</fullName>
    <label>Assisted Referral Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_claim_Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>dcp_claim_Mailing_Address__c</fullName>
    <description>Captures Mailing Address from Claim form</description>
    <label>Mailing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Due_Date__c</fullName>
    <description>Due date of Case closure</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_EWOV_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>dcp_EWOV_Case_Number__c</fullName>
    <externalId>true</externalId>
    <label>EWOV Case Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_EWOV_Customer_Statement__c.field-meta.xml
<CustomField>
    <fullName>dcp_EWOV_Customer_Statement__c</fullName>
    <description>This captures customer statement from incoming EWOV email</description>
    <inlineHelpText>This captures customer statement from incoming EWOV email</inlineHelpText>
    <label>Customer Statement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_EWOV_Level__c.field-meta.xml
<CustomField>
    <fullName>dcp_EWOV_Level__c</fullName>
    <description>Level of EWOV Case</description>
    <label>EWOV Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assisted Referral</fullName>
            </value>
            <value>
                <fullName>Stage 1</fullName>
            </value>
            <value>
                <fullName>Stage 2</fullName>
            </value>
            <value>
                <fullName>Stage 3</fullName>
            </value>
            <value>
                <fullName>Final Stage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_EWOV_Salutation__c.field-meta.xml
<CustomField>
    <fullName>dcp_EWOV_Salutation__c</fullName>
    <description>Captures salutation of the customer from the New Assisted Referral</description>
    <inlineHelpText>Captures salutation of the customer from the New Assisted Referral</inlineHelpText>
    <label>Salutation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Final_Stage_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Final_Stage_Date__c</fullName>
    <label>Final Stage Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Resolution_Sought__c.field-meta.xml
<CustomField>
    <fullName>dcp_Resolution_Sought__c</fullName>
    <description>Case resolution details</description>
    <label>Resolution Sought</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Skip_Validations__c.field-meta.xml
<CustomField>
    <fullName>dcp_Skip_Validations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Skips validations for Email2Case scenarios so the case record can be created without hitting validations</description>
    <inlineHelpText>Skips validations for Email2Case scenarios so the case record can be created without hitting validations</inlineHelpText>
    <label>Skip Validations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Stage_1_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Stage_1_Date__c</fullName>
    <label>Stage 1 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Stage_2_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Stage_2_Date__c</fullName>
    <label>Stage 2 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/dcp_Stage_3_Date__c.field-meta.xml
<CustomField>
    <fullName>dcp_Stage_3_Date__c</fullName>
    <label>Stage 3 Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/dcp_EWOV.recordType-meta.xml
<RecordType>
    <fullName>dcp_EWOV</fullName>
    <active>true</active>
    <businessProcess>DCP Support Process</businessProcess>
    <description>All EWOV cases</description>
    <label>EWOV</label>
</RecordType>

force-app/main/default/classes/DCPCaseEWOVHandler.cls
public class DCPCaseEWOVHandler {
    public DCPCaseNewEWOVParser parser=new DCPCaseNewEWOVParser(); 
    public DCPCaseUpgradeEWOVParser upgradeParser= new DCPCaseUpgradeEWOVParser();
    
    public void beforeInsert(List<Case> cases) {                
        try{
            Id caseEWOVRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('dcp_EWOV').getRecordTypeId();
            List<Case> evovNewCases=new List<Case>();
            List<Case> evovExistingCases=new List<Case>();
            for(Case c: cases){                 
                if(c.RecordTypeId==caseEWOVRecordTypeId && c.Subject.startsWithIgnoreCase('New Assisted Referral')){                    
                    evovNewCases.add(c);
                }
                if(c.RecordTypeId==caseEWOVRecordTypeId && (c.Subject.startsWithIgnoreCase('Upgrade notification') || c.Subject.startsWithIgnoreCase('Further information') || c.Subject.startsWithIgnoreCase('New Stage'))){                    
                    evovExistingCases.add(c);
                }
            } 
            if(evovNewCases.size()>0){
                this.processNewEWOVCases(evovNewCases);
            }
            if(evovExistingCases.size()>0){
                this.processUpgradeNotification(evovExistingCases);
            }
        }
        catch(Exception e){System.debug('**Exception in beforeInsert');}
    }
    public void afterInsert(List<Case> cases) {    
        Id caseEWOVRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('dcp_EWOV').getRecordTypeId();
        List<Case> evovExistingCases=new List<Case>();
        Set<String> ewovReferences=new Set<String>();
        Map<String, Case> caseFromEWOVReference = new Map<String, Case>();
        for(Case c: cases){
            if(c.RecordTypeId==caseEWOVRecordTypeId && c.Subject<>NULL && (c.Subject.startsWithIgnoreCase('Upgrade notification') || c.Subject.startsWithIgnoreCase('Further information') || c.Subject.startsWithIgnoreCase('New Stage'))){                    
                evovExistingCases.add(c);
                ewovReferences.add(c.dcp_EWOV_Case_Number__c);
                caseFromEWOVReference.put(c.dcp_EWOV_Case_Number__c, c);
            }
        }
        List<Case> parentCases=[Select Id, dcp_EWOV_Case_Number__c, dcp_EWOV_Level__c, dcp_Stage_1_Date__c, dcp_Stage_2_Date__c, dcp_Stage_3_Date__c, dcp_Final_Stage_Date__c 
                                From Case
                                Where dcp_EWOV_Case_Number__c in :ewovReferences and IsDeleted=false];
        
        if(parentCases.size()>0){
            for(Case pc: parentCases){
                if(caseFromEWOVReference.containsKey(pc.dcp_EWOV_Case_Number__c)){
                    if(caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).Subject.startsWithIgnoreCase('Upgrade notification') || caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).Subject.startsWithIgnoreCase('New Stage')){
                        pc.dcp_EWOV_Level__c=caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).dcp_EWOV_Level__c;
                        pc.dcp_Stage_1_Date__c=pc.dcp_EWOV_Level__c=='Stage 1'?(caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).dcp_Stage_1_Date__c):Null;
                        pc.dcp_Stage_2_Date__c=pc.dcp_EWOV_Level__c=='Stage 2'?(caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).dcp_Stage_2_Date__c):Null;
                        pc.dcp_Stage_3_Date__c=pc.dcp_EWOV_Level__c=='Stage 3'?(caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).dcp_Stage_3_Date__c):Null;
                        pc.dcp_Final_Stage_Date__c=pc.dcp_EWOV_Level__c=='Final Stage'?(caseFromEWOVReference.get(pc.dcp_EWOV_Case_Number__c).dcp_Final_Stage_Date__c):Null;
                    }
                }
            }
            update parentCases;
        }
    }
    public void processNewEWOVCases(List<Case> newEWOVCases){
        for(Case c: newEWOVCases){
            c.dcp_EWOV_Level__c='Assisted Referral';
            c.dcp_Assisted_Referral_Date__c=Date.today();
            c.dcp_EWOV_Case_Number__c=this.parser.getEWOVReferenceNumber(c.Subject)!='0'?this.parser.getEWOVReferenceNumber(c.Subject):'';
            //c.dcp_EWOV_Salutation__c=this.parser.getEWOVReferenceNumber(c.Subject)!='0'?this.parser.getCustomerSalutation(c.Subject):'';
            c.SuppliedName=this.parser.getEWOVReferenceNumber(c.Subject)!='0'?this.parser.getCustomerName(c.Subject):'';
            c.dcp_Resolution_Sought__c=this.parser.getResolutionFromDescriptionBeforeInsert(c.Description, c);
            c.dcp_EWOV_Customer_Statement__c=this.parser.getCustomerStatementFromDescriptionBeforeInsert(c.Description, c);
            c.SuppliedPhone=this.parser.getMobileNumberFromDescriptionBeforeInsert(c.Description, c);
            c.dcp_Applicant_Email__c=this.parser.getEmailFromDescriptionBeforeInsert(c.Description, c);
            c.dcp_claim_Mailing_Address__c=this.parser.getMailingAddressFromDescriptionBeforeInsert(c.Description, c);
            c.dcp_Due_Date__c=this.parser.getDueDateDescriptionBeforeInsert(c.Description, c);
            c.Description=this.parser.getShortDescriptionFromDescriptionBeforeInsert(c.Description, c);
        }
    }
    public void processUpgradeNotification(List<Case> existingEWOVCases){
        List<String> ewovReferences=new List<String>();
        Map<String, Case> caseFromEWOVReference = new Map<String, Case>();
        
        System.debug('**existingEWOVCases size:'+existingEWOVCases.size());
        
        for(Case c: existingEWOVCases){
            System.debug('*** c.dcp_EWOV_Case_Number__c'+c.dcp_EWOV_Case_Number__c);
            if(c.Subject.startsWithIgnoreCase('Upgrade notification')){
                c.dcp_EWOV_Case_Number__c=this.upgradeParser.getEWOVReferenceNumber(c.Subject)!='0'?this.upgradeParser.getEWOVReferenceNumber(c.Subject):'';
                c.dcp_EWOV_Level__c=this.upgradeParser.getStageFromDescriptionBeforeInsert(c.Description, c);
                c.dcp_Stage_1_Date__c=c.dcp_EWOV_Level__c=='Stage 1'?(Date.today()):Null;
                c.dcp_Stage_2_Date__c=c.dcp_EWOV_Level__c=='Stage 2'?(Date.today()):Null;
                c.dcp_Stage_3_Date__c=c.dcp_EWOV_Level__c=='Stage 3'?(Date.today()):Null;
                c.dcp_Final_Stage_Date__c=c.dcp_EWOV_Level__c=='Final Stage'?(Date.today()):Null;
            }
            else if(c.Subject.startsWithIgnoreCase('New Stage')){
                c.dcp_EWOV_Case_Number__c=this.upgradeParser.getEWOVReferenceNumberForNewStageEmails(c.Subject)!='0'?this.upgradeParser.getEWOVReferenceNumberForNewStageEmails(c.Subject):'';
                c.dcp_EWOV_Level__c=this.upgradeParser.getStageFromDescriptionBeforeInsert(c.Description, c);
                c.dcp_Stage_1_Date__c=c.dcp_EWOV_Level__c=='Stage 1'?(Date.today()):Null;
                c.dcp_Stage_2_Date__c=c.dcp_EWOV_Level__c=='Stage 2'?(Date.today()):Null;
                c.dcp_Stage_3_Date__c=c.dcp_EWOV_Level__c=='Stage 3'?(Date.today()):Null;
                c.dcp_Final_Stage_Date__c=c.dcp_EWOV_Level__c=='Final Stage'?(Date.today()):Null;
            }                           
            else if(c.Subject.startsWithIgnoreCase('Further information')){
                c.dcp_EWOV_Case_Number__c=this.upgradeParser.getEWOVReferenceNumberForFurtherInformationEmails(c.Subject)!='0'?this.upgradeParser.getEWOVReferenceNumberForFurtherInformationEmails(c.Subject):'';
            }
            
            if(c.dcp_EWOV_Case_Number__c<>'' && c.dcp_EWOV_Case_Number__c<>null){ewovReferences.add(c.dcp_EWOV_Case_Number__c);}                           
        }
        System.debug('**ewovReferences size:'+ewovReferences.size());
        
        List<Case> parentCases=[Select Id, dcp_EWOV_Case_Number__c, dcp_EWOV_Level__c, dcp_Stage_1_Date__c, dcp_Stage_2_Date__c, dcp_Stage_3_Date__c, dcp_Final_Stage_Date__c 
                                From Case
                                Where dcp_EWOV_Case_Number__c in :ewovReferences and IsDeleted=false];
        
        System.debug('**parentCases size:'+parentCases.size());
        
        if(parentCases.size()>0){ 
            System.debug('*** 1');
            for(Case c: parentCases){ 
                System.debug('*** 11');
                caseFromEWOVReference.put(c.dcp_EWOV_Case_Number__c, c); System.debug('*** 111');           
            }
            
            for(Case c: existingEWOVCases){ 
                System.debug('*** 2');
                if(caseFromEWOVReference.containsKey(c.dcp_EWOV_Case_Number__c)){ 
                    System.debug('*** 22');
                    c.ParentId=caseFromEWOVReference.get(c.dcp_EWOV_Case_Number__c).Id; System.debug('*** 222');
                    c.dcp_Skip_Validations__c=true;                                                            
                    c.Status='Closed';
                }
            }
        }
        
    }
    
}