force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>The Invoice Number from ERP</description>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Used on Reconnect After Fault RT</description>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilCaseMatchingTest.cls
@isTest
private class UtilCaseMatchingTest
{
	public  static String Case_RT   = DER_REST_Application_v1.CASE_RECORDTYPE_AUTO;
	private static Id     Case_RTId = UtilDatabase.getRecordTypeNames('Case').get(Case_RT);

	@testSetup static void setup()
	{
		// ------------------------------------------------------------- //
		// -------- Data setup for Notification field: Start------------ //
		// ------------------------------------------------------------ //

		//Create Individual Account
		Account testCustomer = DER_TestUtility.createPersonAccount('Person Account', 'test@test12345.com');
		insert testCustomer;


		//Create Connection Point
		Connection_Point__c testConnectionPoint = DER_TestUtility.createConnectionPoint(testCustomer.Id);
		testConnectionPoint.NMI__c = '6350682640';
		Insert testConnectionPoint;

		DER_Application__c testDERApp = DER_TestUtility.createDERApplication(testConnectionPoint.Id);
		testDERApp.Meter_Number__c = '12345';
		testDERApp.NMI__c = testConnectionPoint.Id;
		Insert testDERApp;

		 Case testCase = new Case(
			Subject = 'New Case',
			Origin = 'Web',
			RecordTypeId = Case_RTId,
			Invoice_Number__c = '12345',
			DER_Application__c = testDERApp.Id,
			Status ='Publish'
		);
		insert testCase;

		System.assertNotEquals(null, testCase.Id, 'Failed to insert testCase');
		// -------- Data setup for Notification field: End ------------ //
	}

	public static testMethod void testupdateCaseMatchingNmiMeter()
	{
		Map<String,String> mapNMIMeter = new Map<String,String>();
		DER_Application__c derApp = [Select Id,Meter_Number__c,NMI__c from DER_Application__c ][0];
		mapNMIMeter.put(derApp.NMI__c,derApp.Meter_Number__c);
		UtilCaseMatching.updateCaseMatchingNmiMeter(mapNMIMeter);
	}
}