force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/DER_App_Auto.recordType-meta.xml
<RecordType>
    <fullName>DER_App_Auto</fullName>
    <active>true</active>
    <businessProcess>DER Application - Auto</businessProcess>
    <label>DER Application - Auto</label>
</RecordType>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Cap__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Cap__c</fullName>
    <description>DER Register Level 2 – AC Connection
The rated AC output power that is listed in the product specified by the manufacturer.</description>
    <label>AC Equipment Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Exp__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Exp__c</fullName>
    <label>AC Equipment Export (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <description>Identifies the generation type for the equipment</description>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Count__c.field-meta.xml
<CustomField>
    <fullName>Device_Count__c</fullName>
    <description>DER Register Level 2 – AC Connection
Number of AC Connections in the group. For the suite of AC Connections to be considered as a group , all of the AC Connections included must have the same attributes.

DER Register Level 3 – DER Device
Number of devices in the group of DER devices.</description>
    <label>Device Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Phase__c.field-meta.xml
<CustomField>
    <fullName>Device_Phase__c</fullName>
    <description>Selection of the phase this device is on
If 3 Phase is selected, the Phase sits across Phase A, B, and C</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>3 Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Sub_Type__c</fullName>
    <description>DER Register Level 3 – DER Device

This field is also used to record for example the battery chemistry, or the type of PV panel. It is also used to record if a battery is contained in an electric vehicle connected in a vehicle-to-grid arrangement.</description>
    <label>Device Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monocrystalline</fullName>
            </value>
            <value>
                <fullName>Polycrystalline</fullName>
            </value>
            <value>
                <fullName>Thin-film</fullName>
            </value>
            <value>
                <fullName>Concentrating PV</fullName>
            </value>
            <value>
                <fullName>Silicon</fullName>
            </value>
            <value>
                <fullName>Biohybrid</fullName>
            </value>
            <value>
                <fullName>Cadmium telluride</fullName>
            </value>
            <value>
                <fullName>Lithium-ion</fullName>
            </value>
            <value>
                <fullName>Lead acid</fullName>
            </value>
            <value>
                <fullName>Lead carbon sodium nickel</fullName>
            </value>
            <value>
                <fullName>Lead crystal</fullName>
            </value>
            <value>
                <fullName>Absorbed glass matt</fullName>
            </value>
            <value>
                <fullName>Vanadium</fullName>
            </value>
            <value>
                <fullName>Aqueous hybrid ion</fullName>
            </value>
            <value>
                <fullName>Tubular gel</fullName>
            </value>
            <value>
                <fullName>Zinc bromide</fullName>
            </value>
            <value>
                <fullName>Electric Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <description>DER Register Level 3 – DER Device

Used to indicate the primary technology used in the DER device.</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar PV</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Device_Hierarchy_Test.cls
@isTest
private class Device_Hierarchy_Test
{
	public static testMethod void device_insert_success()
	{
		User testUser = UtilDatabase_Test.getTestUser();
		Case derCase = [SELECT Id, Subject FROM Case LIMIT 1];

		Test.startTest();
		System.runAs(testUser)
		{
			Device_Hierarchy.getDeviceHierarchy(derCase.Id);
		}
		Test.stopTest();


	}



	@TestSetup
	public static void setup()
	{

		//Create User
		User testUser = DER_TestUtility.createTestUser();
		insert testUser;

		//Create Individual Account
		Account testCustomer = DER_TestUtility.createPersonAccount('Person Account', 'test@test12345.com');
		insert testCustomer;

		//Create Business Account
		Account testInstaller = DER_TestUtility.createBusinessAccount('Business Account');
		insert testInstaller;

		//Create Business Account's Contact
		Contact testInstallerContact = DER_TestUtility.createBusinessAccountContact(testInstaller.Id, 'Test', 'Installer', 'test@test12345.com');
		insert testInstallerContact;

		//Create Connection Point
		Connection_Point__c testConnectionPoint = DER_TestUtility.createConnectionPoint(testCustomer.Id);
		insert testConnectionPoint;


		//Create DER Application
		DER_Application__c testDERApp = DER_TestUtility.createDERApplication(testConnectionPoint.Id);
		insert testDERApp;

		// case
		Case derCase = DER_TestUtility.createCaseWith_Installer_Customer_Rep(testDERApp.Id,
															'DER_App_Auto',
															'New', 'Web', null,
															null, null,
															null, null,
															null, null);
		insert derCase;


		//Create Device1
		Device__c testDeviceL2 = DER_TestUtility.createDevice_L2(testDERApp.Id);
		testDeviceL2.Device_Phase__c = 'A';
		testDeviceL2.AC_Equip_Cap__c = 40;
		testDeviceL2.AC_Equip_Exp__c = 30;
		testDeviceL2.AC_Equip_Type__c = 'Inverter';
		testDeviceL2.AC_Equip_Sub_Type__c = 'Solar';
		testDeviceL2.Device_Count__c = 2;
		insert testDeviceL2;

		//Create Device L3
		Device__c testDeviceL3 = DER_TestUtility.createDevice_L3(testDeviceL2.Id);
		testDeviceL3.Device_Type__c = 'Solar PV';
		testDeviceL3.Device_Sub_Type__c = 'Monocrystalline';
		testDeviceL3.Device_Count__c = 5;
		insert testDeviceL3;
	}

	@isTest
	public static void testSearchInverter() {
		Boolean result = Device_Hierarchy.searchDevice('samplemockstring', 'Inverter');
		System.assertEquals(false, result);
	}

	@isTest
	public static void testSearchModule() {
		Boolean result = Device_Hierarchy.searchDevice('samplemockstring', 'Module');
		System.assertEquals(false, result);
	}
}