force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/DER_Agreement__c.object-meta.xml
<CustomObject>
    <label>DER Agreement</label>
    <nameField>
        <displayFormat>Agmt-{0000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DER_Payload.cls
/*
	@author  : pavan.dave@ausnetservices.com.au
	@created : 30 Aug 2019
	@Description : Payload Class for parsing JSON Request Body
	-----------------------------------------------------------------------------------------
	Change log
	-----------------------------------------------------------------------------------------
	Date                  Name                           Description
	-----------------------------------------------------------------------------------------
	NA                    NA                              NA
	-----------------------------------------------------------------------------------------
*/
public with sharing class DER_Payload {
	public Case derCase;
	public DER_Application__c derApp;
	public Connection_Point__c nmi;
	public List<Device__c> devices;
	public Account customer;
	public Account installer;
	public Contact installerContact;
	public Contact representative;
	public Account representativeCompany;
	public DER_Agreement__c derAgreement;

	public String getJSON()
	{
		return JSON.serialize(this);
	}
}