force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Cap__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Cap__c</fullName>
    <description>DER Register Level 2 – AC Connection
The rated AC output power that is listed in the product specified by the manufacturer.</description>
    <label>AC Equipment Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Exp__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Exp__c</fullName>
    <label>AC Equipment Export (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <description>Identifies the generation type for the equipment</description>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track Device history</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Decommission__c.field-meta.xml
<CustomField>
    <fullName>Decommission__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Decommission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Phase__c.field-meta.xml
<CustomField>
    <fullName>Device_Phase__c</fullName>
    <description>Selection of the phase this device is on
If 3 Phase is selected, the Phase sits across Phase A, B, and C</description>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>3 Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Existing_Device__c.field-meta.xml
<CustomField>
    <fullName>Existing_Device__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing Device</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track Device history</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DER_L2_Device_Lines_Test.cls
/*
@author  : palash.awasthi@ausnetservices.com.au
@created : 2 Jan 2020
@Description : Test Class for DER L2 Device Lines
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public with sharing class DER_L2_Device_Lines_Test {
    private static String customerEmail = 'customer@test12345.com';
    private static String installerEmail = 'installer@test12345.com';
    private static String repEmail = 'rep@test12345.com';
    
    @testSetup static void setup()
    {
        Id testDERAppId = DER_TestUtility.loadDERAppRecords(customerEmail, installerEmail, repEmail);
        List<Device__c> testDevList = new List<Device__c>(); 

        Device__c testDevice2 = DER_TestUtility.createDevice_L2(testDERAppId);
        testDevice2.AC_Equip_Type__c = 'Inverter';
        testDevice2.AC_Equip_Sub_Type__c = 'Solar';
        testDevice2.Device_Phase__c = 'A';
        testDevice2.AC_Equip_Cap__c = 50;
        testDevice2.AC_Equip_Exp__c = 30;
        testDevice2.Approved__c = TRUE;
        testDevList.add(testDevice2); 

        Device__c testDevice3 = DER_TestUtility.createDevice_L2(testDERAppId);
        testDevice3.AC_Equip_Type__c = 'Inverter';
        testDevice3.AC_Equip_Sub_Type__c = 'Solar';
        testDevice3.Device_Phase__c = 'A';
        testDevice3.AC_Equip_Cap__c = 60;
        testDevice3.AC_Equip_Exp__c = 30;
        testDevice3.Installed__c = TRUE;
        testDevList.add(testDevice3); 

        Device__c testDevice4 = DER_TestUtility.createDevice_L2(testDERAppId);
        testDevice4.AC_Equip_Type__c = 'Inverter';
        testDevice4.AC_Equip_Sub_Type__c = 'Solar';
        testDevice4.Device_Phase__c = 'A';
        testDevice4.AC_Equip_Cap__c = 70;
        testDevice4.AC_Equip_Exp__c = 30;
        testDevice4.Existing_Device__c = TRUE;
        testDevList.add(testDevice4); 

        Device__c testDevice5 = DER_TestUtility.createDevice_L2(testDERAppId);
        testDevice5.AC_Equip_Type__c = 'Inverter';
        testDevice5.AC_Equip_Sub_Type__c = 'Solar';
        testDevice5.Device_Phase__c = 'A';
        testDevice5.AC_Equip_Cap__c = 80;
        testDevice5.AC_Equip_Exp__c = 30;
        testDevice5.Decommission__c = TRUE;
        testDevList.add(testDevice5);

        insert testDevList;
    }


    @isTest static void testL2DeviceLinesTotal(){
        
        Case cas = [SELECT Id, DER_Application__c FROM Case];
        Map < String, Double > tableDataExpected = new Map < String, Double > ();
        Map < String, Double > tableDataActual = new Map < String, Double > ();
        tableDataExpected.put('Requested', 40);
        tableDataExpected.put('Approved', 50);
        tableDataExpected.put('Installed', 60);
        tableDataExpected.put('Existing', 70);
        tableDataExpected.put('Decommission', -80);
        tableDataExpected.put('Total', 30);
        Test.startTest();
        tableDataActual = DER_L2_Device_Lines.L2_Device_Lines(cas.Id);
        System.assertEquals(tableDataExpected, tableDataActual, 'The Actual and Expected values do not match');
        Test.stopTest();
    }
}