force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CECModules__x/CECModules__x.object-meta.xml
<CustomObject>
    <description>CECModules</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>CECModules</externalName>
    <label>CECModules</label>
    <pluralLabel>CECModules</pluralLabel>
</CustomObject>

force-app/main/default/objects/CECModules__x/fields/ModelNumber__c.field-meta.xml
<CustomField>
    <fullName>ModelNumber__c</fullName>
    <description>ModelNumber</description>
    <externalDeveloperName>ModelNumber</externalDeveloperName>
    <label>ModelNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CECModules__x/fields/ModuleNumber__c.field-meta.xml
<CustomField>
    <fullName>ModuleNumber__c</fullName>
    <description>ModuleNumber</description>
    <externalDeveloperName>ModuleNumber</externalDeveloperName>
    <label>ModuleNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CECModules__x/fields/OutputAtSTC__c.field-meta.xml
<CustomField>
    <fullName>OutputAtSTC__c</fullName>
    <description>OutputAtSTC</description>
    <externalDeveloperName>OutputAtSTC</externalDeveloperName>
    <label>OutputAtSTC</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <description>Identifies the generation type for the equipment</description>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Count__c.field-meta.xml
<CustomField>
    <fullName>Device_Count__c</fullName>
    <description>DER Register Level 2 – AC Connection
Number of AC Connections in the group. For the suite of AC Connections to be considered as a group , all of the AC Connections included must have the same attributes.

DER Register Level 3 – DER Device
Number of devices in the group of DER devices.</description>
    <label>Device Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Sub_Type__c</fullName>
    <description>DER Register Level 3 – DER Device

This field is also used to record for example the battery chemistry, or the type of PV panel. It is also used to record if a battery is contained in an electric vehicle connected in a vehicle-to-grid arrangement.</description>
    <label>Device Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monocrystalline</fullName>
            </value>
            <value>
                <fullName>Polycrystalline</fullName>
            </value>
            <value>
                <fullName>Thin-film</fullName>
            </value>
            <value>
                <fullName>Concentrating PV</fullName>
            </value>
            <value>
                <fullName>Silicon</fullName>
            </value>
            <value>
                <fullName>Biohybrid</fullName>
            </value>
            <value>
                <fullName>Cadmium telluride</fullName>
            </value>
            <value>
                <fullName>Lithium-ion</fullName>
            </value>
            <value>
                <fullName>Lead acid</fullName>
            </value>
            <value>
                <fullName>Lead carbon sodium nickel</fullName>
            </value>
            <value>
                <fullName>Lead crystal</fullName>
            </value>
            <value>
                <fullName>Absorbed glass matt</fullName>
            </value>
            <value>
                <fullName>Vanadium</fullName>
            </value>
            <value>
                <fullName>Aqueous hybrid ion</fullName>
            </value>
            <value>
                <fullName>Tubular gel</fullName>
            </value>
            <value>
                <fullName>Zinc bromide</fullName>
            </value>
            <value>
                <fullName>Electric Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <description>DER Register Level 3 – DER Device

Used to indicate the primary technology used in the DER device.</description>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar PV</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <description>DER Register Level 2 – AC Connection
DER Register Level 3 – DER Device

Identifies the device manufacturer</description>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Parent_Device__c.field-meta.xml
<CustomField>
    <fullName>Parent_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/recordTypes/Device_L2.recordType-meta.xml
<RecordType>
    <fullName>Device_L2</fullName>
    <active>true</active>
    <label>AC Equipment - L2</label>
</RecordType>

force-app/main/default/objects/Device__c/recordTypes/Device_L3.recordType-meta.xml
<RecordType>
    <fullName>Device_L3</fullName>
    <active>true</active>
    <label>DER Device - L3</label>
</RecordType>

force-app/main/default/objects/Inverters__x/Inverters__x.object-meta.xml
<CustomObject>
    <description>Inverters</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>Inverters</externalName>
    <label>Inverters</label>
    <pluralLabel>Inverters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inverters__x/fields/inverter_number__c.field-meta.xml
<CustomField>
    <fullName>inverter_number__c</fullName>
    <description>inverter_number</description>
    <externalDeveloperName>inverter_number</externalDeveloperName>
    <label>inverter_number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inverters__x/fields/manufacturer__c.field-meta.xml
<CustomField>
    <fullName>manufacturer__c</fullName>
    <description>manufacturer</description>
    <externalDeveloperName>manufacturer</externalDeveloperName>
    <label>manufacturer</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inverters__x/fields/model_number__c.field-meta.xml
<CustomField>
    <fullName>model_number__c</fullName>
    <description>model_number</description>
    <externalDeveloperName>model_number</externalDeveloperName>
    <label>model_number</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inverters__x/fields/rated_apparent_va__c.field-meta.xml
<CustomField>
    <fullName>rated_apparent_va__c</fullName>
    <description>rated_apparent_va</description>
    <externalDeveloperName>rated_apparent_va</externalDeveloperName>
    <label>rated_apparent_va</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Device_Hierarchy.cls
public class Device_Hierarchy
{
	@AuraEnabled
	public static List<items> getDeviceHierarchy(Id caseId)
	{
		// Wrapper instance
		List<items> finalWrp = new List<items>();

		Case Caserecord = [SELECT DER_Application__c, DER_Application__r.Name FROM Case WHERE Id = :caseId];

		// Going upto 2 level only as per SOQL limit
		for (Device__c devL2 : [SELECT Id, Name, RecordType.Name, AC_Equip_Type__c, AC_Equip_Sub_Type__c, Device_Count__c,
		 						(SELECT Id, Name, RecordType.Name, Parent_Device__c, Device_Type__c, Device_Sub_Type__c, Device_Count__c
								 	FROM Devices__r
									 WHERE RecordType.DeveloperName='Device_L3')
								FROM Device__c
								WHERE DER_Application__c = :Caserecord.DER_Application__c
								AND RecordType.DeveloperName='Device_L2'])
		{
			// populating wrapper
			List<items> trP3 = new List<items>();
			for (Device__c devL3: devL2.Devices__r)
			{
				trP3.add(new items(devL3.RecordType.Name, devL3.Device_Type__c + ' - ' + devL3.Device_Sub_Type__c + ' (x'+devL3.Device_Count__c+')', true, null));
			}

			finalWrp.add(new items(devL2.RecordType.Name, devL2.AC_Equip_Type__c + ' - ' + devL2.AC_Equip_Sub_Type__c + ' (x'+devL2.Device_Count__c+')', true, trP3));
		}

		return finalWrp;
	}

	@AuraEnabled 
	public static Boolean searchDevice(String queryString, String searchType) {
		if(searchType == 'Inverter') {
			for(Inverters__x inv : [SELECT inverter_number__c, model_number__c, manufacturer__c, rated_apparent_va__c
									  FROM 	 Inverters__x]) { //External Objects don't support like) {
				if((inv.model_number__c != null && inv.model_number__c.contains(queryString)) ||
					(inv.manufacturer__c != null && inv.manufacturer__c.contains(queryString)) ||
					(inv.rated_apparent_va__c != null && inv.rated_apparent_va__c.contains(queryString))) {
					return true;
				}
			}
		}
		if(searchType == 'Module') {
			for(CECModules__x module: [SELECT ModuleNumber__c, ModelNumber__c, OutputAtSTC__c FROM CECModules__x]) {
				if((module.ModuleNumber__c != null && module.ModuleNumber__c.contains(queryString)) ||
					(module.ModelNumber__c != null && module.ModelNumber__c.contains(queryString)) ||
					(module.OutputAtSTC__c != null && module.OutputAtSTC__c.contains(queryString))) {
					return true;
				}
			}
		}

		return false;
	}

	public class items
	{
		@AuraEnabled public String label { get; set; }
		@AuraEnabled public String name { get; set; }
		@AuraEnabled public Boolean expanded { get; set; }
		@AuraEnabled public List<items> items { get; set; }

		public items(String name, String label, Boolean expanded, List<items> items)
		{
			this.label = label;
			this.name = name;
			this.expanded = expanded;
			this.items = items;
		}
	}
 }