force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/AgentLastName__c.field-meta.xml
<CustomField>
    <fullName>AgentLastName__c</fullName>
    <description>Last name of the customer agent, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Agent Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ApplicantContact__c.field-meta.xml
<CustomField>
    <fullName>ApplicantContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Applicant Contact)</relationshipLabel>
    <relationshipName>Projects_App_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ApplicationType__c.field-meta.xml
<CustomField>
    <fullName>ApplicationType__c</fullName>
    <label>Application Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/IsPropertyOwner__c.field-meta.xml
<CustomField>
    <fullName>IsPropertyOwner__c</fullName>
    <description>Property owner of the installation place</description>
    <label>Is Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/JobType__c.field-meta.xml
<CustomField>
    <fullName>JobType__c</fullName>
    <label>Job Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerABN__c.field-meta.xml
<CustomField>
    <fullName>OwnerABN__c</fullName>
    <description>Australian Business Number
Must receive just numbers</description>
    <label>Owner ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerCompany__c.field-meta.xml
<CustomField>
    <fullName>OwnerCompany__c</fullName>
    <description>Name of owner company with which lead is affiliated. Up to 255 characters are allowed in this field.</description>
    <label>Owner Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerEmail__c.field-meta.xml
<CustomField>
    <fullName>OwnerEmail__c</fullName>
    <description>Email address of property owner. Must be a valid email address in the form: jsmith@acme.com. Up to 80 characters are allowed in this field.</description>
    <label>Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerLastName__c.field-meta.xml
<CustomField>
    <fullName>OwnerLastName__c</fullName>
    <description>Last name of the property owner, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Owner Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerMobile__c.field-meta.xml
<CustomField>
    <fullName>OwnerMobile__c</fullName>
    <description>Cellular or mobile phone number. Up to 40 characters are allowed in this field.</description>
    <label>Owner Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PreliminaryOfferAcceptanceDate__c.field-meta.xml
<CustomField>
    <fullName>PreliminaryOfferAcceptanceDate__c</fullName>
    <description>It is updated when the last task type Prelim Offer is closed as accepted.</description>
    <label>Preliminary Offer Acceptance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectAssigmentStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssigmentStatus__c</fullName>
    <label>Project Assignment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AssigmentStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatus__c.field-meta.xml
<CustomField>
    <fullName>SAPStatus__c</fullName>
    <defaultValue>&quot;REGI&quot;</defaultValue>
    <description>Display of where the project is up to</description>
    <label>SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CMStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SAPStatusFlag__c.field-meta.xml
<CustomField>
    <fullName>SAPStatusFlag__c</fullName>
    <label>Status Flag</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SignatureStatus__c.field-meta.xml
<CustomField>
    <fullName>SignatureStatus__c</fullName>
    <label>SignatureStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/TVE_EmailHelperTNCTest.cls
/*
@author  : arti.fogla@ausnetservices.com.au
@created : 20 March 2019
@Description : Test class for TVE_EmailHelperTNC 
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public class TVE_EmailHelperTNCTest {
    public static final string testUserEmail = 'testuser@TVEArtefactControllerTest.com';
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Payment pending (Application submitted)';
    public static final string PROGRESS_BAR_STATUS_DESIGN = 'Payment pending (Application submitted)';
    
    @isTest
    static void sendEmailswithTNC(){
        
        
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        Contact con = [select id from Contact limit 1];
        Project__c proj = [select id from Project__c limit 1];
        emailTemplate template =[select id,developername from emailTemplate where Name ='Test' limit 1];
        account acc= TVE_TestUtility.createBusinessAccount('test');
        insert acc;
      
        TVE_EmailHelperTNC.EmailActionRequest request = new TVE_EmailHelperTNC.EmailActionRequest();
        request.primaryRecipientContactRequired = con.id;
        request.recordId = proj.Id;
        request.emailTemplateDevName=template.developername;
        request.toEmailsSemiColonSeperatedOptional='test@gmail.com';
        Test.startTest();
        List<TVE_EmailHelperTNC.EmailActionRequest> requests = new List<TVE_EmailHelperTNC.EmailActionRequest>();
        requests.add(request);
        if(requests!=null)    
            List<TVE_EmailHelperTNC.EmailActionResult> results = TVE_EmailHelperTNC.sendEmailWithTNC(requests);
        Test.stoptest();
    }
    
    @TestSetup
    public static void setup() {
        
        
        //Create User
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
        system.runAs(testUser){
            Emailtemplate et=new Emailtemplate(Name='Test',
                                               FolderId=UserInfo.getUserId(), 
                                               TemplateType='text',
                                               developername='test',
                                               isActive=true);
            insert et;
        }
        
        //Create Business Account
        Account testInstaller = TVE_TestUtility.createBusinessAccount('Business Account');
        database.insert(testInstaller,false) ;
        system.debug('testInstaller'+testInstaller);
        Contact con = new Contact();
        con.LastName = 'test1';
        Database.insert(con,false);
        system.debug('con'+con);

        Project__c projObj = TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE);
        projObj.OwnerLastName__c = 'testLastName';
        projObj.AgentLastName__c = 'testLastName98';
        projObj.OwnerABN__c = '123456789';
        projObj.OwnerCompany__c = 'testOwnerComp';
        projObj.OwnerMobile__c = '8932438932';
        projObj.IsPropertyOwner__c = 'Yes';
        projObj.OwnerCompany__c = '';
        projObj.OwnerEmail__c = 'abc@email.com';
        projObj.ApplicantContact__c=con.id;
        projObj.JobType__c='R-NEXT-M-106-00';
        projObj.ApplicationType__c='Residential';
        projObj.SignatureStatus__c='';
        projObj.SAPStatus__c='COMT';
        projObj.ProjectAssigmentStatus__c='Accepted';
        projObj.PreliminaryOfferAcceptanceDate__c=System.today();
        projObj.SAPStatusFlag__c='';
        
        Trig_Project.TrigDisabled=true;
        
        Database.Insert(projObj,false) ;
        system.debug('projObj'+projObj);
    } 
}