force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ConstructionCompletionDate__c.field-meta.xml
<CustomField>
    <fullName>ConstructionCompletionDate__c</fullName>
    <label>Construction Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TVE_WorkOrder_Utility.cls
/*
@author  : lakshay.sharma@ausnetservices.com.au
@created : 27 Feb 2020
@Description : Class for WorkOrder Utility
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
public with sharing class TVE_WorkOrder_Utility {
    public static void updateWorkOrder(Map<Id,Id> mapPrjIdWOid, Map<Id,WorkOrder> mapWO) {
        Project__c proj;
        List<Project__c> projList=new List<Project__c>();
    
        
        for(Id projId:mapPrjIdWOid.keySet()){
            proj=new Project__c(Id=projId,ConstructionCompletionDate__c=mapWO.get(mapPrjIdWOid.get(projId)).EndDate.date());
            projList.add(proj);
            
        }
        System.debug('projList'+projList);
        if(!projList.isEmpty())
        {
            update projList;
        }        
    }
         
        


}