force-app/main/default/objects/Incident/fields/Affected_Suburbs__c.field-meta.xml
<CustomField>
    <fullName>Affected_Suburbs__c</fullName>
    <label>Affected Suburbs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incident/fields/Public_Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Assessment_Date__c</fullName>
    <formula>uom_Estimated_assessment_date__c</formula>
    <label>Public Assessment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident/fields/Public_Status__c.field-meta.xml
<CustomField>
    <fullName>Public_Status__c</fullName>
    <formula>TEXT(Status)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Public Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident/fields/uom_Estimated_restoration_date__c.field-meta.xml
<CustomField>
    <fullName>uom_Estimated_restoration_date__c</fullName>
    <label>Estimated Time of Restoration (ETR)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident/fields/uom_Incident_Id__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident_Id__c</fullName>
    <externalId>true</externalId>
    <label>Incident Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Incident/fields/uom_Number_Off_Supply__c.field-meta.xml
<CustomField>
    <fullName>uom_Number_Off_Supply__c</fullName>
    <label>Number Off Supply</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incident/fields/uom_Operating_Zone__c.field-meta.xml
<CustomField>
    <fullName>uom_Operating_Zone__c</fullName>
    <label>Operating Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublicOutageController.cls
public without sharing class PublicOutageController {
    @AuraEnabled(cacheable=true)
    public static List<Incident> getIncidents() {
        return [SELECT Id, uom_Incident_Id__c, Public_Status__c, Type,uom_Estimated_restoration_date__c, 
        Public_Assessment_Date__c, uom_Operating_Zone__c, Affected_Suburbs__c, StartDateTime, Category, uom_Number_Off_Supply__c
        FROM Incident
        WHERE Status != 'Merged' AND Status != 'Cancelled' AND Status != 'Restored' AND uom_Number_Off_Supply__c != 0
        ORDER BY uom_Operating_Zone__c ASC, StartDateTime ASC];
    }
}