force-app/main/default/objects/Asset/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Conn_Point__c.field-meta.xml
<CustomField>
    <fullName>Conn_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connection Point</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Device_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Sub_Type__c</fullName>
    <label>Device Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monocrystalline</fullName>
            </value>
            <value>
                <fullName>Polycrystalline</fullName>
            </value>
            <value>
                <fullName>Thin-film</fullName>
            </value>
            <value>
                <fullName>Concentrating PV</fullName>
            </value>
            <value>
                <fullName>Silicon</fullName>
            </value>
            <value>
                <fullName>Biohybrid</fullName>
            </value>
            <value>
                <fullName>Cadmium telluride</fullName>
            </value>
            <value>
                <fullName>Lithium-ion</fullName>
            </value>
            <value>
                <fullName>Lead acid</fullName>
            </value>
            <value>
                <fullName>Lead carbon sodium nickel</fullName>
            </value>
            <value>
                <fullName>Lead crystal</fullName>
            </value>
            <value>
                <fullName>Absorbed glass matt</fullName>
            </value>
            <value>
                <fullName>Vanadium</fullName>
            </value>
            <value>
                <fullName>Aqueous hybrid ion</fullName>
            </value>
            <value>
                <fullName>Tubular gel</fullName>
            </value>
            <value>
                <fullName>Zinc bromide</fullName>
            </value>
            <value>
                <fullName>Electric Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solar PV</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset_DER_L2.recordType-meta.xml
<RecordType>
    <fullName>Asset_DER_L2</fullName>
    <active>true</active>
    <label>AC Equipment - L2</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Asset_DER_L3.recordType-meta.xml
<RecordType>
    <fullName>Asset_DER_L3</fullName>
    <active>true</active>
    <label>DER Device - L3</label>
</RecordType>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Used on Reconnect After Fault RT</description>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/Existing_Total_Export_Rating__c.field-meta.xml
<CustomField>
    <fullName>Existing_Total_Export_Rating__c</fullName>
    <label>Existing Total Export Rating</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Import_Existing_Assets__c.field-meta.xml
<CustomField>
    <fullName>Import_Existing_Assets__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Import Existing Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Meter_Install_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Meter_Install_Type_Code__c</fullName>
    <label>Meter Install Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Meter_Ref__c.field-meta.xml
<CustomField>
    <fullName>Meter_Ref__c</fullName>
    <label>Meter Ref</label>
    <length>255</length>
    <referenceTo>MeterDataSets__x</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Ph_A_New_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Ph_A_New_Capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Phase A New System Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Ph_B_New_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Ph_B_New_Capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Phase B New System Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Ph_C_New_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Ph_C_New_Capacity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Phase C New System Capacity (kVA)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MeterDataSets__x/MeterDataSets__x.object-meta.xml
<CustomObject>
    <description>MeterDataSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>MeterDataSets</externalName>
    <label>MeterDataSets</label>
    <pluralLabel>MeterDataSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/MeterDataSets__x/fields/Nmi__c.field-meta.xml
<CustomField>
    <fullName>Nmi__c</fullName>
    <description>Nmi</description>
    <externalDeveloperName>Nmi</externalDeveloperName>
    <label>Nmi</label>
    <length>128</length>
    <referenceTargetField>Connection_Point__c.NMI__c</referenceTargetField>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>MeterDataSets</relationshipLabel>
    <relationshipName>MeterDataSets</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/NmiDataSets__x/NmiDataSets__x.object-meta.xml
<CustomObject>
    <description>NmiDataSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>NmiDataSets</externalName>
    <label>NmiDataSets</label>
    <pluralLabel>NmiDataSets</pluralLabel>
</CustomObject>

force-app/main/default/classes/Trig_DER_Application_Test.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 23 Sep 2019
  @Description : Test class for DER Application Trigger and respective trigger logics
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/

@isTest
private class Trig_DER_Application_Test {
    
    private static String NMI_NUMBER = '123456789'; 
    private static String SERIAL_NUM = '1234'; 
    private static String TYPE_CODE = 'TEST'; 
    private static String customerEmail = 'customer@test12345.com';
    private static String installerEmail = 'installer@test12345.com';
    private static String repEmail = 'rep@test12345.com';
    private static String custEmailNotifLogic = 'customer@test12345.com';
    public  static String Asset_RT   = 'Asset_DER_L2';
    public  static String Asset_RT_L3   = 'Asset_DER_L3';
    private static Id  Asset_RTId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(Asset_RT).getRecordTypeId();
    private static Id  Asset_RTId_L3 = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(Asset_RT_L3).getRecordTypeId();
    
    public static testMethod void device_update_success(){
        User testUser = UtilDatabase_Test.getTestUser();
        DER_Application__c app = [SELECT Id, Ph_A_New_Capacity__c
                            FROM DER_Application__c LIMIT 1];
        
        Test.startTest();
        System.runAs(testUser){
            app.Ph_A_New_Capacity__c = 0;

            update app;            
        }
        Test.stopTest();

        DER_Application__c appAfterUpdate = (DER_Application__c) UtilDatabase.getRecord(app.Id);
        System.assertEquals(0, appAfterUpdate.Ph_A_New_Capacity__c);
        System.assertEquals(0, appAfterUpdate.Ph_B_New_Capacity__c);
        System.assertEquals(0, appAfterUpdate.Ph_C_New_Capacity__c);

    }

    public static testMethod void meter_ref_update(){
        User testUser = UtilDatabase_Test.getTestUser();
        Case derCase = [SELECT Id, DER_Application__c 
                            FROM Case
                            WHERE ContactEmail =: installerEmail
                            AND DER_Application__c != null];

        DER_Application__c derApp = [SELECT Id, Meter_Number__c , Meter_Ref__c, NMI__c
                                        FROM DER_Application__c 
                                        WHERE Id =: derCase.DER_Application__c
                                        AND NMI__c != null
                                        LIMIT 1];        
        Test.startTest();
        System.runAs(testUser){
            Connection_Point__c conPoint = [SELECT Id, NMI__c FROM Connection_Point__c WHERE Id =: derApp.NMI__c];
            conPoint.NMI__c = NMI_NUMBER;
            update conPoint;

            //Create NmiDataSets__x
            MeterDataSets__x testExtMtr = DER_TestUtility.createEXTMtr(NMI_NUMBER, SERIAL_NUM, TYPE_CODE);
            DER_Application_Util.mockedExtMtr.add(testExtMtr);
            
            derApp.Meter_Number__c = SERIAL_NUM;
            update derApp;            
        }
        Test.stopTest();

        DER_Application__c appAfterUpdate =  [SELECT Id, Meter_Number__c, Meter_Ref__c, Meter_Install_Type_Code__c
                                                    FROM DER_Application__c 
                                                    WHERE Id =: derApp.Id
                                                    LIMIT 1];
        System.assertNotEquals(null, appAfterUpdate.Meter_Install_Type_Code__c);
    }

    public static testMethod void meter_ref_clear(){
        User testUser = UtilDatabase_Test.getTestUser();
        Case derCase = [SELECT Id, DER_Application__c 
                            FROM Case
                            WHERE ContactEmail =: installerEmail
                            AND DER_Application__c != null];

        DER_Application__c derApp = [SELECT Id, Meter_Number__c , Meter_Ref__c, NMI__c
                                        FROM DER_Application__c 
                                        WHERE Id =: derCase.DER_Application__c
                                        AND NMI__c != null
                                        LIMIT 1];        

        Connection_Point__c conPoint = [SELECT Id, NMI__c FROM Connection_Point__c WHERE Id =: derApp.NMI__c];
        conPoint.NMI__c = NMI_NUMBER;
        update conPoint;

        //Create NmiDataSets__x
        MeterDataSets__x testExtMtr = DER_TestUtility.createEXTMtr(NMI_NUMBER, SERIAL_NUM, TYPE_CODE);
        DER_Application_Util.mockedExtMtr.add(testExtMtr);
        
        derApp.Meter_Number__c = SERIAL_NUM;
        update derApp;


        Test.startTest();
        System.runAs(testUser){
            
            derApp.Meter_Number__c = null;
            update derApp;            
        }
        Test.stopTest();

        DER_Application__c appAfterUpdate =  [SELECT Id, Meter_Number__c, Meter_Ref__c, Meter_Install_Type_Code__c
                                                    FROM DER_Application__c 
                                                    WHERE Id =: derApp.Id
                                                    LIMIT 1];
        System.assertEquals(null, appAfterUpdate.Meter_Install_Type_Code__c);
    }

     public static testMethod void upsertDeviceRecordsTest(){
          //Create Individual Account
        Account testCustomer = DER_TestUtility.createPersonAccount('Person Account', 'test@test12345.com');
        insert testCustomer;


        DER_Application__c derApp = new DER_Application__c();
        insert derApp;
         
       Connection_Point__c cp = new Connection_Point__c();
         cp.NMI__c = '123456';
         insert cp;
         
         derApp.NMI__c = cp.Id;
         update derApp;

        //Create Business Account
        Account testInstaller = DER_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;

        //Create Business Account's Contact
        Contact testInstallerContact = DER_TestUtility.createBusinessAccountContact(testInstaller.Id, 'Test', 'Installer', custEmailNotifLogic);
        insert testInstallerContact;

        //Create Business Account
        Account testRepAcc = DER_TestUtility.createBusinessAccount('Representative Business Account');
        insert testRepAcc;

        //Create Business Account's Contact
        Contact testRep = DER_TestUtility.createBusinessAccountContact(testInstaller.Id, 'Test', 'Representative', 'representative@test12345.com');
        insert testRep;

        //Create case with customer, installer & representative
        Case testCaseNotifLogic = DER_TestUtility.createCaseWith_Installer_Customer_Rep(derApp.Id,
                                                                                        DER_REST_Application_v1.CASE_RECORDTYPE_MANUAL,
                                                                                        'New', 'Email', 'Medium',
                                                                                        testInstaller.Id, testInstallerContact.Id,
                                                                                        testCustomer.Id, testRep.Id,
                                                                                        Trig_Case.APPLICANT_REP, Trig_Case.RESP_PARTY_REP);
        insert testCaseNotifLogic;

        Asset ast = new Asset();
        ast.Conn_Point__c = cp.Id;
        ast.Name = 'test1';
        ast.AC_Equip_Type__c = 'Inverter';
        ast.AC_Equip_Sub_Type__c = 'Solar';
        ast.RecordTypeId = Asset_RTId;
        ast.Status = 'Active';
        insert ast;

        Asset ast1 = new Asset();
        ast1.Name = 'test2';
        ast1.ParentId = ast.Id;
        ast1.Device_Type__c = 'Solar PV';
        ast1.Device_Sub_Type__c = 'Monocrystalline';
        ast1.RecordTypeId = Asset_RTId_L3;
        ast1.Status = 'Active';
        insert ast1;
         
        derApp.Import_Existing_Assets__c = true;
        derApp.Existing_Total_Export_Rating__c = 3.2;
        update derApp;
         
     }

    @TestSetup
    public static void setup() {
        
        //Create User
        User testUser = DER_TestUtility.createTestUser();
        insert testUser;

        Id testDERAppId = DER_TestUtility.loadDERAppRecords(customerEmail, installerEmail, repEmail);
    }      
}