force-app/main/default/objects/API_Callout_Headers__mdt/API_Callout_Headers__mdt.object-meta.xml
<CustomObject>
    <label>API Callout Headers</label>
    <pluralLabel>API Callout Header</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/endpoint__c.field-meta.xml
<CustomField>
    <fullName>endpoint__c</fullName>
    <label>endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/sourceSystem__c.field-meta.xml
<CustomField>
    <fullName>sourceSystem__c</fullName>
    <label>sourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/targetSystem__c.field-meta.xml
<CustomField>
    <fullName>targetSystem__c</fullName>
    <label>targetSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/AmountLine1ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine1ExGST__c</fullName>
    <label>Amount Line 1 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine2ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine2ExGST__c</fullName>
    <label>Amount Line 2 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine3ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine3ExGST__c</fullName>
    <label>Amount Line 3 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine1__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine1__c</fullName>
    <label>Material Code Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine2__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine2__c</fullName>
    <label>Material Code Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine3__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine3__c</fullName>
    <label>Material Code Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine3__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Sales Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_RequestInvoiceUtil.cls
public with sharing class TVE_SAPInteg_RequestInvoiceUtil {
    public static HttpResponse callRequestInvoice(Artefact__c artfctRecord,API_Callout_Headers__mdt apiCallHea) {

        Project__c projRec = [SELECT Id, SalesOrder__c FROM Project__c WHERE Id =: artfctRecord.Project__c];
        //RequestInvoiceSAPInteg reqInvIntegSAP = new RequestInvoiceSAPInteg();
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeFieldName('request');
        gen.writeStartObject();
        gen.writeStringField('key', apiCallHea.key__c);
        gen.writeStringField('msgId', TVE_Utility.getUniqueId(artfctRecord.Id));
        gen.writeStringField('sourceSystem', apiCallHea.sourceSystem__c);
        gen.writeStringField('targetSystem', apiCallHea.targetSystem__c);
        gen.writeStringField('objectName', apiCallHea.objectName__c);
        gen.writeFieldName('payload');
        gen.writeStartObject();
        gen.writeFieldName('d');
        gen.writeStartObject();
        gen.writeStringField('InvoiceNo','');
        gen.writeStringField('SalesOrder', projRec.SalesOrder__c);
        gen.writeStringField('SfInvoiceRefNum',artfctRecord.Id);
        gen.writeFieldName('ItemToCreateInvoiceSet');
        gen.writeStartObject();
        gen.writeFieldName('results');
        gen.writeStartArray();
        gen.writeStartObject();
        gen.writeStringField('InvoiceNo','');
        gen.writeStringField('SalesOrder',projRec.SalesOrder__c);
        gen.writeStringField('MaterialNumber',artfctRecord.MaterialCodeLine1__c);

        gen.writeStringField('BillTo', artfctRecord.Bill_To__c);
        gen.writeStringField('Price', String.valueOf(artfctRecord.AmountLine1ExGST__c));
        gen.writeEndObject();

        if(String.isNotEmpty(artfctRecord.MaterialCodeLine2__c)){
            gen.writeStartObject();
            gen.writeStringField('InvoiceNo','');
            gen.writeStringField('SalesOrder',projRec.SalesOrder__c);
            gen.writeStringField('MaterialNumber',artfctRecord.MaterialCodeLine2__c);

            gen.writeStringField('BillTo', artfctRecord.Bill_To__c);
            gen.writeStringField('Price', String.valueOf(artfctRecord.AmountLine2ExGST__c));
            gen.writeEndObject();
        }

        if(String.isNotEmpty(artfctRecord.MaterialCodeLine3__c)){
            gen.writeStartObject();
            gen.writeStringField('InvoiceNo','');
            gen.writeStringField('SalesOrder',projRec.SalesOrder__c);
            gen.writeStringField('MaterialNumber',artfctRecord.MaterialCodeLine3__c);

            gen.writeStringField('BillTo', artfctRecord.Bill_To__c);
            gen.writeStringField('Price', String.valueOf(artfctRecord.AmountLine3ExGST__c));
            gen.writeEndObject();
        }

        gen.writeEndArray();
        gen.writeEndObject();
        gen.writeEndObject();
        gen.writeEndObject();
        gen.writeEndObject();
        gen.writeEndObject();
        String jsonData = gen.getAsString();
        HttpResponse response;
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setClientCertificateName('eains');
        request.setBody(jsonData);
        system.debug('requestBody--'+request.getBody());
        request.setEndpoint(apiCallHea.endpoint__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        //request.setHeader('slug','SapObject=/CUM/CONSM,ObjectId=000075002168,ArObject=ZCU_ACCC,Filename=test.txt');
        response = http.send(request);
        system.debug('responseBody++'+response.getBody());
        return response;
    }
}