force-app/main/default/objects/API_Callout_Headers__mdt/API_Callout_Headers__mdt.object-meta.xml
<CustomObject>
    <label>API Callout Headers</label>
    <pluralLabel>API Callout Header</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/endpoint__c.field-meta.xml
<CustomField>
    <fullName>endpoint__c</fullName>
    <label>endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/sourceSystem__c.field-meta.xml
<CustomField>
    <fullName>sourceSystem__c</fullName>
    <label>sourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/targetSystem__c.field-meta.xml
<CustomField>
    <fullName>targetSystem__c</fullName>
    <label>targetSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Number__c</fullName>
    <externalId>true</externalId>
    <label>Notification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/TVE_Integration_Constants__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TVE Integration Constants</label>
</CustomObject>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Assembly__c.field-meta.xml
<CustomField>
    <fullName>Assembly__c</fullName>
    <label>Assembly</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Integration_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Method_Name__c</fullName>
    <label>Integration Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/MessageID__c.field-meta.xml
<CustomField>
    <fullName>MessageID__c</fullName>
    <label>MessageID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Partner_Role_1__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role_1__c</fullName>
    <label>Partner Role 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Partner_Role_2__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role_2__c</fullName>
    <label>Partner Role 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_CreateWork.cls
public without sharing class TVE_SAPInteg_CreateWork implements Queueable,Database.AllowsCallouts
{
    List<Integration_Task__c> lstIntgTask = new List<Integration_Task__c>();
    public void execute(QueueableContext qc)
    {
        Map<id,String> successMap = new Map<Id,String>();
        Map<id,String> failureMap = new Map<Id,String>();
        List<Id> projIdList = new List<id>();
        Map<id,Project__c> projectInfoMap = new Map<Id,Project__c>();
        Map<id,Opportunity> projOppMap = new Map<Id,Opportunity>();
        Map<id,Map<String,string>> BillToSoldToMap = new Map<id,Map<String,string>>();
        Project__c projRecord;
        Opportunity oppRecord;
        Map<String,String> BtStMap;
        Map<String,String> billToSoldToInfo;
        Map<String,String> creatIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMapfail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();
        Map<String,string> WOprojMap = new Map<String,string>();
        // TVE_SAP_Int_APICalls.CreateWorkResponse response;
        String response;
        TVE_Integration_Constants__c intConstant = [select Integration_Method_Name__c,Assembly__c,Partner_Role_1__c,Partner_Role_2__c,MessageID__c
                                                    from TVE_Integration_Constants__c 
                                                    where Integration_Method_Name__c='TVE_SAPInteg_CreateMasterNoti' limit 1];//TVE_Integration_Constants__c.getall().values();
        
        API_Callout_Headers__mdt apiCallHea = [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                               objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                               WHERE objectName__c ='CreateWork' ];
        lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Create','Project__c','CreateWork','In Progress');
        
        if(!lstIntgTask.isEmpty()){
            System.debug('callSAPreq eexecute');
            
            for(Integration_Task__c intTask: lstIntgTask)
            {
                projIdList.add(intTask.ParentId__c);
            }
            if(projIdList.size()>0)
            {
                BillToSoldToMap=TVE_IntegUtility.getSoldToBillTO(projIdList);
                WOprojMap= TVE_IntegUtility.getCMType(projIdList);
                List<Project__c> lstProjs=TVE_IntegUtility.getProject(projIdList);
                for(Project__c proj:lstProjs)
                {
                    projectInfoMap.put(proj.id,proj);
                }
                
                List<Opportunity> oppList=[select id,Notification_Number__c,Notification_Type__c,Project__c,System_Status__c
                                           from Opportunity where Project__c IN:projIdList and Type='Design'];
                System.debug('oppList list map'+oppList);
                if(oppList.size()>0)
                {
                    for(Opportunity opp:oppList)
                    {
                        projOppMap.put(opp.Project__c,opp);
                    }
                }
            }
            
            for(Integration_Task__c iTask: lstIntgTask)
            {
                if(projectInfoMap.containsKey(iTask.ParentId__c) && projOppMap.containsKey(iTask.ParentId__c)){
                    projRecord = projectInfoMap.get(iTask.ParentId__c);
                    oppRecord = projOppMap.get(iTask.ParentId__c);
                    
                    BtStMap = BillToSoldToMap.get(iTask.ParentId__c);
                    response=TVE_SAP_Int_APICalls.callcreateWorkreq(projRecord,oppRecord,BtStMap,
                                                                    intConstant,apiCallHea,WOprojMap);
                    System.debug('response in execute'+response);
                    //After response is received
                    if(response=='Created')
                        successMap.put(iTask.id,iTask.ParentId__c);
                    else
                        failureMap.put(iTask.id,response);
                } else {
                    failureMap.put(iTask.id, 'Error: Cannot find the related Project or Opportunity record.');
                }
            }
            
            if(successMap.size()>0)
            {
                updateIntTaskMap.put('Status__c','Successful');
                createIntglogmapS.put('Status__c','Successful');
                
                TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
                TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
                
            }
            if(FailureMap.size()>0)
            {
                updateIntTaskMapFail.put('Status__c','Failed');
                
                createIntglogmapF.put('Status__c','Failed');
                
                TVE_IntegUtility.UpdateInteTask(FailureMap,updateIntTaskMapFail);
                TVE_IntegUtility.createIntegLog(FailureMap,createIntglogmapF);
            }
        }
        lstIntgTask=TVE_IntegUtility.getIntegrationTask( 'Create','Project__c','CreateWork','In Progress');
        if(!lstIntgTask.isEmpty()){
            TVE_SAPInteg_CreateWork updateCM = new TVE_SAPInteg_CreateWork();
            ID jobID = System.enqueueJob(updateCM);  
        }
    }
    
}