force-app/main/default/objects/API_Callout_Headers__mdt/API_Callout_Headers__mdt.object-meta.xml
<CustomObject>
    <label>API Callout Headers</label>
    <pluralLabel>API Callout Header</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/endpoint__c.field-meta.xml
<CustomField>
    <fullName>endpoint__c</fullName>
    <label>endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/sourceSystem__c.field-meta.xml
<CustomField>
    <fullName>sourceSystem__c</fullName>
    <label>sourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/targetSystem__c.field-meta.xml
<CustomField>
    <fullName>targetSystem__c</fullName>
    <label>targetSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_UpdateCMQue.cls
public without sharing class TVE_SAPInteg_UpdateCMQue implements Queueable,Database.AllowsCallouts{
    List<Integration_Task__c> lstIntgTask = new List<Integration_Task__c>();
    /*public TVE_SAPInteg_UpdateCMQue(List<Integration_Task__c> lstIntgTask){
        this.lstIntgTask=lstIntgTask;
    }*/
     public void execute(QueueableContext qc)
    {
        List<Id> projIdList = new List<id>();
        Map<id,Project__c> projectInfoMap = new Map<Id,Project__c>();
        Project__c projRecord;
        TVE_SAP_Int_APICalls.UpdateCMResponse response;
         Map<id,String> successMap = new Map<Id,String>();
        Map<id,String> failureMap = new Map<Id,String>();
        //Map<String,String> creatIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
         Map<String,String> updateIntTaskMapfail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();
        
        API_Callout_Headers__mdt apiCallHea = [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                               objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                               WHERE objectName__c ='UpdateConstructionMeasure' ];
        
     	lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Update','Project__c','UpdateCM','In Progress');
        if(!lstIntgTask.isEmpty()){
             for(Integration_Task__c intTask: lstIntgTask)
            {
                Boolean checkId = (intTask.ParentId__c InstanceOf Id);
                if(checkId)
                {
                    projIdList.add(intTask.ParentId__c);
                }
                else {
                    failureMap.put(intTask.Id, 'Error: invalid ParentId on Integration Task');
                }
            }
            if(projIdList.size()>0)
            {
                 List<Project__c> projIds=TVE_IntegUtility.getProject(projIdList);
                
                for(Project__c proj:projIds)
                	projectInfoMap.put(proj.id,proj);
           }
             for(Integration_Task__c iTask: lstIntgTask)
            {
                projRecord = new project__c();
                projRecord = projectInfoMap.get(iTask.ParentId__c);
                response=TVE_SAP_Int_APICalls.callCMUpdateReq(projRecord,apiCallHea);
               // System.debug('Response status message'+response.statusMessage);
               if(response!=null)
               {
                if(response.statusMessage=='No Content')
                   successMap.put(iTask.id,'success');
                else
                {
                    if(response.payloadUpCM!=null)
                	failureMap.put(iTask.id,response.statusMessage+response.payloadUpCM);
                    else
                        failureMap.put(iTask.id,response.statusMessage);
                }
               }
            }

            for (Integration_Task__c task : lstIntgTask) {
                if(!successMap.containsKey(task.Id) && !failureMap.containsKey(task.Id)) {
                    failureMap.put(task.Id,'Error: Integration Task could not proceed');
                }
            }
            if(successMap.size()>0)
            {
                    updateIntTaskMap.put('Status__c','Successful');
                    createIntglogmapS.put('Status__c','Successful');

                TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
                TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
                            
            }
            if(FailureMap.size()>0)
            {
                updateIntTaskMapFail.put('Status__c','Failed');
                
                createIntglogmapF.put('Status__c','Failed');
                
                TVE_IntegUtility.UpdateInteTask(FailureMap,updateIntTaskMapFail);
                TVE_IntegUtility.createIntegLog(FailureMap,createIntglogmapF);
            }
        }
        
        lstIntgTask=TVE_IntegUtility.getIntegrationTask( 'Update','Project__c','UpdateCM','In Progress');
        if(!lstIntgTask.isEmpty()){
            TVE_SAPInteg_UpdateCMQue updateCM = new TVE_SAPInteg_UpdateCMQue();
                        ID jobID = System.enqueueJob(updateCM);  
        }
    }
}