force-app/main/default/objects/API_Callout_Headers__mdt/API_Callout_Headers__mdt.object-meta.xml
<CustomObject>
    <label>API Callout Headers</label>
    <pluralLabel>API Callout Header</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/endpoint__c.field-meta.xml
<CustomField>
    <fullName>endpoint__c</fullName>
    <label>endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/sourceSystem__c.field-meta.xml
<CustomField>
    <fullName>sourceSystem__c</fullName>
    <label>sourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/targetSystem__c.field-meta.xml
<CustomField>
    <fullName>targetSystem__c</fullName>
    <label>targetSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/CMnumber__c.field-meta.xml
<CustomField>
    <fullName>CMnumber__c</fullName>
    <label>CM number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Number__c</fullName>
    <externalId>true</externalId>
    <label>Notification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CMNumber__c.field-meta.xml
<CustomField>
    <fullName>CMNumber__c</fullName>
    <externalId>true</externalId>
    <label>CM Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectAssignee__c.field-meta.xml
<CustomField>
    <fullName>ProjectAssignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Assignee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Project Assignee must have &quot;DER TVE-11 Unified User&quot; or &quot;TVE-11 AST Standard User&quot; profile</errorMessage>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>DER TVE-11 Unified User, TVE-11 AST Standard User, DSP User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>ProjectsAssigned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/TVE_Integration_Constants__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TVE Integration Constants</label>
</CustomObject>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Assembly__c.field-meta.xml
<CustomField>
    <fullName>Assembly__c</fullName>
    <label>Assembly</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Integration_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Method_Name__c</fullName>
    <label>Integration Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/MessageID__c.field-meta.xml
<CustomField>
    <fullName>MessageID__c</fullName>
    <label>MessageID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Partner_Role_1__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role_1__c</fullName>
    <label>Partner Role 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_Integration_Constants__c/fields/Partner_Role_2__c.field-meta.xml
<CustomField>
    <fullName>Partner_Role_2__c</fullName>
    <label>Partner Role 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <description>Valid values for testing are: 10000868 and 10002255</description>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_CreateMasterNoti.cls
public without sharing class TVE_SAPInteg_CreateMasterNoti implements Queueable,Database.AllowsCallouts
{
    List<Integration_Task__c> lstIntgTask = new  List<Integration_Task__c>();
    public void execute(QueueableContext qc)
    {
        Map<Id,String> successMap = new Map<Id,String>();
        Map<Id,String> failureMap = new Map<Id,String>();
        Map<Id,String> oppNotinumberMap = new Map<Id,String>();
        Map<Id,Id> oppIdToProjIdMap = new Map<Id,Id>();
        Map<Id,Id> projIdToTaskIdMap = new Map<Id,Id>();
        List<Id> projIdList = new List<id>();
        Map<Id,Project__c> projectInfoMap = new Map<Id,Project__c>();
        Map<Id,Opportunity> projOppMap = new Map<Id,Opportunity>();
        Map<Id,Map<String,string>> BillToSoldToMap = new Map<id,Map<String,string>>();
        Project__c projRecord;
        Opportunity oppRecord;
        Map<String,String> BtStMap;
        String SoldTo;
        TVE_SAP_Int_APICalls.NotiResponse response;
        Map<String,String> creatIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMapfail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();
        API_Callout_Headers__mdt apiCallHea = new  API_Callout_Headers__mdt();
        TVE_SAP_Int_APICalls.PartnerResponse PRAG; 
        TVE_SAP_Int_APICalls.PartnerResponse PRVW;
        API_Callout_Headers__mdt UpdateNotificationPartner= [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                                             objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                                             WHERE DeveloperName ='PartnerAG_VW_Callout' ];
        
        TVE_Integration_Constants__c intConstant = [select Integration_Method_Name__c,Assembly__c,Partner_Role_1__c,Partner_Role_2__c,MessageID__c
                                                    from TVE_Integration_Constants__c 
                                                    where Integration_Method_Name__c='TVE_SAPInteg_CreateMasterNoti' limit 1];//TVE_Integration_Constants__c.getall().values();
        
        System.debug('callSAPreq');
        
        lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Create','Project__c','CreateMasterNoti','In Progress');
        if(!lstIntgTask.isEmpty()){
            System.debug('callSAPreq eexecute'+lstIntgTask.size());
            for(Integration_Task__c intTask: lstIntgTask)
            {
                projIdList.add(intTask.ParentId__c);
                projIdToTaskIdMap.put(intTask.ParentId__c, intTask.Id);
            }
            if(projIdList.size()>0)
            {
                BillToSoldToMap=TVE_IntegUtility.getSoldToBillTO(projIdList);
                
                List<Project__c> lstProjects=TVE_IntegUtility.getProject(projIdList);
                
                for(Project__c proj:lstProjects){
                    projectInfoMap.put(proj.id,proj);
                }
                
                for(Opportunity opp:[select id,Notification_Number__c,Notification_Type__c,Project__c,System_Status__c
                                     from Opportunity where Project__c IN:projIdList and Type='Design']){
                    projOppMap.put(opp.Project__c,opp);
                    oppIdToProjIdMap.put(opp.Id, opp.Project__c);
                }
            }
            for(Integration_Task__c iTask: lstIntgTask)
            {
                if(projectInfoMap.containsKey(iTask.ParentId__c) && projOppMap.containsKey(iTask.ParentId__c)){
                    projRecord = projectInfoMap.get(iTask.ParentId__c);
                    oppRecord = projOppMap.get(iTask.ParentId__c);
                    
                    BtStMap = BillToSoldToMap.get(iTask.ParentId__c);
                    System.debug('BtStMap333333'+BtStMap);
                    if(BtStMap!=null && BtStMap.size()>0)
                    {
                        if(BtStMap.containsKey('SoldTo'))
                            SoldTo = BtStMap.get('SoldTo');
                    }
                    if(projRecord.CMNumber__c==null){
                        apiCallHea = [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                      objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                      WHERE DeveloperName ='CreateMasterNoti_Callout' ];
                        
                        response=TVE_SAP_Int_APICalls.callCreateNotireq(projRecord,oppRecord,
                                                                        SoldTo,intConstant,apiCallHea,false,'');
                        
                        if(response.isSuccess==false){
                            failureMap.put(iTask.id,response.errorMessage);
                        }else{
                            oppNotinumberMap.put(projOppMap.get(iTask.ParentId__c).Id,response.notiNumber);
                        }
                    }
                    else{
                        apiCallHea = [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                      objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                      WHERE DeveloperName ='UpdateMasterNoti_Callout'];
                        
                        TVE_IntegUtility.ConstMeasureWrapper CMWrapper=TVE_IntegUtility.getConstMeasureSet(projRecord.CMNumber__c);
                        if(CMWrapper.cmset!=null){
                            response=TVE_SAP_Int_APICalls.callCreateNotireq(projRecord,oppRecord,
                                                                            SoldTo,intConstant,apiCallHea,true,CMWrapper.cmset.Qmnum__c);
                            if(response.isSuccess==false){
                                failureMap.put(iTask.id,response.errorMessage);
                            }else{
                                PRAG=TVE_SAP_Int_APICalls.callPartnerAG_VW(UpdateNotificationPartner,response.notiNumber,projRecord.id,SoldTo,'AG');
                                if(PRAG.status.startsWith('2')){
                                    PRVW=TVE_SAP_Int_APICalls.callPartnerAG_VW(UpdateNotificationPartner,
                                                                               response.notiNumber,
                                                                               projRecord.id,
                                                                               projRecord.ProjectAssignee__r.Employee_ID__c,
                                                                               'VW');
                                    if(PRVW.status.startsWith('2')){
                                        oppNotinumberMap.put(projOppMap.get(iTask.ParentId__c).Id,response.notiNumber);
                                    }else{
                                        failureMap.put(iTask.id,PRVW.statusMessage);
                                    }
                                }else{
                                    failureMap.put(iTask.id,PRAG.statusMessage);
                                }
                            }
                        }else{
                            failureMap.put(iTask.id,CMWrapper.errorMessage);
                        }
                    }
                } else {
                    failureMap.put(iTask.id, 'Error: Cannot find the related Project or Opportunity record.');
                }
            }
            
            if(!oppNotinumberMap.isEmpty()){
                List<Id> oppIds = new List<Id>(oppNotinumberMap.keySet());
                List<Database.SaveResult> srList = TVE_IntegUtility.updateOpp(oppIds, oppNotinumberMap);
                for(Integer i = 0; i < srList.size(); i++) {
                    Database.SaveResult sr = srList.get(i);
                    if (!sr.isSuccess()) {
                        List<String> errorMsg = new List<String>();
                        for(Database.Error err : sr.getErrors()) {
                            errorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
                        }
                        failureMap.put(projIdToTaskIdMap.get(oppIdToProjIdMap.get(oppIds.get(i))), 'Error on Opportunity update: ' + String.join(errorMsg, '\r\n'));
                    }
                }
            }
            
            for(Integration_Task__c iTask: lstIntgTask){
                if(!failureMap.containsKey(iTask.Id)){
                    successMap.put(iTask.id,iTask.ParentId__c);
                }
            }
            
            if(successMap.size()>0){
                creatIntTaskMap.put('SObject__c','Project__c');
                creatIntTaskMap.put('Type__c','CreateWork');
                creatIntTaskMap.put('Status__c','In Progress');
                creatIntTaskMap.put('Operation__c','Create');
                
                updateIntTaskMap.put('Status__c','Successful');
                createIntglogmapS.put('Status__c','Successful');
                
                
                TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
                TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
                TVE_IntegUtility.CreateInteTask(successMap,creatIntTaskMap);
            }
            
            if(failureMap.size()>0){
                updateIntTaskMapFail.put('Status__c','Failed');
                createIntglogmapF.put('Status__c','Failed');
                
                TVE_IntegUtility.UpdateInteTask(failureMap,updateIntTaskMapFail);
                TVE_IntegUtility.createIntegLog(failureMap,createIntglogmapF);
            }
        }
            
        lstIntgTask=TVE_IntegUtility.getIntegrationTask( 'Create','Project__c','CreateMasterNoti','In Progress');
        if(!Test.isRunningTest()){
            if(!lstIntgTask.isEmpty()){
                TVE_SAPInteg_CreateMasterNoti createMasterNoti = new TVE_SAPInteg_CreateMasterNoti();
                Id jobID = System.enqueueJob(createMasterNoti);  
            }else{
                TVE_SAPInteg_CreateWork createWork = new TVE_SAPInteg_CreateWork();
                // enqueue the job for processing
                Id jobID = System.enqueueJob(createWork);
            } 
        }
    }
}