force-app/main/default/objects/API_Callout_Headers__mdt/API_Callout_Headers__mdt.object-meta.xml
<CustomObject>
    <label>API Callout Headers</label>
    <pluralLabel>API Callout Header</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/endpoint__c.field-meta.xml
<CustomField>
    <fullName>endpoint__c</fullName>
    <label>endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/sourceSystem__c.field-meta.xml
<CustomField>
    <fullName>sourceSystem__c</fullName>
    <label>sourceSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Headers__mdt/fields/targetSystem__c.field-meta.xml
<CustomField>
    <fullName>targetSystem__c</fullName>
    <label>targetSystem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/TVE_File_Classification_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>TVE File Classification Mapping</label>
    <pluralLabel>TVE File Classification Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
                <default>true</default>
                <label>Prelim Estimate</label>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_File_Classification_Mapping__mdt/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>DocumentType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TVE_File_ext_Mapping__c/TVE_File_ext_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TVE File ext Mapping</label>
</CustomObject>

force-app/main/default/classes/TVE_SAPInt_CreateArtefact.cls
public without sharing class TVE_SAPInt_CreateArtefact implements Queueable,Database.AllowsCallouts{
    
    List<Integration_Task__c> lstIntgTask = new  List<Integration_Task__c>();
    public void execute(QueueableContext qc)
    {
        List<id> ArtefactIdList = new List<id>();
        Map<id,Artefact__c> artefactMap = new Map<id,Artefact__c>();
        Map<id,ContentVersion> artCVMap = new Map<id,ContentVersion>();
        TVE_CreateCMArtResponse CAW;
        Map<id,String> successMap = new Map<Id,String>();
        Map<id,String> failureMap = new Map<Id,String>();
        Map<String,String> creatIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
         Map<String,String> updateIntTaskMapfail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();
        Map<String,String> CMMap = new Map<String,String>();
        Map<String,String> artDocIdMap = new Map<String,String>();
        Map<String,String> fileextMap = new Map<String,String>();
        
        API_Callout_Headers__mdt apiCallHea = [SELECT key__c, sourceSystem__c, targetSystem__c, 
                                  objectName__c, endpoint__c FROM API_Callout_Headers__mdt 
                                  WHERE DeveloperName ='Create_Attachment_Callout' ];
         List<TVE_File_Classification_Mapping__mdt> classificationMapping = [SELECT DeveloperName,Classification__c,documenttype__c
                                                                       FROM TVE_File_Classification_Mapping__mdt  ];
        for(TVE_File_Classification_Mapping__mdt cm:classificationMapping)
            CMMap.put(cm.Classification__c,cm.documenttype__c);
        
        List<TVE_File_ext_Mapping__c> fileExt =[select name,Type__c from 	TVE_File_ext_Mapping__c];
        for(TVE_File_ext_Mapping__c FE : fileExt)
            fileextMap.put(FE.name,FE.Type__c);
        
        //get Integration task
        lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Create','Artefact__c','CreateArtefact','In Progress');
        System.debug('lstIntgTask in main class'+lstIntgTask);
        if(!lstIntgTask.isEmpty()){
            for(Integration_Task__c intTask: lstIntgTask)
            {
                Boolean checkId = (intTask.ParentId__c InstanceOf Id);
                if(checkId)
                {
                    ArtefactIdList.add(intTask.ParentId__c);
                }
                else {
                    failureMap.put(intTask.Id, 'Error: invalid ParentId on Integration Task');
                }
            }
            if(ArtefactIdList.size()>0)
            {
                artefactMap=TVE_IntegUtility.getArtefact(ArtefactIdList);
                artCVMap=TVE_IntegUtility.getContentVersion(ArtefactIdList);
            }
        }
        
        for(Integration_Task__c iTask: lstIntgTask){
            Artefact__c artTemp = artefactMap.get(iTask.ParentId__c);
            CAW=TVE_SAP_Int_APICalls.callCreateAttachment(artefactMap.get(iTask.ParentId__c),artCVMap.get(iTask.ParentId__c),apiCallHea,CMMap.get(artTemp.Classification__c),fileextMap);
            //System.debug('CAW.payloadAW'+CAW.payload.d.ArcDocId);
            if(CAW.status.startsWith('2')){
                successMap.put(iTask.id,iTask.ParentId__c);
                if(CAW.payload!=null)
                	artDocIdMap.put(iTask.ParentId__c,CAW.payload.d.ArcDocId);
            }
            else
                failureMap.put(iTask.id,CAW.statusMessage);
        }

        for (Integration_Task__c task : lstIntgTask) {
            if(!successMap.containsKey(task.Id) && !failureMap.containsKey(task.Id)) {
                failureMap.put(task.Id,'Error: Integration Task could not proceed');
            }
        }

         if(successMap.size()>0)
        {
             updateIntTaskMap.put('Status__c','Successful');
             createIntglogmapS.put('Status__c','Successful');

            TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
            TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
                      
        }
        if(FailureMap.size()>0)
        {
            updateIntTaskMapFail.put('Status__c','Failed');
            
            createIntglogmapF.put('Status__c','Failed');
            
            TVE_IntegUtility.UpdateInteTask(FailureMap,updateIntTaskMapFail);
            TVE_IntegUtility.createIntegLog(FailureMap,createIntglogmapF);
        }
        if(artDocIdMap.size()>0)
            TVE_IntegUtility.updateArcID(artDocIdMap);
        lstIntgTask=TVE_IntegUtility.getIntegrationTask('Create','Artefact__c','CreateArtefact','In Progress');
        System.debug('lstIntgTask in create Artefact'+lstIntgTask.size());
        if(!lstIntgTask.isEmpty()){
            TVE_SAPInt_CreateArtefact createArte = new TVE_SAPInt_CreateArtefact();
             if(!Test.isRunningTest())
                 ID jobID = System.enqueueJob(createArte);  
        }
    }
    

}