force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Notification_Number__c.field-meta.xml
<CustomField>
    <fullName>Notification_Number__c</fullName>
    <externalId>true</externalId>
    <label>Notification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Required_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_End_Date__c</fullName>
    <label>Required End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <label>System Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMNotificationSets__x/PMNotificationSets__x.object-meta.xml
<CustomObject>
    <description>PMNotificationSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>PMNotificationSets</externalName>
    <label>PMNotificationSets</label>
    <pluralLabel>PMNotificationSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMNotificationSets__x/fields/NotificationNumber__c.field-meta.xml
<CustomField>
    <fullName>NotificationNumber__c</fullName>
    <description>NotificationNumber</description>
    <externalDeveloperName>NotificationNumber</externalDeveloperName>
    <label>NotificationNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMNotificationSets__x/fields/RequiredEndDate__c.field-meta.xml
<CustomField>
    <fullName>RequiredEndDate__c</fullName>
    <description>RequiredEndDate</description>
    <externalDeveloperName>RequiredEndDate</externalDeveloperName>
    <label>RequiredEndDate</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMNotificationSets__x/fields/SystemStatus__c.field-meta.xml
<CustomField>
    <fullName>SystemStatus__c</fullName>
    <description>SystemStatus</description>
    <externalDeveloperName>SystemStatus</externalDeveloperName>
    <label>SystemStatus</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_GetNotificationToSAP.cls
/*
  @author  : harshad.kumbhar@ausnetservices.com.au
  @created : 06 Mar 2020
  @Description : Class for Get Notification to SAP system
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/

public without sharing class TVE_SAPInteg_GetNotificationToSAP implements Queueable {
    
    @TestVisible private static List<PMNotificationSets__x> mockedExtPMNoti = new List<PMNotificationSets__x>();    
    
    private static final String CREATECUST_CALLOUT = 'GetConstNoti';
    
    public void execute(QueueableContext qc)
    {        
        List<Integration_Task__c> lstIntgTask = TVE_IntegUtility.getIntegrationTask( 'Get','Opportunity','GetConstNoti','In Progress');
		System.debug('Integration Task : ' + lstIntgTask);
      
        Boolean queryException = false;
        List<Opportunity> OppToUpdate = new List<Opportunity>();

        Map<Id, Id> parentToTask = new Map<Id, Id>();
        Map<String,Opportunity> oldmapOpp = new Map<String,Opportunity>();
        Map<String,Opportunity> newmapOpp = new Map<String,Opportunity>();

        Map<Id,String> successMap = new Map<Id,String>();
        Map<Id,String> failureMap = new Map<Id,String>();
        Map<String,String> updateIntTaskMap = new Map<String,String>();
        Map<String,String> updateIntTaskMapFail = new Map<String,String>();
        Map<String,String> createIntglogmapS = new Map<String,String>();
        Map<String,String> createIntglogmapF = new Map<String,String>();

        for(Integration_Task__c item: lstIntgTask)
        {
            Boolean checkId = (item.ParentId__c InstanceOf Id);
            if(checkId)
            { 
                parentToTask.put(item.ParentId__c, item.Id);
            }
            else {
                failureMap.put(item.Id, 'Error: invalid ParentId on Integration Task');
            }
        }

          
        try {
            List<Opportunity> lstOpp = [SELECT Id,Notification_Number__c,System_Status__c, Project__c,Required_End_Date__c
                                     FROM Opportunity WHERE Id in: parentToTask.keySet()];
            for(Opportunity opp : lstOpp) {
                oldmapOpp.put(opp.Notification_Number__c,opp);
            }
            newmapOpp = getOpportunities(oldmapOpp);
        } catch (Exception e) {
            queryException = true;
            //Fail all Integration_Task__c
            for(Integration_Task__c task : lstIntgTask) {
                failureMap.put(task.Id, e.getMessage());
            }
        }
        
        if(!queryException) {
            for(String extId : oldmapOpp.keySet()) {
                if(newmapOpp.containsKey(extId)) {
                    //Compare newmapWorkOrder with oldmapWorkOrder
                    Opportunity newOpp = newmapOpp.get(extId);
                    Opportunity oldOpp = oldmapOpp.get(extId);
                
                    if(newOpp.Required_End_Date__c == oldOpp.Required_End_Date__c && newOpp.System_Status__c == oldOpp.System_Status__c) {
                        //If no changes are required, set Integration_Task__c successful
                        successMap.put(parentToTask.get(newOpp.Id), newOpp.Id);
                    } else {
                        //To update
                        OppToUpdate.add(newOpp);
                    }
                } else {
                    //OrderNumber not found in SAP
                    failureMap.put(parentToTask.get(oldmapOpp.get(extId).Id), 'Notification Number not found in SAP');
                }
            }
        
            if(!OppToUpdate.isEmpty()) {
                List<Database.SaveResult> lstSR = Database.update(OppToUpdate, false);
                for(Database.SaveResult res : lstSR) {
                    if (res.isSuccess()) {
                        successMap.put(parentToTask.get(res.getId()), res.getId());
                    } else {
                        List<String> errorMsg = new List<String>();
                        for(Database.Error err : res.getErrors()) {
                            errorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
                        }
                        failureMap.put(parentToTask.get(res.getId()), String.join(errorMsg, '\r\n'));
                    }
                }
            }
        }
        for (Integration_Task__c task : lstIntgTask) {
            if(!successMap.containsKey(task.Id) && !failureMap.containsKey(task.Id)) {
                failureMap.put(task.Id,'Error: Integration Task could not proceed');
            }
        }
        if(!successMap.isEmpty()) {
            updateIntTaskMap.put('Status__c','Successful');
            createIntglogmapS.put('Status__c','Successful');
                
            TVE_IntegUtility.UpdateInteTask(successMap,updateIntTaskMap);
            TVE_IntegUtility.createIntegLog(successMap,createIntglogmapS);
        }
        if(!failureMap.isEmpty()) {
            updateIntTaskMapFail.put('Status__c','Failed');
            createIntglogmapF.put('Status__c','Failed');
                
            TVE_IntegUtility.UpdateInteTask(failureMap,updateIntTaskMapFail);
            TVE_IntegUtility.createIntegLog(failureMap,createIntglogmapF);
        }

        lstIntgTask=TVE_IntegUtility.getIntegrationTask( 'Get','Opportunity','GetConstNoti','In Progress');
        if(!lstIntgTask.isEmpty()){
            TVE_SAPInteg_GetNotificationToSAP getNoti = new TVE_SAPInteg_GetNotificationToSAP();
                        ID jobID = System.enqueueJob(getNoti);  
        }

    }
    public static Map<String,Opportunity> getOpportunities(Map<String,Opportunity> oldmapOpp)
    {
        List<PMNotificationSets__x> lstPMNoti = new List<PMNotificationSets__x>(); 
        Map<String, Opportunity> newmapOpp = new Map<String, Opportunity>();      
       
        if(Test.isRunningTest())
        {
            lstPMNoti = (mockedExtPMNoti.size() > 0) ? mockedExtPMNoti : lstPMNoti; 
        }
        else {
            lstPMNoti = TVE_IntegUtility.GetPMNoti(oldmapOpp.keySet());
        }       
    
        for (PMNotificationSets__x opp : lstPMNoti) {     
            Opportunity newItem = new Opportunity(
                Id = oldmapOpp.get(opp.NotificationNumber__c).Id
            );

            if(String.isNotBlank(opp.RequiredEndDate__c))
            {
                newItem.Required_End_Date__c =  TVE_IntegUtility.dateConversionSAPtoSF(opp.RequiredEndDate__c);                               
            }
            if(String.isNotBlank(opp.SystemStatus__c))
            {   
                newItem.System_Status__c = opp.SystemStatus__c;
            }        
            newmapOpp.put(opp.NotificationNumber__c, newItem);       
        }
       
        return newmapOpp;
    }
}