force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Artefact.recordType-meta.xml
<RecordType>
    <fullName>Artefact</fullName>
    <active>true</active>
    <label>Artefact</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/WorkOrder.recordType-meta.xml
<RecordType>
    <fullName>WorkOrder</fullName>
    <active>true</active>
    <label>WorkOrder</label>
</RecordType>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tveERPIntTest.cls
/*
@author  : Lakshay Sharma <Lakshay.Sharma@ausnetservices.com.au>
@created : 11th Feb 2020
@Description :Test class for Controller class of LWC component tveERPIntegrationAppPage
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------
*/
@isTest
public class tveERPIntTest {
     public static final string testUserEmail = 'testuser@TVEIntegInitiationControllerTest.com';
    public static ID intTask_arte_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('Artefact').getRecordTypeId();
    public static ID intTask_opp_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('Opportunity').getRecordTypeId();
    public static ID intTask_workord_Id = Schema.SObjectType.Integration_Task__c.getRecordTypeInfosByName().get('WorkOrder').getRecordTypeId();

    @testSetup
    public static void setup() {
        Integration_Task__c intTask=new Integration_Task__c();
        intTask.Status__c='In Progress';
        intTask.Type__c	='CreateCustomer';
        
        insert intTask;
                Integration_Task__c intTask4=new Integration_Task__c();
        intTask.Status__c='Ready';
        intTask4.Type__c	='CreateCustomer';
        insert intTask4;
        
        Integration_Task__c intTask2=new Integration_Task__c();
        intTask2.Status__c='In Progress';
        intTask2.Type__c ='GetInvoice';
        intTask2.RecordTypeID=intTask_arte_Id;
        insert intTask2;
        
        Integration_Task__c intTask3=new Integration_Task__c();
        intTask3.Status__c='In Progress';
        intTask3.Type__c='UpdateCM';
        insert intTask3;
    }
    @isTest
    public static void testtveERPIntchecklist(){
        List<Integration_Task__c> intlist = [SELECT Id,Status__c  FROM Integration_Task__c WHERE Status__c='In Progress'];
        test.startTest();
        tveERPInt.tveERPIntchecklist();
        test.stopTest();
    }
    @isTest
    public static void testQueueableApex(){
        User testUser = TVE_TestUtility.createTestUser(testUserEmail);
        insert testUser;
		
        PermissionSet psa = [SELECT Id FROM PermissionSet WHERE Name = 'Execute_SAP_Integration'];
        insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = psa.Id);
        
         List<Integration_task__c> listintTask=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='In Progress'];
        List<Integration_task__c> listintTask2=[SELECT Id, Status__c,Type__c FROM Integration_Task__c
                                                                                   WHERE Status__c ='Ready'];
        System.runAs(testUser){
        test.startTest();
        tveERPInt.callqueueableapex();
        test.stopTest();
        }
    
}
}