force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN - DER</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELE - CINCL</fullName>
            </value>
            <value>
                <fullName>ELE - DER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>CustomerCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>The Invoice Number from ERP</description>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Offer_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Accepted_Date__c</fullName>
    <description>Email merge field</description>
    <label>Offer Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Offer_Made_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Made_Date__c</fullName>
    <label>Offer Made Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Representative__c.field-meta.xml
<CustomField>
    <fullName>Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representative</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Error: Cannot select a Person Account for this field</errorMessage>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Representative)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Responsible_Party__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Party__c</fullName>
    <description>Selection of who the Responsible Party is. This determines who the invoice will be sent to.</description>
    <label>Responsible Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installer</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Representative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Connection Points</relationshipLabel>
    <relationshipName>Connection_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELE - CINCL</fullName>
            </value>
            <value>
                <fullName>ELE - DER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/DER_Agreement__c.object-meta.xml
<CustomObject>
    <label>DER Agreement</label>
    <nameField>
        <displayFormat>Agmt-{0000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Offer_Made_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Made_Date__c</fullName>
    <label>Offer Made Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Offer_Type__c.field-meta.xml
<CustomField>
    <fullName>Offer_Type__c</fullName>
    <label>Offer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic Micro EG MSO</fullName>
            </value>
            <value>
                <fullName>Negotiated 0-5MW</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA&amp;NMA</fullName>
            </value>
            <value>
                <fullName>Negotiated &gt;5MW NEA</fullName>
            </value>
            <value>
                <fullName>Flexible &lt;30kW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Contract Active</fullName>
            </value>
            <value>
                <fullName>Contract Completed</fullName>
            </value>
            <value>
                <fullName>Contract Unauthorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Sub_Type__c</fullName>
    <description>Identifies the generation type for the equipment</description>
    <label>AC Equipment Sub-Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Fossil</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Biomass/Waste</fullName>
            </value>
            <value>
                <fullName>Geothermal</fullName>
            </value>
            <value>
                <fullName>Co- / Tri-generation</fullName>
            </value>
            <value>
                <fullName>Bio Gas</fullName>
            </value>
            <value>
                <fullName>Coal</fullName>
            </value>
            <value>
                <fullName>Electric Car</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Tidal</fullName>
            </value>
            <value>
                <fullName>Wave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Parent_Device__c.field-meta.xml
<CustomField>
    <fullName>Parent_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/recordTypes/Device_L2.recordType-meta.xml
<RecordType>
    <fullName>Device_L2</fullName>
    <active>true</active>
    <label>AC Equipment - L2</label>
</RecordType>

force-app/main/default/objects/Device__c/recordTypes/Device_L3.recordType-meta.xml
<RecordType>
    <fullName>Device_L3</fullName>
    <active>true</active>
    <label>DER Device - L3</label>
</RecordType>

force-app/main/default/objects/MeterDataSets__x/MeterDataSets__x.object-meta.xml
<CustomObject>
    <description>MeterDataSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>MeterDataSets</externalName>
    <label>MeterDataSets</label>
    <pluralLabel>MeterDataSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/MeterDataSets__x/fields/Nmi__c.field-meta.xml
<CustomField>
    <fullName>Nmi__c</fullName>
    <description>Nmi</description>
    <externalDeveloperName>Nmi</externalDeveloperName>
    <label>Nmi</label>
    <length>128</length>
    <referenceTargetField>Connection_Point__c.NMI__c</referenceTargetField>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>MeterDataSets</relationshipLabel>
    <relationshipName>MeterDataSets</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/classes/DER_TestUtility.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 04 Sep 2019
  @Description : Utility Test class
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/
@isTest
public class DER_TestUtility {
    public static String L2_Device_RT = 'Device_L2';
    public static String L3_Device_RT = 'Device_L3';

    public static Account createPersonAccount(String acctName, String emailAddr) {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(DER_REST_Application_v1.ACCOUNT_RECORDTYPE_INDIVIDUAL).getRecordTypeId();
        return new Account(
            LastName = acctName,
            RecordTypeId = acctRTId,
            PersonEmail = emailAddr,
            ABN__c = getUniqueABN());
    }

    public static Account createBusinessAccount(String acctName) {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(DER_REST_Application_v1.ACCOUNT_RECORDTYPE_SERVICEPROVIDER).getRecordTypeId();
        return new Account(
            Name = acctName,
            RecordTypeId = acctRTId,
            Customer_Type__c = 'ELE - DER',
            ABN__c = getUniqueABN());
    }
    public static String getUniqueABN(){
        String returnValue;
        returnValue = String.valueOf(Math.round((Math.random() * (900000) + 1000000000)));
		return returnValue;
	}

    public static Contact createBusinessAccountContact(Id businessAccId, String firstName, String lastName, String email){
        return new Contact(
            FirstName = firstName,
            LastName = lastName,
            Email = email,
            AccountId = businessAccId
        );
    }    

    public static Case createCaseForInstaller(String recordTypeDeveloperName, String status, String origin, 
                                              String priority, Id installerId, Id installerContactId) {
        Id caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        return new Case(
            Status = status,
            RecordTypeId = caseRTId,
            Origin = origin,
            Priority = priority,
            AccountId = installerId,
            ContactId = installerContactId,
            Invoice_Number__c = '12345');
    }

    
    public static Case createCaseForCustomer(Id derAppId, String recordTypeDeveloperName, String status, String origin, 
                                             String priority, Id customerId) {
        Id caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        return new Case(
            DER_Application__c = derAppId, 
            Status = status,
            RecordTypeId = caseRTId,
            Origin = origin,
            Priority = priority,
            Customer__c = customerId,
            Invoice_Number__c = '12345'
        );
    }
    
    public static Case createCaseForDerGetMethod(Id derAppId, String recordTypeDeveloperName, String status, String origin, 
                                              String priority, Id installerId, Id installerContactId,Id customerId) {
        Id caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        return new Case(
            DER_Application__c = derAppId, 
            Status = status,
            RecordTypeId = caseRTId,
            Origin = origin,
            Priority = priority,
            AccountId = installerId,
            ContactId = installerContactId,
            Customer__c = customerId,
            Invoice_Number__c = '12345');
    }

    public static Case createCaseWith_Installer_Customer_Rep(Id derAppId, 
                                                            String recordTypeDeveloperName, 
                                                            String status, String origin, String priority, 
                                                            Id installerId, Id installerContactId,
                                                            Id customerId, Id repId, 
                                                            String applicantType, String respParty) {

        Id caseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        return new Case(
            DER_Application__c = derAppId, 
            Status = status,
            RecordTypeId = caseRTId,
            Origin = origin,
            Priority = priority,
            AccountId = installerId,
            ContactId = installerContactId,
            Customer__c = customerId,
            Representative__c = repId,
            Applicant_Type__c = applicantType,
            Responsible_Party__c = respParty,
            Invoice_Number__c = '12345');
    }

    public static Connection_Point__c createConnectionPoint(Id accountId) {
        return new Connection_Point__c(
            Account__c = accountId,
            NMI__c = '12345'
        );
    }

    public static DER_Application__c createDERApplication (Id connectionPointId){
        return new DER_Application__c(
            NMI__c = connectionPointId
        );
    }
    public static Device__C createDevice (Id derApplicationId){
        return new Device__c(
            DER_Application__c = derApplicationId,
            AC_Equip_Type__c = 'Inverter',
            AC_Equip_Sub_Type__c = 'Solar'
          
        );
    }

    public static Device__C createDevice_L2 (Id derApplicationId){
        Id L2_Device_RTId = Schema.SObjectType.Device__c.getRecordTypeInfosByDeveloperName().get(L2_Device_RT).getRecordTypeId();
        return new Device__c(
            DER_Application__c = derApplicationId,
            RecordTypeId = L2_Device_RTId,
            AC_Equip_Type__c = 'Inverter',
            AC_Equip_Sub_Type__c = 'Solar'
        
        );        
    }
    
    public static Device__C createDevice_L3 (Id deviceL2Id){
        Id L3_Device_RTId = Schema.SObjectType.Device__c.getRecordTypeInfosByDeveloperName().get(L3_Device_RT).getRecordTypeId();
        return new Device__c(
            Parent_Device__c = deviceL2Id,
            RecordTypeId = L3_Device_RTId,
            AC_Equip_Type__c = 'Inverter',
            AC_Equip_Sub_Type__c = 'Solar'
        );        
    }

    public static DER_Agreement__c createAgreement(Id derAppId, Id installerAccId, String agmtStatus, 
                                                    Date offerAccptDate, Date offerMadeDate, String offerType){
        return new DER_Agreement__c(
            DER_Application__c = derAppId,
            Account__c = installerAccId,
            Status__c = agmtStatus,
            Offer_Accepted_Date__c = offerAccptDate,
            Offer_Made_Date__c = offerMadeDate,
            Offer_Type__c = offerType,
            Contract_Active_Date__c = offerAccptDate,
            Offer_Version__c ='0.0'
        );
    }

    public static NmiDataSets__x createEXTNMI(String nmiNumber){
        return new NmiDataSets__x(            
            ExternalId = nmiNumber,
            Nmi__c = nmiNumber
        );
    }

    public static MeterDataSets__x createEXTMtr(String nmiNumber, String serialNum, String typeCode){
        return new MeterDataSets__x(            
            ExternalId = nmiNumber,
            SerialNumber__c = serialNum,
            InstallTypeCode__c = typeCode
        );
    }

    public static User createTestUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        System.assert(p != null, 'Profile not found.');

        return new User(
            ProfileId = p.Id,
            LastName = 'Doe',
            Email = 'testuser@fnptest.com',
            Username = 'testuser@fnptest.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
    }
    
    // ------------------------------------------------------------- //
    // -------------- Data setup for DER Application --------------- //
    // ------------------------------------------------------------ //
        
    public static Id loadDERAppRecords(String customerEmail, String installerEmail, String repEmail){

        //Create Individual Account
        Account testCustomer = DER_TestUtility.createPersonAccount('Person Account', customerEmail);
        insert testCustomer;        
        
        //Create Connection Point
        Connection_Point__c testConnectionPoint = DER_TestUtility.createConnectionPoint(testCustomer.Id);
        Insert testConnectionPoint;
        
        DER_Application__c testDERApp = DER_TestUtility.createDERApplication(testConnectionPoint.Id);
        Insert testDERApp;
        
        //Create Business Account
        Account testInstaller = DER_TestUtility.createBusinessAccount('Business Account');
        insert testInstaller;
        
        //Create Business Account's Contact
        Contact testInstallerContact = DER_TestUtility.createBusinessAccountContact(testInstaller.Id, 'Test', 'Installer', installerEmail);
        insert testInstallerContact;
        
        //Create Business Account
        Account testRepAcc = DER_TestUtility.createBusinessAccount('Representative Business Account');
        insert testRepAcc;
        
        //Create Business Account's Contact
        Contact testRep = DER_TestUtility.createBusinessAccountContact(testInstaller.Id, 'Test', 'Representative', repEmail);
        insert testRep;

        //Create case with customer, installer & representative
        Case testCase = DER_TestUtility.createCaseWith_Installer_Customer_Rep(testDERApp.Id,
                                                                         DER_REST_Application_v1.CASE_RECORDTYPE_AUTO, 
                                                                         'New', 'Email', 'Medium', 
                                                                         testInstaller.Id, testInstallerContact.Id, 
                                                                         testCustomer.Id, testRep.Id,
                                                                         Trig_Case.APPLICANT_REP, Trig_Case.RESP_PARTY_REP);
        insert testCase;

        //Create Device1
        Device__c testDevice = DER_TestUtility.createDevice_L2(testDERApp.Id);
        testDevice.AC_Equip_Type__c = 'Inverter';
        testDevice.AC_Equip_Sub_Type__c = 'Solar';
        testDevice.Requested__c = true;
        testDevice.Device_Phase__c = 'A';
        testDevice.AC_Equip_Cap__c = 40;
        testDevice.AC_Equip_Exp__c = 30;
        Insert testDevice;  
        
        return testDERApp.Id;
    }
}