force-app/main/default/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <label>ABN - DER</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DER_Offer_URL__c.field-meta.xml
<CustomField>
    <fullName>DER_Offer_URL__c</fullName>
    <label>DER Offer URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>The Invoice Number from ERP</description>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Send_DER_Offer__c.field-meta.xml
<CustomField>
    <fullName>Send_DER_Offer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To send offer.</description>
    <label>Send DER Offer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/DER_Agreement__c.object-meta.xml
<CustomObject>
    <label>DER Agreement</label>
    <nameField>
        <displayFormat>Agmt-{0000000}</displayFormat>
        <label>Agreement Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Agreement__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>DER Agreements</relationshipLabel>
    <relationshipName>DER_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DER_Agreement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offer Made</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Offer Declined</fullName>
            </value>
            <value>
                <fullName>Offer Expired</fullName>
            </value>
            <value>
                <fullName>Contract Active</fullName>
            </value>
            <value>
                <fullName>Contract Completed</fullName>
            </value>
            <value>
                <fullName>Contract Unauthorised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/eSignSettings__c/fields/DER_Offer_URL__c.field-meta.xml
<CustomField>
    <fullName>DER_Offer_URL__c</fullName>
    <label>DER Offer URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/DER_updateSendOfferTest.cls
/*
@author  : brajesh.tiwary@ausnetservices.com.au
@created : 28 Oct 2019
@Description : Test Class for DER_updateSendOffer class
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
@isTest
public class DER_updateSendOfferTest {
@isTest static void teststatusChangeAndURLUpdate()
    {
       //Create Individual Account
        Account testCustomer = new Account();
        testCustomer.Name = 'test';
        testCustomer.ABN__c = '1234567890';
        insert testCustomer;
        DER_Application__c testDERApp = new DER_Application__c();
        insert testDERApp;
        DER_Agreement__c agr = DER_TestUtility.createAgreement(testDERApp.Id,testCustomer.id,null,null,null,null);
        agr.status__c = 'Offer Expired';
        insert agr;
        
        Contact instCont = DER_TestUtility.createBusinessAccountContact(testCustomer.Id, 'Test', 'Test', 'test@derapp1212121.com');
        insert instCont;
        eSignSettings__c esign = new eSignSettings__c();
        esign.AES_Key__c = 'kKxPMcESCQOueOnmX5B5xw==';
        esign.DER_Offer_URL__c = 'google.com';
        esign.Name = 'test';
        insert esign;
        //Create case for Customer
        Case testCaseForCustomer = DER_TestUtility.createCaseForInstaller(DER_REST_Application_v1.CASE_RECORDTYPE_AUTO, 'More Info Required', 'Email', 'Low', testCustomer.Id, instCont.Id);        
        testCaseForCustomer.DER_Application__c = testDERApp.Id;
        testCaseForCustomer.Send_DER_Offer__c = false;
        testCaseForCustomer.Invoice_Number__c = '12345';
        insert testCaseForCustomer;
        string isUpdated = '';
        test.startTest();
        isUpdated = DER_updateSendOffer.updateOfferOnManualPage(testCaseForCustomer.Id);
        //offer.updateOfferOnManualPage(testCaseForCustomer.Id);
        test.stopTest();
        Id manualRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('DER Application - Manual').getRecordTypeId();
        testCaseForCustomer.recordTypeId = manualRecordTypeId;
        testCaseForCustomer.Status = 'Closed';
        update testCaseForCustomer;
        isUpdated = DER_updateSendOffer.updateOfferOnManualPage(testCaseForCustomer.Id);       
    }
}