force-app/main/default/objects/Account/fields/ASPAccreditaionId__c.field-meta.xml
<CustomField>
    <fullName>ASPAccreditaionId__c</fullName>
    <description>Stores the AusNet Services Accreditation Number for the ASP.</description>
    <externalId>true</externalId>
    <label>AusNet Services Accreditation ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the ASP chosen by the customer for External Design or External Construction.</description>
    <label>ASP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (ASP)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ASPnotDisplayedonList__c.field-meta.xml
<CustomField>
    <fullName>ASPnotDisplayedonList__c</fullName>
    <description>tv-255</description>
    <label>ASP Not Displayed on List</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/tve_ASPController.cls
/*
@author  : Lakshay Sharma <Lakshay.Sharma@ausnetservices.com.au>
@created : 29th Jan 2020
@Description : class for LWC component tve_getasplist
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
30th Jan 2020    pavan.dave@ausnetservices.com.au    Code review & finishing touch
-----------------------------------------------------------------------------------------
*/

public without sharing class tve_ASPController {
    @AuraEnabled
    public static Project__c updateManualASP(Id prjId, String aspManualText, String taskId) {
        System.debug('tve_ASPController------>prjId)---->'+prjId);
        System.debug('tve_ASPController------>aspManualText-->'+aspManualText);
        Project__c prj = [SELECT Id, ASP__c, ASPnotDisplayedonList__c 
                          FROM Project__c 
                          WHERE Id=: prjId];
        prj.ASPnotDisplayedonList__c = aspManualText;
        update prj;
        markTaskComplete(taskId);
        return prj;
    }

    @AuraEnabled
    public static Account findAccount(String extId){
        Account acc=[SELECT Id, ASPAccreditaionId__c 
                     FROM Account 
                     WHERE ASPAccreditaionId__c =: extId];
        return acc;
    }

    @AuraEnabled
    public static Project__c updateFromASPList(Id prjId, String extId, String taskId){
        Project__c proj= [SELECT Id, ASP__c, ASPnotDisplayedonList__c 
                           FROM Project__c 
                           WHERE Id=: prjId];
        proj.ASP__c = findAccount(extId).Id;
        update proj;
        markTaskComplete(taskId);        
        return proj;
        
    }

    //TV-2248 If taskId has a value then complete the task & send notification to project owner using flow
    public static void markTaskComplete(String taskId){        
        if(taskId != null && taskId != '' && taskId != 'undefined')
        {
            Task markComp = [SELECT Id, Status FROM Task WHERE Id =: taskId LIMIT 1];
            markComp.Status = 'Completed';
            update markComp;
        }
    }
}