force-app/main/default/objects/Account/fields/ASPAccreditaionId__c.field-meta.xml
<CustomField>
    <fullName>ASPAccreditaionId__c</fullName>
    <description>Stores the AusNet Services Accreditation Number for the ASP.</description>
    <externalId>true</externalId>
    <label>AusNet Services Accreditation ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the ASP chosen by the customer for External Design or External Construction.</description>
    <label>ASP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (ASP)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Trig_WorkOrderTest.cls
/*
  @author  : lakshay.sharma@ausnetservices.com.au
  @created : 28 Feb 2020
  @Description : Test class for WorkOrder Trigger and respective trigger logics
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  NA                    NA                              NA
  -----------------------------------------------------------------------------------------
*/
@isTest
public class Trig_WorkOrderTest {
    Private static Account acc;
    Private static Project__c prj;
    Private static string PROGRESS_BAR_STATUS = 'Allocated for initial assessment';
    Private static string CONTESTATIBILITY_TYPE = 'IDEC';
    Private static string aspManualText='Test01';
    Private static string extId='abc123456789012';
    @testSetup static void setup(){
        acc=TVE_TestUtility.createBusinessAccount('TestAccount');
        acc.ASPAccreditaionId__c='12345xyz12';
        insert acc;
    	prj=TVE_TestUtility.createProject('TestRef1',PROGRESS_BAR_STATUS,CONTESTATIBILITY_TYPE);
        prj.ASP__c=acc.Id;
        insert prj;
        WorkOrder workord = new WorkOrder(Type__c='Construction',StartDate=DateTime.NOW().AddDays(-1),EndDate=DateTime.NOW(),Project__c=prj.Id);
        insert workord;
    }
    @isTest public static void testAfterUpdateProjUpdate(){
		List<WorkOrder> workord=[SELECT Id,Type__c,EndDate,Project__c FROM WorkOrder WHERE Type__c='Construction'];
      workord[0].StartDate =  DateTime.NOW();
      workord[0].EndDate=DateTime.NOW().AddDays(1);
            
        
        Test.startTest();
        update workord[0];
		Test.stopTest();        
    }

}