force-app/main/default/objects/Account/fields/Contact_Matched__c.field-meta.xml
<CustomField>
    <fullName>Contact_Matched__c</fullName>
    <label>Contact Matched</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Contacts Found</fullName>
            </value>
            <value>
                <fullName>Contact Found</fullName>
            </value>
            <value>
                <fullName>Multiple Contacts Found</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Market_Identifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Identifier</label>
    <referenceTo>vlocity_cmt__ServicePoint__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__PrimaryContactId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the primary person to contact for anything related to this account. For consumers, the primary contact is often the same as the person who is the consumer but need not be. For example, the consumer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__RootAccountId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__RootAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The ultimate, or root, parent account of this account. Used to enable display of all service and billing accounts for the given root account. The Vlocity TelcoAccount trigger sets the RootAccountId__c based on the ParentId of this record and any parent records. Changes of the account hierarchy at the top level may not trigger changes to the child accounts. Use the Account Hierarchy Maintenance job from the CMT Maintenance tab to fix the RootAccountId__c on these child records.</description>
    <label>Root Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Contact__c.field-meta.xml
<CustomField>
    <fullName>MC_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactPointConsent/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Point Consents</relationshipLabel>
    <relationshipName>Contact_Point_Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContactPointConsent/fields/Contact_Point__c.field-meta.xml
<CustomField>
    <fullName>Contact_Point__c</fullName>
    <label>Contact Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactPointConsent/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF((EffectiveTo &lt;= NOW()) || (EffectiveFrom &gt; NOW()), &apos;Inactive&apos;, &apos;Active&apos;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Outage_AccountContactUtils.cls
public with sharing class Outage_AccountContactUtils {

	public static final String CON_MATCHED_MULTIPLE = 'Multiple Contacts Found';
	public static final String CON_MATCHED_FOUND = 'Contact Found';
	public static final String CON_MATCHED_NONE = 'No Contacts Found';

	/********** Constructor **********/

	// public Outage_AccountContactUtils() { /* No Constructor required atm*/ }


	/********** Main methods **********/

	public static void handleMarketingCloudContactByContactIds(Set<Id> contactIds)
	{
		Id serviceRecordTypeId =  UtilDatabase.getRecordTypeNames('Account').get(Outage_IncidentProcessor.ACC_SERVICE_RT);
		List<Contact> contactsToUpdate = new List<Contact>();

		for (Contact con : [SELECT Id, Name, MC_Contact__c, Account.vlocity_cmt__PrimaryContactId__c, Account.RecordTypeId,

								(SELECT Id, ContactId, AccountId, Roles
								 FROM AccountContactRelations
								 WHERE Account.Market_Identifier__c != null
								 AND Account.Market_Identifier__r.vlocity_cmt__Status__c = :Outage_IncidentProcessor.SERV_POINT_STS_ACTIVE
								 AND Account.Market_Identifier__r.vlocity_cmt__ServiceType__c = 'Electricity'
								 AND Account.Market_Identifier__r.dcp_NMIStatus_To_Date__c = null
								 AND (Roles includes(:Outage_IncidentProcessor.ACR_ROLE_MKT_CON) OR Roles includes(:Outage_IncidentProcessor.ACR_ROLE_SEC_CON))
								 LIMIT 1),

								 (SELECT Id, Name FROM vlocity_cmt__Accounts__r
								 WHERE RecordType.Name = :Outage_IncidentProcessor.ACC_SERVICE_RT
								 AND Market_Identifier__c != null
								 AND Market_Identifier__r.vlocity_cmt__Status__c = :Outage_IncidentProcessor.SERV_POINT_STS_ACTIVE
								 AND Market_Identifier__r.vlocity_cmt__ServiceType__c = 'Electricity'
								 AND Market_Identifier__r.dcp_NMIStatus_To_Date__c = null
								 LIMIT 1)

							FROM Contact
							WHERE Id IN :contactIds])
		{
			if (con.AccountContactRelations.size() >= 1 || con.vlocity_cmt__Accounts__r.size() >= 1) {

				if (!con.MC_Contact__c) {
					con.MC_Contact__c = true;
					contactsToUpdate.add(con);
				}

			} else if (con.MC_Contact__c) {
				con.MC_Contact__c = false;
				contactsToUpdate.add(con);
			}
		}

		if (!contactsToUpdate.isEmpty()) {
			update contactsToUpdate;
		}
	}

	public static void runAccountContactMatching()
	{
		String query = Outage_AccountContactBatch.getBatchQuery();
		List<AccountContactRelation> ACRsList = Database.query(query);

		Set<Id> accIds = new Set<Id>();
		for (AccountContactRelation acr: ACRsList)
			accIds.add(acr.AccountId);

		List<Account> accountsAndACRsList = [SELECT Id, Name, vlocity_cmt__PrimaryContactId__c, Contact_Matched__c,
											(SELECT Id, ContactId, AccountId, Roles
												FROM AccountContactRelations
												LIMIT 2)
											FROM Account 
											WHERE Id IN :accIds];

		if (accountsAndACRsList == null || accountsAndACRsList.isEmpty())
		{
			// crash
			System.debug('bad');
			return ;
		}

		processAccountContactMatching(accountsAndACRsList);
	}

	public static void processAccountContactMatching(List<Account> accountsAndACRsList)
	{
		if (accountsAndACRsList == null || accountsAndACRsList.isEmpty()) return;

		List<Account> accountsToUpdate = new List<Account>();

		for (Account acc : accountsAndACRsList)
		{
			// Grab prior values
			Id     PrimConId  = acc.vlocity_cmt__PrimaryContactId__c;
			String ConMatched = acc.Contact_Matched__c;

			if (acc.AccountContactRelations.isEmpty())
			{
				acc.vlocity_cmt__PrimaryContactId__c = null;
				acc.Contact_Matched__c = CON_MATCHED_NONE;
			}
			else if (acc.AccountContactRelations.size() == 1 && String.isBlank(acc.vlocity_cmt__PrimaryContactId__c))
			{
				acc.vlocity_cmt__PrimaryContactId__c = acc.AccountContactRelations[0].ContactId;
				acc.Contact_Matched__c = CON_MATCHED_FOUND;

			}
			else if (acc.AccountContactRelations.size() >= 1)
			{

				if (String.isNotBlank(acc.vlocity_cmt__PrimaryContactId__c))
				{
					acc.Contact_Matched__c = CON_MATCHED_FOUND;
				}
				else
				{
					acc.Contact_Matched__c = CON_MATCHED_MULTIPLE;
				}
			}

			// Only update if values have changed
			if (acc.vlocity_cmt__PrimaryContactId__c != PrimConId ||
				acc.Contact_Matched__c != ConMatched)
			{
				accountsToUpdate.add(acc);
			}
		}

		if (!accountsToUpdate.isEmpty())
			update accountsToUpdate;
	}

	public static void processMCContactCheckbox(List<Account> argAccs)
	{
		Set<Id> contactIds = new Set<Id>();

		for (Account acc: [SELECT Id, vlocity_cmt__PrimaryContactId__c
							FROM Account
							WHERE Id IN :argAccs])
		{
			if (acc.vlocity_cmt__PrimaryContactId__c != null)
				contactIds.add(acc.vlocity_cmt__PrimaryContactId__c);
		}

		for (AccountContactRelation acr: [SELECT Id, ContactId, AccountId, Roles 
											FROM AccountContactRelation
											WHERE AccountId IN :argAccs
											AND Account.RecordType.Name = :Outage_IncidentProcessor.ACC_SERVICE_RT
											AND Account.Market_Identifier__c != null
											AND Account.Market_Identifier__r.vlocity_cmt__Status__c = :Outage_IncidentProcessor.SERV_POINT_STS_ACTIVE
											AND Account.Market_Identifier__r.vlocity_cmt__ServiceType__c = 'Electricity'
											AND Account.Market_Identifier__r.dcp_NMIStatus_To_Date__c = null
											AND Contact.IsPersonAccount = false
											AND (Roles INCLUDES(:Outage_IncidentProcessor.ACR_ROLE_MKT_CON) 
												 OR Roles INCLUDES(:Outage_IncidentProcessor.ACR_ROLE_SEC_CON))])
		{
			contactIds.add(acr.ContactId);
		}

		handleMarketingCloudContactByContactIds(contactIds);
	}

	public static void optOutContactPhoneNumbers(Set<String> stopNumbers)
	{
		String STOP_REASON = 'Consent Removed: Number on Stop List';

		// Ensure numbers are formated correctly, or they won't match
		//		eg 61400123456

		for (String phNum: stopNumbers)
		{
			String newPhNum = CE_ContactPointSync2.getMobileFormat(phNum);
			if (phNum != newPhNum)
			{
				stopNumbers.add(newPhNum);
				stopNumbers.remove(phNum);
			}
		}

		UtilDatabase db = new UtilDatabase();

		for (ContactPointConsent CPC: [SELECT Id, Name, Contact__r.Name, Status__c, Contact_Point__c, EffectiveFrom
										FROM ContactPointConsent
										WHERE Contact_Point__c IN :stopNumbers
										AND Status__c = :Outage_IncidentProcessor.CPC_STS_ACTIVE
										AND DataUsePurpose.Name = :Outage_IncidentProcessor.DATAUSE_OUTAGES
										AND EngagementChannelType.Name = :Outage_IncidentProcessor.CHANNEL_SMS])
		{
			CPC.EffectiveTo = CPC.EffectiveFrom;
			CPC.CaptureSource = STOP_REASON;
			CPC.CaptureDate = System.now();

			db.addObjForUpsert(CPC);
		}

		db.upsertObjs();
	}

	/********** Helper methods **********/
}