force-app/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELE - CINCL</fullName>
            </value>
            <value>
                <fullName>ELE - DER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAPCustomer__c.field-meta.xml
<CustomField>
    <fullName>SAPCustomer__c</fullName>
    <label>SAP Customer</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer_Business.recordType-meta.xml
<RecordType>
    <fullName>Customer_Business</fullName>
    <active>true</active>
    <description>Business Account</description>
    <label>Customer - Business</label>
</RecordType>

force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master detail relationship between account and artefact</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/SAPCustomer__c.field-meta.xml
<CustomField>
    <fullName>SAPCustomer__c</fullName>
    <label>SAP Customer</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Artefact__c/recordTypes/Offer.recordType-meta.xml
<RecordType>
    <fullName>Offer</fullName>
    <active>true</active>
    <description>Record type for offer</description>
    <label>Offer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AD_User_ID__c.field-meta.xml
<CustomField>
    <fullName>AD_User_ID__c</fullName>
    <label>AD User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELE - CINCL</fullName>
            </value>
            <value>
                <fullName>ELE - DER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/recordTypes/WorkOrder.recordType-meta.xml
<RecordType>
    <fullName>WorkOrder</fullName>
    <active>true</active>
    <label>WorkOrder</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/AgentLastName__c.field-meta.xml
<CustomField>
    <fullName>AgentLastName__c</fullName>
    <description>Last name of the customer agent, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Agent Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CMProgressBar__c.field-meta.xml
<CustomField>
    <fullName>CMProgressBar__c</fullName>
    <label>Progress Bar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CMProgressBar</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/ContestabilityType__c.field-meta.xml
<CustomField>
    <fullName>ContestabilityType__c</fullName>
    <label>Contestability Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDIC</fullName>
            </value>
            <value>
                <fullName>EDEC</fullName>
            </value>
            <value>
                <fullName>IDEC</fullName>
            </value>
            <value>
                <fullName>IDEC-2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/IsPropertyOwner__c.field-meta.xml
<CustomField>
    <fullName>IsPropertyOwner__c</fullName>
    <description>Property owner of the installation place</description>
    <label>Is Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerCompany__c.field-meta.xml
<CustomField>
    <fullName>OwnerCompany__c</fullName>
    <description>Name of owner company with which lead is affiliated. Up to 255 characters are allowed in this field.</description>
    <label>Owner Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerLastName__c.field-meta.xml
<CustomField>
    <fullName>OwnerLastName__c</fullName>
    <description>Last name of the property owner, as displayed on the lead edit page. Up to 80 characters are allowed in this field.</description>
    <label>Owner Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/OwnerMobile__c.field-meta.xml
<CustomField>
    <fullName>OwnerMobile__c</fullName>
    <description>Cellular or mobile phone number. Up to 40 characters are allowed in this field.</description>
    <label>Owner Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/User/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_TestUtility.cls
/*
@author  : pavan.dave@ausnetservices.com.au
@created : 16 Dec 2019
@Description : Utility class for TVE test classes
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
public with sharing class TVE_TestUtility {
    public static final string CLASSIFICATION_INVOICE = 'Invoice';
    public static final string CLASSIFICATION_FIRM_OFFER_LETTER = 'Firm Offer Letter';
    public static String ACCOUNT_RECORDTYPE_INDIVIDUAL = 'Customer_Individual';
    public static String ACCOUNT_RECORDTYPE_BUSINESS  = 'Customer_Business';
    public static Project__c createProject(String referenceNum, String status, string ConType) {
        return new Project__c(
            Name = referenceNum,
            CMProgressBar__c = status,
            ContestabilityType__c = ConType,
            OwnerMobile__c = '8932438932',
            OwnerLastName__c = 'testLastName',
            OwnerCompany__c = 'testOwnerComp',
            AgentLastName__c = 'testLastName9822',
            IsPropertyOwner__c = 'Yes');
    }
    public static Account createPersonAccount(String acctName, String emailAddr) {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCOUNT_RECORDTYPE_INDIVIDUAL).getRecordTypeId();
        return new Account(
            LastName = acctName,
            RecordTypeId = acctRTId,
            PersonEmail = emailAddr,
            Customer_Type__c = 'ELE - CINCL'
        );
    }
    public static Account createBusinessAccount(String acctName) {
        Id acctRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCOUNT_RECORDTYPE_BUSINESS).getRecordTypeId();
        system.debug('acctRTId'+acctRTId);
        return new Account(
            Name = acctName,
            RecordTypeId = acctRTId,
            SAPCustomer__c='10263',
            Customer_Type__c = 'ELE - CINCL',
            BillingStreet='Test BillingStreet to see of split function work n it split the data into array of string. Length should be greater than 35'
        );
    }
    public static Artefact__c createOfferArtefact(String name, Id project, Id account) {
        Id offerRTId = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get('Offer').getRecordTypeId();
        return new Artefact__c(
            Name = name,
            Project__c = project,
            Account__c = account,
            RecordTypeId=offerRTId,
            Classification__c = CLASSIFICATION_FIRM_OFFER_LETTER);
    }
    public static Emailtemplate createEmailtemplate()
    {
        return new Emailtemplate(Name='test',
                                 FolderId=userinfo.getuserid(), 
                                 TemplateType='text',
                                 developername='test',
                                 isActive=true);
        
    }
    
    public static contact createContact(){
        return new contact(FirstName = 'Dee',
                           LastName = 'Licious',
                           email = 'Arti.Fogla@ausnetservices.com.au',
                           AD_User_ID__c='sd33dd');
    }
    
    public static contact createContact(Id accId, String fName, String lName, String email){
        return new contact(AccountId = accId,
                           FirstName = fName,
                           LastName = lName,
                           Email = email);
    }

    public static Artefact__c createInvoiceArtefact(String name, Id project, Id account) {
        Id offerRTId = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get('Invoice').getRecordTypeId();
        return new Artefact__c(
            Name = name,
            Project__c = project,
            Account__c = account,
            RecordTypeId=offerRTId,
            Classification__c = CLASSIFICATION_INVOICE);
    }
    
    public static Artefact__c createArtefact(String name, Id project, Id account) {
        Id offerRTId = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get('Invoice').getRecordTypeId();
        return new Artefact__c(
            Name = name,
            Project__c = project,
            Account__c = account,
            RecordTypeId=offerRTId,
            Classification__c = 'Audit reports');
    }
    
    public static User createTestUser(String userEmail){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        System.assert(p != null, 'Profile not found.');
        
        return new User(
            ProfileId = p.Id,
            LastName = 'Doe',
            Email = userEmail,
            Username = userEmail + '.'+  System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            SAP_ID__c='TRAI',
            IsActive=true
        );
    }
    
    public static void insertFile(String parentId){
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = parentId;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;    
    }
    
    //added by Neha
    public static task createTask(String projID, String Userid,String sub) {
        return new Task(
            WhatID = projID,
            Subject=sub,
            Status='In Progress',
            Priority='Normal',
            OwnerID = Userid);
    }
    
    //added by Neha
    public static Opportunity createOpportunity(ID projId,ID accId){
        return new Opportunity(Name='Test opp',
                               Project__c=projId,
                               Type='Design',
                               StageName='Prospecting',
                               AccountId= accId,
                               CloseDate=System.today()
                              );
        
    }

    public static Opportunity createOpportunityType(ID projId,ID accId, String Type){	
        return new Opportunity(Name='Test opp',	
                              Project__c=projId,	
                              Type=Type,	
                              StageName='Prospecting',	
                              AccountId= accId,	
                              CloseDate=System.today()	
                              );	
        	
    }

    //added by Neha
    public static Integration_Task__c createIntegrationTask(ID parentID,String Operation,String sobj,String status,String type){
        return new Integration_Task__c(Operation__c=Operation,
                                       ParentId__c=parentID,
                                       SObject__c=sobj,
                                       Status__c=status,
                                       Type__c=type);
    }
    
      //added by Harshad	
      public static WorkOrder createWorkOrder(ID projId,String Type){	
        return new WorkOrder(Project__c=projId,Type__c = Type );	
        	
    }
    
    public static TVE_Integration_Constants__c createIntegrationConstant()
    {
        return new TVE_Integration_Constants__c(Assembly__c='40000481',
                                                Integration_Method_Name__c='TVE_SAPInteg_CreateMasterNoti',
                                                MessageID__c='000011111',
                                                Partner_Role_1__c='AG',
                                                Partner_Role_2__c='VW',
                                                Name='TVE_SAPInteg_CreateMasterNoti');
    }
    
    public static Project__c createIntegrationProject(String referenceNum, String status, string ConType ,id accid)
    {
        return new Project__c(Name = referenceNum,
                              CMProgressBar__c = status,
                              ContestabilityType__c = ConType,
                              PropertyAccessInstructions__c='Test Property Access Instruction',
                              HazardDetails__c='Test hazard detail',
                              FunctionalLocation__c='DL-BN009-2601730307',
                              //projObj.EstimatedCompletionDate__c='2020-02-12T12:34:56';
                              SiteOwner__c=accid,
                              ApplicationType__c='Residential',
                              PaymentReferenceNumber__c='test',
                              IsPropertyOwner__c='No',
                              AuthorisedRepresentative__c=accid);
    }
    
    public static List<Project__c> createMultipleIntegrationProject(String referenceNum, String status, string ConType ,id accid)
    {
        List<Project__c> projList = new List<Project__c>();
        Project__c proj1 = new Project__c();
        Project__c proj2 = new Project__c();
        Project__c proj3 = new Project__c();
        Project__c proj4 = new Project__c();
        Project__c proj5 = new Project__c();
        Project__c proj6 = new Project__c();
        
        proj1.Name = referenceNum;
        proj1.CMProgressBar__c = status;
        proj1.ContestabilityType__c = ConType;
        proj1.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj1.HazardDetails__c='Test hazard detail';
        proj1.FunctionalLocation__c='DL-BN009-2601730307';
        proj1.SiteOwner__c=accid;
        proj1.ApplicationType__c='Residential';
        proj1.PaymentReferenceNumber__c='test';
        proj1.IsPropertyOwner__c='No';
        proj1.AuthorisedRepresentative__c=accid;
        proj1.CMNumber__c='100108663';
		projList.add(proj1);   
        
        proj2.Name = referenceNum;
        proj2.CMProgressBar__c = status;
        proj2.ContestabilityType__c = ConType;
        proj2.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj2.HazardDetails__c='Test hazard detail';
        proj2.FunctionalLocation__c='DL-BN009-2601730307';
        //proj2.SiteOwner__c=accid;
        proj2.ApplicationType__c='New Estate';
        proj2.PaymentReferenceNumber__c='test';
        proj2.IsPropertyOwner__c='No';
        proj2.AuthorisedRepresentative__c=accid;
        projList.add(proj2);
        
        proj3.Name = referenceNum;
        proj3.CMProgressBar__c = status;
        proj3.ContestabilityType__c = ConType;
        proj3.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj3.HazardDetails__c='Test hazard detail';
        proj3.FunctionalLocation__c='DL-BN009-2601730307';
        proj3.SiteOwner__c=accid;
        proj3.ApplicationType__c='Residential';
        proj3.PaymentReferenceNumber__c='test';
        proj3.IsPropertyOwner__c='Yes';
        proj3.AuthorisedRepresentative__c=accid;
		projList.add(proj3);   
        
        proj4.Name = referenceNum;
        proj4.CMProgressBar__c = status;
        proj4.ContestabilityType__c = ConType;
        proj4.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj4.HazardDetails__c='Test hazard detail';
        proj4.FunctionalLocation__c='DL-BN009-2601730307';
        proj4.SiteOwner__c=accid;
        proj4.ApplicationType__c='Residential';
        proj4.PaymentReferenceNumber__c='';
        proj4.IsPropertyOwner__c='Yes';
        proj4.AuthorisedRepresentative__c=accid;
		projList.add(proj4); 
        
        proj5.Name = referenceNum;
        proj5.CMProgressBar__c = status;
        proj5.ContestabilityType__c = ConType;
        proj5.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj5.HazardDetails__c='Test hazard detail';
        proj5.FunctionalLocation__c='DL-BN009-2601730307';
        proj5.SiteOwner__c=accid;
        proj5.ApplicationType__c='Residential';
        proj5.PaymentReferenceNumber__c='';
        proj5.IsPropertyOwner__c='Yes';
        proj5.AuthorisedRepresentative__c=accid;
        proj5.Ready_for_SAP_Integration__c=true;
        proj5.CMNumber__c='75002168';
        projList.add(proj5); 
        
        proj6.Name = referenceNum;
        proj6.CMProgressBar__c = status;
        proj6.ContestabilityType__c = ConType;
        proj6.PropertyAccessInstructions__c='Test Property Access Instruction';
        proj6.HazardDetails__c='Test hazard detail';
        proj6.FunctionalLocation__c='DL-BN009-2601730307';
        proj6.SiteOwner__c=accid;
        proj6.ApplicationType__c='Residential';
        proj6.PaymentReferenceNumber__c='';
        proj6.IsPropertyOwner__c='Yes';
        proj6.AuthorisedRepresentative__c=accid;
        proj6.Ready_for_SAP_Integration__c=true;
        //proj5.CMNumber__c='75002168';
        projList.add(proj6); 
        
        
        
        return projList;
    }
    
    public static List<Opportunity> createMultipleOpportunity(List<Project__c> projList,ID accId){
        List<Opportunity> oppList = new List<Opportunity>();
       
        for(Project__c proj:projList){
             Opportunity opp = new Opportunity();
             opp.Name='Test opp';
             opp.Project__c=proj.Id;
             opp.Type='Design';
             opp.StageName='Prospecting';
             opp.AccountId= accId;
             opp.CloseDate=System.today();
            OppList.add(opp);
        }
       return oppList;
    }
    
    public static List<Integration_Task__c> createMultipleIntegrationTask(List<Project__c> projList,String Operation,String sobj,String status,String type){
        List<Integration_Task__c> intTaskList = new List<Integration_Task__c>();
       
        for(Project__c proj:projList)
        {
            Integration_Task__c intTask = new Integration_Task__c();
        	intTask.Operation__c=Operation;
            intTask.ParentId__c=proj.id;
            intTask.SObject__c=sobj;
            intTask.Status__c=status;
            intTask.Type__c=type;
			intTaskList.add(intTask);            
        }
       return intTaskList;
        
    }
    
     public static ConstructionMeasureSets__x  createConstMeasureSet(){
         return new ConstructionMeasureSets__x(Qmnum__c='100108664',
                                              Cmnum__c='100108663');
     }
    
    public static ContentVersion createCV(String artId){
        return new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true,
            	FirstPublishLocationId=artId
            );
    }
       
    
}