force-app/main/default/objects/Account/fields/Market_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Market_Identifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Identifier</label>
    <referenceTo>vlocity_cmt__ServicePoint__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__PremisesId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PremisesId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the premises at which this customer may need services. Part of the service address definition of a customer or service account.</description>
    <label>Premises</label>
    <referenceTo>vlocity_cmt__Premises__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__PrimaryContactId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the primary person to contact for anything related to this account. For consumers, the primary contact is often the same as the person who is the consumer but need not be. For example, the consumer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/vlocity_cmt__Status__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__Status__c</fullName>
    <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/Tariff_Trial__c.object-meta.xml
<CustomObject>
    <label>Tariff Trial</label>
    <nameField>
        <displayFormat>TT-{0000000}</displayFormat>
        <label>Tariff Trial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tariff Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tariff_Trial__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <description>Name of the campaign</description>
    <label>Campaign Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>duration of the tariff trial event</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email of the participant</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>mobile number of the participant</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <description>NMI of tariff trial</description>
    <label>NMI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_First_Name__c</fullName>
    <description>first name of the participant</description>
    <label>Participant First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_Id__c.field-meta.xml
<CustomField>
    <fullName>Participant_Id__c</fullName>
    <externalId>true</externalId>
    <label>Participant Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Last_Name__c</fullName>
    <label>Participant Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <description>Start datetime of the event</description>
    <label>Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    public static List<Account> createAccounts(Integer numberOfAccounts, List<vlocity_cmt__ServicePoint__c> sps, List<Contact> contacts) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numberOfAccounts; i++) {
            Account acc = new Account(
                Name = 'Test Account ' + i,
                Market_Identifier__c = sps[i].Id,
                vlocity_cmt__PrimaryContactId__c = contacts[i].Id
                // Add other required fields here
            );
            accounts.add(acc);
        }
        return accounts;
    }

    public static List<vlocity_cmt__Premises__c> createPremises(Integer numberOfPremises) {
        List<vlocity_cmt__Premises__c> premises = new List<vlocity_cmt__Premises__c>();
        for (Integer i = 0; i < numberOfPremises; i++) {
            vlocity_cmt__Premises__c premise = new vlocity_cmt__Premises__c(
                Name = '123' + i + ' Fake Street', 
                vlocity_cmt__StreetAddress__c = '123' + i + ' Fake Street',
                vlocity_cmt__City__c = 'Melbourne', 
                vlocity_cmt__State__c = 'VIC', 
                vlocity_cmt__PostalCode__c = '3000');
            premises.add(premise);
        }
        return premises;
    }

    public static List<Contact> createContacts(Integer numberOfContacts) {
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < numberOfContacts; i++) {
            Contact con = new Contact(
                FirstName = 'Test First Name ' + i,
                LastName = 'Test Last Name ' + i,
                Email = 'test' + i + '@test.com',
                MobilePhone = '46531425' + i
                // Add other required fields here
            );
            contacts.add(con);
        }
        return contacts;
    }

    public static List<vlocity_cmt__ServicePoint__c> createServicePoints(Integer numberOfServicePoints, List<vlocity_cmt__Premises__c> premises) {
        List<vlocity_cmt__ServicePoint__c> sps = new List<vlocity_cmt__ServicePoint__c>();
        for (Integer i = 0; i < numberOfServicePoints; i++) {
            vlocity_cmt__ServicePoint__c sp = new vlocity_cmt__ServicePoint__c(
                Name = '1234567890' + i, 
                vlocity_cmt__MarketIdentifier__c = '1234567890' + i, 
                vlocity_cmt__ServiceType__c = 'Electricity', 
                vlocity_cmt__Status__c = 'Connected', 
                vlocity_cmt__PremisesId__c = premises[i].Id);
            sps.add(sp);
        }
        return sps;
    }

    public static List<Tariff_Trial__c> createTariffTrials(Integer numberOfTrials) {
        List<Tariff_Trial__c> tariffTrials = new List<Tariff_Trial__c>();
        for (Integer i = 0; i < numberOfTrials; i++) {
            Tariff_Trial__c trial = new Tariff_Trial__c(
                Event_Id__c = 'Event' + i,
                NMI__c = '1234567890' + i,
                Campaign_Name__c = 'Campaign' + i,
                Start_DateTime__c = Date.today(),
                Duration__c = 5, 
                // Add other required fields here
                Participant_First_Name__c = 'IBM',
                Participant_Last_Name__c = 'Tester',
                Participant_Id__c = 'Event' + i + '_' + 'Event' + i,
                Mobile__c = '46531425' + i,
                Email__c = 'test' + i + '@test.com'
            );
            tariffTrials.add(trial);
        }
        return tariffTrials;
    }
}