force-app/main/default/objects/Account/fields/Market_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Market_Identifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Identifier</label>
    <referenceTo>vlocity_cmt__ServicePoint__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/vlocity_cmt__PrimaryContactId__c.field-meta.xml
<CustomField>
    <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID of the primary person to contact for anything related to this account. For consumers, the primary contact is often the same as the person who is the consumer but need not be. For example, the consumer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Tariff_Trial_Event.recordType-meta.xml
<RecordType>
    <fullName>Tariff_Trial_Event</fullName>
    <active>true</active>
    <description>Campaign for tariff trial events such as EV tariff trial</description>
    <label>Tariff Trial Event</label>
</RecordType>

force-app/main/default/objects/CampaignMember/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <description>Calculation of baseline usage</description>
    <label>Baseline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>the email of a campaign member for tariff trial</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>first name of campaign member for tariff trial</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>last name of a campaign member for tariff trial</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Mobile_Phone__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone__c</fullName>
    <description>the mobile phone of a campaign member for tariff trial</description>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Participant_Id__c.field-meta.xml
<CustomField>
    <fullName>Participant_Id__c</fullName>
    <externalId>true</externalId>
    <label>Participant Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Performance__c.field-meta.xml
<CustomField>
    <fullName>Performance__c</fullName>
    <description>Calculation of Performance</description>
    <label>Performance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Retailer_Id__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Id__c</fullName>
    <externalId>true</externalId>
    <label>Retailer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Service_Point__c.field-meta.xml
<CustomField>
    <fullName>Service_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Point</label>
    <referenceTo>vlocity_cmt__ServicePoint__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/Tariff_Trial__c.object-meta.xml
<CustomObject>
    <label>Tariff Trial</label>
    <nameField>
        <displayFormat>TT-{0000000}</displayFormat>
        <label>Tariff Trial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tariff Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tariff_Trial__c/fields/Baseline__c.field-meta.xml
<CustomField>
    <fullName>Baseline__c</fullName>
    <label>Baseline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <description>Name of the campaign</description>
    <label>Campaign Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>duration of the tariff trial event</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>email of the participant</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>mobile number of the participant</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <description>NMI of tariff trial</description>
    <label>NMI</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_First_Name__c</fullName>
    <description>first name of the participant</description>
    <label>Participant First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_Id__c.field-meta.xml
<CustomField>
    <fullName>Participant_Id__c</fullName>
    <externalId>true</externalId>
    <label>Participant Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Participant_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Last_Name__c</fullName>
    <label>Participant Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Performance__c.field-meta.xml
<CustomField>
    <fullName>Performance__c</fullName>
    <label>Performance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Retailer_Id__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Id__c</fullName>
    <description>participating retailer id</description>
    <label>Retailer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tariff_Trial__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <description>Start datetime of the event</description>
    <label>Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TariffTrial_CampaignUtil.cls
public with sharing class TariffTrial_CampaignUtil {

    public static void createOrUpdateCampaigns(List<Tariff_Trial__c> tariffTrials) {
        Map<String, Campaign> eventToCampaignMap = new Map<String, Campaign>();
        List<CampaignMember> newCampaignMembers = new List<CampaignMember>();
        Set<String> nmis = new Set<String>();
        Set<String> eventIds = new Set<String>();

        // Step 1: Build set of NMIs for querying matching accounts
        // Build event ID to Campaign mapping
        for (Tariff_Trial__c tariffTrial : tariffTrials) {
            nmis.add(tariffTrial.NMI__c);
            eventIds.add(tariffTrial.Event_Id__c);
        }

        // Step 2: Query matching accounts based on NMIs
        // TODO: need to extend query conditions
        // Note: there is a risk if the account doesn't have a contact
        Map<String, Account> nmiToAccountMap = new Map<String, Account>();
        for (Account acc : [SELECT Id, vlocity_cmt__PrimaryContactId__c, Market_Identifier__r.vlocity_cmt__MarketIdentifier__c
                            FROM Account 
                            WHERE Market_Identifier__r.vlocity_cmt__MarketIdentifier__c IN :nmis]) {
            nmiToAccountMap.put(acc.Market_Identifier__r.vlocity_cmt__MarketIdentifier__c, acc);
        }


        // Step 3: Query matching Campaigns
        for(Campaign campaign : [SELECT Id, Name, Event_Id__c 
                                 FROM Campaign 
                                 WHERE Event_Id__c IN :eventIds 
                                 AND RecordType.DeveloperName = 'Tariff_Trial_Event']) {
            eventToCampaignMap.put(campaign.Event_Id__c, campaign);
        }
        
        // Step 2: Create new Campaigns
        for(Tariff_Trial__c tariffTrial : tariffTrials) {
            if(!eventToCampaignMap.containsKey(tariffTrial.Event_Id__c)) {
                Campaign campaign = new Campaign();
                campaign.Name = tariffTrial.Campaign_Name__c;
                campaign.Event_Id__c = tariffTrial.Event_Id__c;
                campaign.IsActive = true;
                campaign.Start_Date_Time__c = tariffTrial.Start_DateTime__c;
                campaign.Duration__c = tariffTrial.Duration__c;
                campaign.RecordTypeId = Schema.SObjectType.Campaign.RecordTypeInfosByDeveloperName.get('Tariff_Trial_Event').RecordTypeId;
                // newCampaigns.add(campaign);
                eventToCampaignMap.put(tariffTrial.Event_Id__c, campaign);
            }
            else {
                Campaign campaign = eventToCampaignMap.get(tariffTrial.Event_Id__c);
                campaign.Name = tariffTrial.Campaign_Name__c;
                campaign.Start_Date_Time__c = tariffTrial.Start_DateTime__c;
                campaign.Duration__c = tariffTrial.Duration__c;
                eventToCampaignMap.put(tariffTrial.Event_Id__c, campaign);
            }
        }
        
        // Step 3: Insert new Campaigns and retrieve Campaign Ids
        if(!eventToCampaignMap.isEmpty()) {
            upsert eventToCampaignMap.values() Event_Id__c;
        }
        
        // Step 4: Create or update Campaign Members
        for(Tariff_Trial__c tariffTrial : tariffTrials) {
            Campaign campaign = eventToCampaignMap.get(tariffTrial.Event_Id__c);
            
            String participantId = tariffTrial.Event_Id__c + '-' + tariffTrial.NMI__c;
            
            Account matchingAccount = nmiToAccountMap.get(tariffTrial.NMI__c);
            if (matchingAccount != null) {
                CampaignMember newMember = new CampaignMember(
                    CampaignId = campaign.Id,
                    Participant_Id__c = participantId,
                    ContactId = matchingAccount.vlocity_cmt__PrimaryContactId__c, 
                    First_Name__c = tariffTrial.Participant_First_Name__c, 
                    Last_Name__c = tariffTrial.Participant_Last_Name__c,
                    Retailer_Id__c = tariffTrial.Retailer_Id__c,
                    Mobile_Phone__c = tariffTrial.Mobile__c,
                    Email__c = tariffTrial.Email__c,
                    NMI__c = tariffTrial.NMI__c,
                    Account__c = matchingAccount.Id,
                    Service_Point__c = matchingAccount.Market_Identifier__c,
                    Baseline__c = tariffTrial.Baseline__c,
                    Performance__c = tariffTrial.Performance__c
                );
                newCampaignMembers.add(newMember);
            }
        }
        
        // Step 5: Insert new Campaign Members
        if(!newCampaignMembers.isEmpty()) {
            upsert newCampaignMembers Participant_Id__c;
        }
    }    
}