force-app/main/default/objects/Account/fields/SAPCustomer__c.field-meta.xml
<CustomField>
    <fullName>SAPCustomer__c</fullName>
    <label>SAP Customer</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/Artefact__c.object-meta.xml
<CustomObject>
    <label>Artefact</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artefacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Artefact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Master detail relationship between account and artefact</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Additional_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Additional_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine1ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine1ExGST__c</fullName>
    <label>Amount Line 1 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine2ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine2ExGST__c</fullName>
    <label>Amount Line 2 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/AmountLine3ExGST__c.field-meta.xml
<CustomField>
    <fullName>AmountLine3ExGST__c</fullName>
    <label>Amount Line 3 (ex. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prelim Estimate</fullName>
            </value>
            <value>
                <fullName>Firm Offer Letter</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Drawings</fullName>
            </value>
            <value>
                <fullName>Technical Specs</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>ACCC form</fullName>
            </value>
            <value>
                <fullName>CRAB form</fullName>
            </value>
            <value>
                <fullName>Audit reports</fullName>
            </value>
            <value>
                <fullName>Co-ordination letters</fullName>
            </value>
            <value>
                <fullName>Easements/ MOA</fullName>
            </value>
            <value>
                <fullName>Rebates</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Leases</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Impact Assessments</fullName>
            </value>
            <value>
                <fullName>Progress Reports</fullName>
            </value>
            <value>
                <fullName>Signed Contracts</fullName>
            </value>
            <value>
                <fullName>Suppliers Quotations</fullName>
            </value>
            <value>
                <fullName>Variations / Change Requested</fullName>
            </value>
            <value>
                <fullName>Plan Of Subdivision</fullName>
            </value>
            <value>
                <fullName>Load Calculation</fullName>
            </value>
            <value>
                <fullName>Development Plans</fullName>
            </value>
            <value>
                <fullName>Property Sketch/Site Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine1__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine1__c</fullName>
    <label>Invoice Type Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine2__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine2__c</fullName>
    <label>Invoice Type Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/InvoiceTypeLine3__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTypeLine3__c</fullName>
    <label>Invoice Type Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine1__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine1__c</fullName>
    <label>Material Code Line 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine2__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine2__c</fullName>
    <label>Material Code Line 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/MaterialCodeLine3__c.field-meta.xml
<CustomField>
    <fullName>MaterialCodeLine3__c</fullName>
    <label>Material Code Line 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>InvoiceTypeLine3__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Material_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Artefacts (Payer)</relationshipLabel>
    <relationshipName>Artefacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Artefacts</relationshipLabel>
    <relationshipName>Artefacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/SAPCustomer__c.field-meta.xml
<CustomField>
    <fullName>SAPCustomer__c</fullName>
    <label>SAP Customer</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Salesforce Cloud</fullName>
            </value>
            <value>
                <fullName>SiteCore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending Payment&quot;</defaultValue>
    <description>Status field with values</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending Reconciliation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Artefact__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <description>Record type for invoice</description>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ASPContact__c.field-meta.xml
<CustomField>
    <fullName>ASPContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (ASP Contact)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/AuthorizedRepresentativeContact__c.field-meta.xml
<CustomField>
    <fullName>AuthorizedRepresentativeContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Representative Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Authorized Representative Contact)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PropertyOwnerContact__c.field-meta.xml
<CustomField>
    <fullName>PropertyOwnerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Owner Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Property Owner)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ReferenceNumber__c</fullName>
    <description>Reference number of the application</description>
    <label>Reference Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Request_Invoice.recordType-meta.xml
<RecordType>
    <fullName>Request_Invoice</fullName>
    <active>true</active>
    <label>Request Invoice</label>
</RecordType>

force-app/main/default/classes/TVE_RequestInvoiceUtility.cls
/*
@author  : pavan.dave@ausnetservices.com.au
@created : 05 Mar  2020
@Description : Controller class for LWC tveRejectInvoice, tveRejectInvoiceTask
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
30-Apr-20       dave.pavan@in.ibm.com         Added "without sharing" since system show list of contacts to external user for payer selection
10-May-202      Prateek Gupta                 Updated createTask method for defect TV-3219
-----------------------------------------------------------------------------------------
*/

public without sharing class TVE_RequestInvoiceUtility {
    public static ID requestInvoiceType = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('Request_Invoice').getRecordTypeId();
    public static ID Artefact_Invoice_RTId = Schema.SObjectType.Artefact__c.getRecordTypeInfosByDeveloperName().get('Invoice').getRecordTypeId();

    public static final string CLASSIFICATION_INVOICE = 'Invoice';
    public static final string SOURCE_SF_CLOUD = 'Salesforce Cloud';
    
    @AuraEnabled(cacheable=true)
    public static List<ContactWrapper> getContactWrapper(string prjId, string artId){
        system.debug('in get contact wrapper');
        
        List<ContactWrapper> lstContWrpr = new List<ContactWrapper>();
        Project__c proj=new Project__c();
        
        if(String.isNotEmpty(prjId)){
         proj = [SELECT Id, AuthorizedRepresentativeContact__c, ASPContact__c, PropertyOwnerContact__c
                           FROM Project__c
                           WHERE Id =: prjId];
        }
        
        Artefact__c art;        
        if(String.isNotEmpty(artId))
        {
            art = [SELECT Id, Payer__c FROM Artefact__c WHERE Id =: artId];                               
        }

        Set<Id> setContId=new set<Id>();
        if(proj!=null){
        if(proj.AuthorizedRepresentativeContact__c != null)
            setContId.add(proj.AuthorizedRepresentativeContact__c);
        if(proj.ASPContact__c != null)
            setContId.add(proj.ASPContact__c);
        if(proj.PropertyOwnerContact__c != null)
            setContId.add(proj.PropertyOwnerContact__c);}
        system.debug('setContId:'+setContId);
        if(!setContId.isEmpty())
        {
            Map<Id, Contact> mapCon = new Map<Id, Contact>([SELECT Id, FirstName, LastName, AccountId, Account.IsPersonAccount,
                                                                    Account.BillingStreet, Account.BillingCity,
                                                                    Account.BillingPostalCode, Account.BillingState, 
                                                                    Account.PersonMailingStreet, Account.PersonMailingCity, 
                                                                    Account.PersonMailingPostalCode, Account.PersonMailingState
                                                            FROM Contact
                                                            WHERE Id IN : setContId]);
            
            if(!mapCon.isEmpty())
            {
                ContactWrapper cWrpr;
                Contact c;
                String payerId;
                system.debug('mapCon-->'+mapCon.keySet());
                for(Id conItemId: mapCon.keySet())
                {   
                    c = mapCon.get(conItemId);
                    if((String.isNotEmpty(artId)  && art != null & art.Payer__c != null) )
                    {
                        //----------------------------------------------//
                        //------ TV-368 For Request Invoice LWC--------//
                        //---------------------------------------------//
                        payerId = art.Payer__c;
                        if(c.Id == payerId || c.Id == payerId.mid(0, 15))
                        {
                            // DO NOT ADD TO THE LIST
                        }                            
                        else
                        {
                            cWrpr = new ContactWrapper(c, false);                            
                    		lstContWrpr.add(cWrpr);         
                        }                            
                    }
                    
                    else
                    {
                        //----------------------------------------------//
                        //------ TV-158 For Request Invoice LWC--------//
                        //---------------------------------------------//
                        cWrpr = new ContactWrapper(c, false);                               
                    	lstContWrpr.add(cWrpr);         
                    }
                    system.debug('cWrpr-->'+cWrpr);           
                }
            }
        }
        system.debug('lstContWrpr:'+lstContWrpr);
        return lstContWrpr;
    }

    //TV-386
    @AuraEnabled
    public static task createTask(Id projectId,String name,id taskId){
        system.debug('taskid:'+taskid);
        CustomNotificationType notiID=[SELECT Id, DeveloperName FROM CustomNotificationType where DeveloperName='Task_Assignment']; 
        
        //Added by Prateek for TV-3219 - Start
        Task taskToComplete = [SELECT Id, status FROM Task where Id =:taskId]; 
        taskToComplete.Status = 'Completed';
        update taskToComplete;  
        //Added by Prateek for TV-3219 - ENd

        Task taskToCreate=new Task();
        project__c prj=[select id,ReferenceNumber__c,Name,ownerId from project__c where id =:projectId];
        taskToCreate.RecordTypeId=requestInvoiceType;
        taskToCreate.subject='Request Invoice -'+prj.Name;
        taskToCreate.Description='A request has been submitted for an invoice in another payers name - please request an invoice in the following name:'+name;
        taskToCreate.ActivityDate=system.today()+3;
        String sub = 'Request Invoice -'+prj.Name;

        //For TV-1808, To fix strange test class failure
        if(!Test.isRunningTest())
            taskToCreate.OwnerId=prj.ownerId;
        
        taskToCreate.WhatId=prj.id;
        taskToCreate.Status='Not Started';
        taskToCreate.Priority='Normal';
        insert taskToCreate;
        
        system.debug('task created:'+taskToCreate.id);
        if(taskToCreate.id !=null)
        {
            //Added by Prateek for TV-3219
            //Flow.Interview flow = new Flow.Interview.Notification_on_Task_Creation(new map<String,Object>{'recordID' => taskToCreate.id,'customNotiID'=>notiID.id,'completeTaskId'=>taskId});     
            Flow.Interview flow = new Flow.Interview.Notification_on_Task_Creation(new map<String,Object>{'customNotiID'=>notiID.id, 'recordID'=>taskToCreate.id, 'subject'=>sub, 'assignedto'=>prj.ownerId,'completeTaskId'=>null});
            flow.start();
        }
        
        return taskToCreate;
    }

    //TV-158
    @AuraEnabled(cacheable = true)
    public static Boolean hasWarningMsg(String prjRecId){
        Boolean showWarning = false;
        List<Artefact__c> lstArt = new List <Artefact__c>([SELECT Id FROM Artefact__c 
                                                            WHERE Project__c =: prjRecId 
                                                            AND RecordTypeId =: Artefact_Invoice_RTId]);
        if(!lstArt.isEmpty())
        {
            List<Id> lstArtIds = new List<Id>();
            for(Artefact__c item: lstArt)
            {
                lstArtIds.add(item.Id);
            }

            List<Integration_Task__c> lstIntTask = new List<Integration_Task__c>([SELECT Id FROM Integration_Task__c
                                                                                        WHERE ParentId__c IN: lstArtIds
                                                                                            AND Status__c IN('Ready', 'In Progress')]);
            if(!lstIntTask.isEmpty())
            {
                showWarning = true;
            }                                                         
        }
        return showWarning;        
    }

    //TV-158
    @AuraEnabled
    public static void createArtefact(Id payerId, String invTy1, String invTy2, String invTy3,
                                      Double totAmt, String mCode1, String mCode2, String mCode3,
                                      Id projId, Double amt1, Double amt2, Double amt3){
        Contact conObj = [select id, AccountId, Account.SAPCustomer__c From Contact where id=:payerId];
        system.debug('conObj123'+conObj);
        Artefact__c art = new Artefact__c();
        system.debug('payerId-->'+payerId);
        system.debug('mCode1-->'+mCode1);
        system.debug('totAmt-->'+totAmt);
        art.Project__c = projId;
        art.Classification__c = CLASSIFICATION_INVOICE;
        art.Payer__c = payerId;
        art.Account__c = conObj.AccountId;
        art.Source__c = SOURCE_SF_CLOUD;                                               
        art.InvoiceTypeLine1__c = invTy1;
        art.MaterialCodeLine1__c = mCode1;
        art.AmountLine1ExGST__c = amt1;
        art.NetAmount__c = amt1;
        if(conObj.Account.SAPCustomer__c!=null){
        	art.Bill_To__c = conObj.Account.SAPCustomer__c;
        }
        if(invTy2 != null && mCode2 != null && amt1 != null){
            art.InvoiceTypeLine2__c = invTy2;
            art.MaterialCodeLine2__c = mCode2;
            art.AmountLine2ExGST__c = amt2;
            art.NetAmount__c += amt2;
        }
        if(invTy3 != null && mCode3 != null && amt3 != null){
            art.InvoiceTypeLine3__c = invTy3;
            art.MaterialCodeLine3__c = mCode3;
            art.AmountLine3ExGST__c = amt3;
            art.NetAmount__c += amt3;
        }
        art.TotalAmount__c = totAmt;
        art.Additional_Invoice__c = true;
        insert art;
        system.debug('art-->'+art.Id);
    }

    public class ContactWrapper
    {
        public ContactWrapper(Contact con, Boolean isSel)
        {
            this.contactId = con.Id;
            String name='';
            name+=con.FirstName+ ' '+con.LastName;
            this.contactName=name;
            
            String addr = '';
            if(con.Account.IsPersonAccount)
            {                
                if(String.isNotEmpty(con.Account.PersonMailingStreet))
                    addr+= con.Account.PersonMailingStreet + ', ';
                if(String.isNotEmpty(con.Account.PersonMailingCity))
                    addr+= con.Account.PersonMailingCity + ', ';
                if(String.isNotEmpty(con.Account.PersonMailingState))
                    addr+= con.Account.PersonMailingState + ' ';
                if(String.isNotEmpty(con.Account.PersonMailingPostalCode))
                    addr+= con.Account.PersonMailingPostalCode;
                
                this.contactAddress = addr;
            }
            else
            {
                if(String.isNotEmpty(con.Account.BillingStreet))
                    addr+= con.Account.BillingStreet + ', ';
                if(String.isNotEmpty(con.Account.BillingCity))
                    addr+= con.Account.BillingCity + ', ';
                if(String.isNotEmpty(con.Account.BillingState))
                    addr+= con.Account.BillingState + ' ';
                if(String.isNotEmpty(con.Account.BillingPostalCode))
                    addr+= con.Account.BillingPostalCode;
                
                this.contactAddress = addr;
            }

            this.isSelected = isSel;
        }

        @AuraEnabled public String contactId;
        @AuraEnabled public String contactName;
        @AuraEnabled public String contactAddress;
        @AuraEnabled public boolean isSelected;
    }
}