force-app/main/default/objects/Account/fields/SFDCUniqueId__c.field-meta.xml
<CustomField>
    <fullName>SFDCUniqueId__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>SFDC Unique Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/CustomerSets__x.object-meta.xml
<CustomObject>
    <description>CustomerSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>CustomerSets</externalName>
    <label>CustomerSets</label>
    <pluralLabel>CustomerSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomerSets__x/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <externalDeveloperName>City</externalDeveloperName>
    <label>City</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/CustName1__c.field-meta.xml
<CustomField>
    <fullName>CustName1__c</fullName>
    <description>CustName1</description>
    <externalDeveloperName>CustName1</externalDeveloperName>
    <label>CustName1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/CustName2__c.field-meta.xml
<CustomField>
    <fullName>CustName2__c</fullName>
    <description>CustName2</description>
    <externalDeveloperName>CustName2</externalDeveloperName>
    <label>CustName2</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/CustNumber__c.field-meta.xml
<CustomField>
    <fullName>CustNumber__c</fullName>
    <description>CustNumber</description>
    <externalDeveloperName>CustNumber</externalDeveloperName>
    <label>CustNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <description>CustomerType</description>
    <externalDeveloperName>CustomerType</externalDeveloperName>
    <label>CustomerType</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Key</description>
    <externalDeveloperName>Key</externalDeveloperName>
    <label>Key</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/MobileNumber__c.field-meta.xml
<CustomField>
    <fullName>MobileNumber__c</fullName>
    <description>MobileNumber</description>
    <externalDeveloperName>MobileNumber</externalDeveloperName>
    <label>MobileNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>ObjectName</description>
    <externalDeveloperName>ObjectName</externalDeveloperName>
    <label>ObjectName</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Postalcode__c.field-meta.xml
<CustomField>
    <fullName>Postalcode__c</fullName>
    <description>Postalcode</description>
    <externalDeveloperName>Postalcode</externalDeveloperName>
    <label>Postalcode</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Previouseaccno__c.field-meta.xml
<CustomField>
    <fullName>Previouseaccno__c</fullName>
    <description>Previouseaccno</description>
    <externalDeveloperName>Previouseaccno</externalDeveloperName>
    <label>Previouseaccno</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region</description>
    <externalDeveloperName>Region</externalDeveloperName>
    <label>Region</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/SourceSystem__c.field-meta.xml
<CustomField>
    <fullName>SourceSystem__c</fullName>
    <description>SourceSystem</description>
    <externalDeveloperName>SourceSystem</externalDeveloperName>
    <label>SourceSystem</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Street1__c.field-meta.xml
<CustomField>
    <fullName>Street1__c</fullName>
    <description>Street1</description>
    <externalDeveloperName>Street1</externalDeveloperName>
    <label>Street1</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Street2__c.field-meta.xml
<CustomField>
    <fullName>Street2__c</fullName>
    <description>Street2</description>
    <externalDeveloperName>Street2</externalDeveloperName>
    <label>Street2</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSets__x/fields/Telephone__c.field-meta.xml
<CustomField>
    <fullName>Telephone__c</fullName>
    <description>Telephone</description>
    <externalDeveloperName>Telephone</externalDeveloperName>
    <label>Telephone</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/AuthorisedRepresentative__c.field-meta.xml
<CustomField>
    <fullName>AuthorisedRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TV-1422</description>
    <label>Authorised Representative</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Authorised Representative)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City portion of the applicant&apos;s address, for example, San Francisco. Up to 40 characters are allowed in this field.</description>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country portion of applicant&apos;s address. Entry is selected from a picklist of standard values, or entered as text. Up to 80 characters are allowed if the field is a text field.</description>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email address of applicant. Must be a valid email address in the form: jsmith@acme.com. Up to 80 characters are allowed in this field.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/MobileNumber__c.field-meta.xml
<CustomField>
    <fullName>MobileNumber__c</fullName>
    <description>Stores the mobile number of the persona who is creating the application</description>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>ZIP code or postal code portion of the lead’s address. Up to 20 characters are allowed in this field.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/SiteOwner__c.field-meta.xml
<CustomField>
    <fullName>SiteOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TV-1422</description>
    <label>Site Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects (Site Owner)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TVE_SAPInteg_GetCustomerTest.cls
@isTest
private class TVE_SAPInteg_GetCustomerTest{

    public static final string testUserEmail = 'testuser@TVECustomerDetailsSAP.com';
    public static final string CON_TYPE = 'IDIC';
    public static final string PROGRESS_BAR_STATUS = 'Prelim estimate accepted';
	@testSetup static void setup(){

		//Create User
		User testUser = TVE_TestUtility.createTestUser(testUserEmail);
		insert testUser;

		Account testAccount = TVE_TestUtility.createPersonAccount('acctName', testUserEmail);
		testAccount.PersonMailingStreet = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean m';   		
		insert testAccount;
		
		Account testAcc1 = TVE_TestUtility.createPersonAccount('acctName1', testUserEmail);
		insert testAcc1;       

		
		eSignSettings__c eSignObj = eSignSettings__c.getInstance(); 
		eSignObj.AES_Key__c = 'K6SufKgGcs6r54OTreZokg==';
		insert eSignObj;
			
		List<Project__c> lstProj = new List<Project__c>();
		lstProj.add(TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE));
		lstProj[0].AuthorisedRepresentative__c = testAccount.Id;
		//lstProj.add(TVE_TestUtility.createProject('test',PROGRESS_BAR_STATUS,CON_TYPE));
		lstProj[0].SiteOwner__c = testAcc1.Id;
         lstProj.add(TVE_TestUtility.createProject('test1',PROGRESS_BAR_STATUS,CON_TYPE));
		Insert lstProj;
        
        Map<Id,String> recordMap = new Map<Id,String>(); 
        recordMap.put(lstProj[0].id, lstProj[0].id);
        Map<String,String> creatIntTaskMap = new Map<String,String>();
        creatIntTaskMap.put('Operation__c', 'Get');
        creatIntTaskMap.put('SObject__c', 'Project__c');       
        creatIntTaskMap.put('Type__c', 'GetCustomer');
        creatIntTaskMap.put('Status__c', 'In Progress');        
        TVE_IntegUtility.CreateInteTask(recordMap,creatIntTaskMap); 
        
        Map<Id,String> recordMapReady = new Map<Id,String>(); 
        recordMapReady.put(lstProj[1].id, lstProj[1].id);
        Map<String,String> creatIntTaskMapReady = new Map<String,String>();
        creatIntTaskMapReady.put('Operation__c', 'Get');
        creatIntTaskMapReady.put('SObject__c', 'Project__c');       
        creatIntTaskMapReady.put('Type__c', 'GetCustomer');
        creatIntTaskMapReady.put('Status__c', 'Ready');  
        TVE_IntegUtility.CreateInteTask(recordMapReady,creatIntTaskMapReady); 
		 
	}

    @isTest static void testMethod1() {
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        List<Account> accList = [SELECT Id, SFDCUniqueId__c from Account];
     
         CustomerSets__x mockedCust1 = new CustomerSets__x(
                    City__c = 'Melbourne',
                    Country__c = 'AU',
                    CustName1__c = 'Test',
                    CustName2__c = 'Customer',
                    CustomerType__c = 'ELE',
                    Email__c = 'test@test.com',
                    Key__c = 'NC',
                    MsgId__c = 'a0E2N000000EDvC',
                    MobileNumber__c = '911',
                    ObjectName__c = 'CreateCustomer',
                    SourceSystem__c = 'Salesforce',
                    TargetSystem__c = 'ERP',
                    Postalcode__c = '3000', 
                    Previouseaccno__c = accList[0].SFDCUniqueId__c,
                    Region__c = 'VIC',
                    Street1__c = 'Unit 30',
                    Street2__c = '20 King Street',
                    Telephone__c = '911',
                    CustNumber__c = 'Cust0001' 
                );        
     	 	CustomerSets__x mockedCust2 = new CustomerSets__x(
                    City__c = 'Melbourne',
                    Country__c = 'AU',
                    CustName1__c = 'Test',
                    CustName2__c = 'Customer',
                    CustomerType__c = 'ELE',
                    Email__c = 'test@test.com',
                    Key__c = 'NC',
                    MsgId__c = 'a0E2N000000EDvC',
                    MobileNumber__c = '9116456456',
                    ObjectName__c = 'CreateCustomer',
                    SourceSystem__c = 'Salesforce',
                    TargetSystem__c = 'ERP',
                    Postalcode__c = '3000555', 
                    Previouseaccno__c = accList[1].SFDCUniqueId__c,
                    Region__c = 'VIC',
                    Street1__c = 'Unit 30',
                    Street2__c = '20 King Street',
                    Telephone__c = '911545435',
                    CustNumber__c = 'Cust0002' 
                );                
				
                TVE_SAPInteg_GetCustomer.mockedExtCust.add(mockedCust1);     
                TVE_SAPInteg_GetCustomer.mockedExtCust.add(mockedCust2);
        		TVE_SAPInteg_GetCustomer.mockedAccount.add(accList[0]);
        		TVE_SAPInteg_GetCustomer.mockedAccount.add(accList[1]);
        		TVE_SAPInteg_GetCustomer.ExceptionFlag = false;
        
            TVE_SAPInteg_GetCustomer getCustomer =  new TVE_SAPInteg_GetCustomer();       
            system.runas(testUser){                        
                System.enqueueJob(getCustomer);
            }       
    }	
    
     @isTest static void testMethod2() {
        User testUser = [SELECT Id FROM User WHERE email=: testUserEmail LIMIT 1];
        List<Account> accList = [SELECT Id, SFDCUniqueId__c from Account];
     
         CustomerSets__x mockedCust1 = new CustomerSets__x(
                    City__c = 'Melbourne',
                    Country__c = 'AU',
                    CustName1__c = 'Test',
                    CustName2__c = 'Customer',
                    CustomerType__c = 'ELE',
                    Email__c = 'test@test.com',
                    Key__c = 'NC',
                    MsgId__c = 'a0E2N000000EDvC',
                    MobileNumber__c = '911',
                    ObjectName__c = 'CreateCustomer',
                    SourceSystem__c = 'Salesforce',
                    TargetSystem__c = 'ERP',
                    Postalcode__c = '3000', 
                    Previouseaccno__c = accList[0].SFDCUniqueId__c,
                    Region__c = 'VIC',
                    Street1__c = 'Unit 30',
                    Street2__c = '20 King Street',
                    Telephone__c = '911',
                    CustNumber__c = 'Cust0001' 
                );        
     	 	CustomerSets__x mockedCust2 = new CustomerSets__x(
                    City__c = 'Melbourne',
                    Country__c = 'AU',
                    CustName1__c = 'Test',
                    CustName2__c = 'Customer',
                    CustomerType__c = 'ELE',
                    Email__c = 'test@test.com',
                    Key__c = 'NC',
                    MsgId__c = 'a0E2N000000EDvC',
                    MobileNumber__c = '9116456456',
                    ObjectName__c = 'CreateCustomer',
                    SourceSystem__c = 'Salesforce',
                    TargetSystem__c = 'ERP',
                    Postalcode__c = '3000555', 
                    Previouseaccno__c = accList[1].SFDCUniqueId__c,
                    Region__c = 'VIC',
                    Street1__c = 'Unit 30',
                    Street2__c = '20 King Street',
                    Telephone__c = '911545435',
                    CustNumber__c = 'Cust0002' 
                );                
				
                TVE_SAPInteg_GetCustomer.mockedExtCust.add(mockedCust1);     
                TVE_SAPInteg_GetCustomer.mockedExtCust.add(mockedCust2);
        		TVE_SAPInteg_GetCustomer.mockedAccount.add(accList[0]);
         		TVE_SAPInteg_GetCustomer.mockedAccount.add(accList[1]);
        		TVE_SAPInteg_GetCustomer.ExceptionFlag = true;
            TVE_SAPInteg_GetCustomer getCustomer =  new TVE_SAPInteg_GetCustomer();       
            system.runas(testUser){                        
                System.enqueueJob(getCustomer);
            }       
    }	
    
}