force-app/main/default/objects/Connection_Point__c/Connection_Point__c.object-meta.xml
<CustomObject>
    <label>Connection Point</label>
    <nameField>
        <label>Connection ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connection Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Point__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <externalId>true</externalId>
    <label>NMI</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/Meter_Install_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Meter_Install_Type_Code__c</fullName>
    <label>Meter Install Type Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/Meter_Ref__c.field-meta.xml
<CustomField>
    <fullName>Meter_Ref__c</fullName>
    <label>Meter Ref</label>
    <length>255</length>
    <referenceTo>MeterDataSets__x</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/objects/DER_Application__c/fields/NMI__c.field-meta.xml
<CustomField>
    <fullName>NMI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMI</label>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>DER Applications</relationshipLabel>
    <relationshipName>DER_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MeterDataSets__x/MeterDataSets__x.object-meta.xml
<CustomObject>
    <description>MeterDataSets</description>
    <externalDataSource>AusNet_OData</externalDataSource>
    <externalName>MeterDataSets</externalName>
    <label>MeterDataSets</label>
    <pluralLabel>MeterDataSets</pluralLabel>
</CustomObject>

force-app/main/default/objects/MeterDataSets__x/fields/InstallTypeCode__c.field-meta.xml
<CustomField>
    <fullName>InstallTypeCode__c</fullName>
    <description>InstallTypeCode</description>
    <externalDeveloperName>InstallTypeCode</externalDeveloperName>
    <label>InstallTypeCode</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeterDataSets__x/fields/Nmi__c.field-meta.xml
<CustomField>
    <fullName>Nmi__c</fullName>
    <description>Nmi</description>
    <externalDeveloperName>Nmi</externalDeveloperName>
    <label>Nmi</label>
    <length>128</length>
    <referenceTargetField>Connection_Point__c.NMI__c</referenceTargetField>
    <referenceTo>Connection_Point__c</referenceTo>
    <relationshipLabel>MeterDataSets</relationshipLabel>
    <relationshipName>MeterDataSets</relationshipName>
    <type>IndirectLookup</type>
</CustomField>

force-app/main/default/objects/MeterDataSets__x/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <description>SerialNumber</description>
    <externalDeveloperName>SerialNumber</externalDeveloperName>
    <label>SerialNumber</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DER_Application_Util.cls
/*
  @author  : pavan.dave@ausnetservices.com.au
  @created : 15 Oct 2019
  @Description : Util Class for DER_Application__c Trigger
  -----------------------------------------------------------------------------------------
  Change log
  -----------------------------------------------------------------------------------------
  Date                  Name                           Description
  -----------------------------------------------------------------------------------------
  12-Nov-19            Pavan Dave                     Since Integration Profile user not able to query external object, chaning to 'without sharing' (CMC-1595)
  -----------------------------------------------------------------------------------------
*/

public without sharing class DER_Application_Util {

	public static Boolean isRunning_PopulateExternalMeter = false;
    public static String DASH = '-';
	@TestVisible private static List<MeterDataSets__x> mockedExtMtr = new List<MeterDataSets__x>();

	@future
	public static void PopulateExternalMeter(List<Id> validExtMeter_Pop, List<Id> validExtMeter_Clear)
	{
		isRunning_PopulateExternalMeter = true;
		List<DER_Application__c> lstDERAppUpd;
		DER_Application__c derApp;
		try{
			if (!validExtMeter_Pop.isEmpty())
			{
				lstDERAppUpd = new List<DER_Application__c>();
				Map<Id, DER_Application__c> mapDERApp = new Map<Id, DER_Application__c>([SELECT Id, Meter_Ref__c, Meter_Install_Type_Code__c,
																								NMI__r.Nmi__c, Meter_Number__c
																							FROM DER_Application__c
																							WHERE Id IN: validExtMeter_Pop]);

				List<String> lstExternalId = new List<String>();
				for(DER_Application__c item: mapDERApp.values())
				{
					if(item.NMI__c != null && String.isNotBlank(item.NMI__r.NMI__c))
					{
						lstExternalId.add(item.NMI__r.NMI__c +DASH+item.Meter_Number__c);
					}
				}
				if(!lstExternalId.isEmpty())
				{
					List <MeterDataSets__x> lstExtMtr;
					if(!mockedExtMtr.isEmpty())
					{
						lstExtMtr = mockedExtMtr;
					}
					else
					{
						lstExtMtr = new List<MeterDataSets__x> ([SELECT Id, ExternalId, Nmi__c, InstallTypeCode__c,
																		SerialNumber__c
																	FROM MeterDataSets__x
																	WHERE ExternalId IN: lstExternalId]);
					}
					Map<String, MeterDataSets__x> mapSerNumExtMtr = new Map<String, MeterDataSets__x>();
					for(MeterDataSets__x item: lstExtMtr)
					{
						mapSerNumExtMtr.put(item.SerialNumber__c, item);
					}

					for(Id item: mapDERApp.keySet())
					{
						derApp = mapDERApp.get(item);

						if(mapSerNumExtMtr.containsKey(derApp.Meter_Number__c)
						&& derApp.Meter_Number__c == (mapSerNumExtMtr.get(derApp.Meter_Number__c)).SerialNumber__c)
						{
							derApp.Meter_Ref__c = (mapSerNumExtMtr.get(derApp.Meter_Number__c)).ExternalId;
							derApp.Meter_Install_Type_Code__c = (mapSerNumExtMtr.get(derApp.Meter_Number__c)).InstallTypeCode__c;
							lstDERAppUpd.add(derApp);
						}
						else
						{
							derApp.Meter_Ref__c = null;
							derApp.Meter_Install_Type_Code__c = null;
							lstDERAppUpd.add(derApp);
						}
					}

					if(!lstDERAppUpd.isEmpty()) update lstDERAppUpd;
				}
			}

			if (!validExtMeter_Clear.isEmpty())
			{
				Map<Id, DER_Application__c> mapDERApp = new Map<Id, DER_Application__c>([SELECT Id, Meter_Ref__c, Meter_Install_Type_Code__c
																							FROM DER_Application__c
																							WHERE Id IN: validExtMeter_Clear]);
				lstDERAppUpd = new List<DER_Application__c>();
				for(Id item: mapDERApp.keySet())
				{
					derApp = mapDERApp.get(item);
					derApp.Meter_Ref__c = null;
					derApp.Meter_Install_Type_Code__c = null;
					lstDERAppUpd.add(derApp);
				}

				if(!lstDERAppUpd.isEmpty()) update lstDERAppUpd;
			}
		}catch(Exception e){
            system.debug('DER_Application_Util.PopulateExternalMeter'+'Exception Occurred. Message: ' + e.getMessage() 
                                        + ' StackTrace: ' + e.getStackTraceString()
                                        + ' Type: ' + e.getTypeName()
                                        + ' Cause: ' + e.getCause());
        }
	}
}