force-app/main/default/objects/Contact/fields/AD_User_ID__c.field-meta.xml
<CustomField>
    <fullName>AD_User_ID__c</fullName>
    <label>AD User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <label>Message ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Integration error message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Integration status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Azure create customer</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
            <value>
                <fullName>upsertRecordData</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ApplicantContact__c.field-meta.xml
<CustomField>
    <fullName>ApplicantContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Applicant Contact)</relationshipLabel>
    <relationshipName>Projects_App_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TVE_Azure_Call__mdt/TVE_Azure_Call__mdt.object-meta.xml
<CustomObject>
    <label>TVE Azure Call</label>
    <pluralLabel>TVE Azure Calls</pluralLabel>
</CustomObject>

force-app/main/default/classes/TVE_SF_Azure_IntegrationTesting.cls
public class TVE_SF_Azure_IntegrationTesting{

 @future(callout = true)
 public static void  callAzureAPI(Id conId,List<Id> ids){
        Contact con =[select id,firstname,lastname,name,Phone,MobilePhone,Email from contact where id=:conId];
        List<Project__c> relatedProjList = [select id, ApplicantContact__c from  Project__c where id IN : ids];
        String adUserId;
        HttpResponse res1;
        String accessToken;
        List<String> emailList = new List<String>();
        emailList.add(con.Email);        
        accessToken=TVE_SF_Azure_Utility.getAccessToken();
        if(accessToken!=null)
        {
            String password=TVE_SF_Azure_Utility.generatePassword(35);
            
            Http h1 = new Http();
            HttpRequest req1 = new HttpRequest();
            
            req1.setHeader('Authorization','Bearer '+accessToken);
            req1.setHeader('Content-Type', 'application/json');
            req1.setHeader('SdkVersion','postman-graph/v1.0');
            req1.setHeader('Accept', 'application/json');
            req1.setEndpoint('https://graph.microsoft.com/v1.0/users');
            req1.setMethod('POST');
            
            TVE_Azure_Call__mdt azureInfo=[SELECT Issuer__c FROM TVE_Azure_Call__mdt WHERE DeveloperName='Azure_User_Creation'];

            passwordProfile pword = new passwordProfile(password, false);
            identities emailId = new identities(TVE_IntegUtility.checkString(con.Email), TVE_IntegUtility.checkString(azureInfo.Issuer__c));
            JSONGenerator gen = JSON.createGenerator(true);  
            gen.writeStartObject();      
            gen.writeStringField('displayName', TVE_IntegUtility.checkString(con.Name));//required
            gen.writeStringField('passwordPolicies','DisablePasswordExpiration');
            gen.writeFieldName('passwordProfile');
            gen.writeObject(pword);
            gen.writeStringField('givenName',TVE_IntegUtility.checkString(con.FirstName));
            gen.writeStringField('surname', TVE_IntegUtility.checkString(con.LastName));
            gen.writeStringField('mobilePhone',formatInternationalMobile(TVE_IntegUtility.checkString(con.MobilePhone)));
            gen.writeFieldName('identities');
            gen.writeStartArray();
            gen.writeObject(emailId);
            gen.writeEndArray();
            
            gen.writeEndObject();    
            
            String reqbody1 = gen.getAsString();
            
            System.debug('jsonMaterials '+reqbody1);
            req1.setBody(reqbody1);  
            if(!Test.isRunningTest()){
                res1 = h1.send(req1);
                
                System.debug('response in azure '+res1.getBody()+'response'+res1);
                if(res1.getStatusCode()==201){
                    AzureResponse AZ=(AzureResponse)JSON.deserialize(res1.getBody(),AzureResponse.class);
                    if(AZ.id!=null){
                        //Flow used to introduce delay of email
                        Flow.Interview flow = new Flow.Interview.Delay_Registration_Emails(new map<String,Object>{
                            'Uname' => con.Email,
                            'Pword' => password, 
                            'Fname'  => con.FirstName});     
                        flow.start();
                        //TVE_SF_Azure_Utility.sendAzureEmail(con.Email,password,con);
                        adUserId=AZ.id;
                        if(adUserId!=null){
                        con.AD_User_ID__c = adUserId;
                        update con;
                        }
                    }
                }
                else{
                    //AzureResponse AZ=(AzureResponse)JSON.deserialize(res1.getBody(),AzureResponse.class);
                    system.debug('response message:'+res1.getBody());
                    createIntegrationLog(res1.getBody(),relatedProjList,con.id);
                }
            }       
            
        }
        
        System.debug('adUserId'+adUserId);
    }
    
    
    
    public static void createIntegrationLog(String response,List<Project__c> projIds,Id contactId)
    {
        Integration_Log__c intLog=new Integration_Log__c();
        intLog.Error_Message__c='Error on Azure customer creation for below list of Projects:'+projIds+'and Contact:'+contactId+'-'+response;         
        intLog.Status__c='Failed';
        intLog.Type__c='Azure create customer';
        insert intLog;
    }
    public class passwordProfile { 
        String password;
        Boolean forceChangePasswordNextSignIn; 
        public passwordProfile(String s, Boolean b) { 
            password = s; 
            forceChangePasswordNextSignIn = b;
        }
    }
    
    public static String formatInternationalMobile(String mobile){
        String formattedMobile= mobile.replaceAll( '\\s+', '');
        formattedMobile='+61 ' + formattedMobile.substring(1);
        System.debug('formattedMobile' + formattedMobile);
        return formattedMobile;
    }
    
    
    public class identities { 
        String signInType;
        String issuer;
        String issuerAssignedId;
        public identities(String s, String iss) { 
            signInType = 'emailAddress'; 
            issuer = iss;
            issuerAssignedId = s;
        }
    }
    
    public class AzureResponse{
        public String id ;
        public String statusMessage;
    }

}