force-app/main/default/objects/Contact/fields/UserCommunityLicense__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityLicense__c</fullName>
    <label>User Community License</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Community Plus Login</fullName>
            </value>
            <value>
                <fullName>Partner Community</fullName>
            </value>
            <value>
                <fullName>Unregistered Community User</fullName>
                <default>true</default>
                <label>Unregistered Community User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eSignSettings__c/eSignSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to get record data.</description>
    <label>eSign Settings</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ApplicantContact__c.field-meta.xml
<CustomField>
    <fullName>ApplicantContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Applicant Contact)</relationshipLabel>
    <relationshipName>Projects_App_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/CommunityChatterLink__c.field-meta.xml
<CustomField>
    <fullName>CommunityChatterLink__c</fullName>
    <label>Community Chatter Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/IsPropertyOwner__c.field-meta.xml
<CustomField>
    <fullName>IsPropertyOwner__c</fullName>
    <description>Property owner of the installation place</description>
    <label>Is Property Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/RelationshipToOwner__c.field-meta.xml
<CustomField>
    <fullName>RelationshipToOwner__c</fullName>
    <label>Relationship To Owner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered Electrical Contractor (REC)</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Accredited Service Provider - AusNet Services</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Family Member/Friend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/SitecoreAcceptanceLink__c.field-meta.xml
<CustomField>
    <fullName>SitecoreAcceptanceLink__c</fullName>
    <label>Sitecore Acceptance Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TriageDescription__c.field-meta.xml
<CustomField>
    <fullName>TriageDescription__c</fullName>
    <label>Triage Action Required</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TVE_Project_URL__c.field-meta.xml
<CustomField>
    <fullName>TVE_Project_URL__c</fullName>
    <label>TVE Project URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/UploadDocumentsLink__c.field-meta.xml
<CustomField>
    <fullName>UploadDocumentsLink__c</fullName>
    <label>Upload Documents Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/WorkCode__c.field-meta.xml
<CustomField>
    <fullName>WorkCode__c</fullName>
    <description>Mandatory on SAP to create the master work order.</description>
    <label>Work Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVE_Account_Util.cls
/*
@author  : dave.pavan@in.ibm.com
@created : 29 May 2020
@Description : Class for Account Util method for TVE team
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-------------------------------------------------------------------------------------------------------
NA                  NA                                NA
-------------------------------------------------------------------------------------------------------
*/

public without sharing class TVE_Account_Util {
    
    public static void UpdateProjectUrl_On_CustomerUpdate(Set<id>ContactIds)
    {
        eSignSettings__c eSign = eSignSettings__c.getInstance();
        System.debug('eSign' + eSign);
        if(eSign != null)
        {
            if(eSign.AES_Key__c != null)
            {   
                if(ContactIds!=null)
                {
                    system.debug('ContactIds:'+ContactIds);
                    
                    List<Project__c>projToUpdate=new List<Project__c>();

                    for(project__c proj :[SELECT Id, TVE_Project_URL__c, TriageDescription__c, WorkCode__c,
                                          ApplicantContact__c, ApplicantContact__r.UserCommunityLicense__c,
                                          IsPropertyOwner__c, RelationshipToOwner__c,
                                          CommunityChatterLink__c, UploadDocumentsLink__c, SitecoreAcceptanceLink__c
                                          FROM Project__c WHERE ApplicantContact__c IN : ContactIds
                                          AND ApplicantContact__r.UserCommunityLicense__c != null] )
                    {   
                        projToUpdate.add(TVE_Project_Utility.ProjectLinkMapping(proj, eSign, null));
                    }

                    if(!projToUpdate.isEmpty())
                    {
                        update projToUpdate;
                    }
                }
            }
            else 
            {
                System.debug('UpdateProjectUrl_On_CustomerUpdate----> eSign.AES_Key__c is NOT set');
                //throw new TVE_ConfigurationException('AES key is not set for custom setting eSignSettings__c');
            }            
        }else{
            System.debug('eSignSettings__c data not found');
            throw new TVE_ConfigurationException('No valid records found for custom setting eSignSettings__c');
        }
        
    }
}