force-app/main/default/objects/Affected_Customer__c/Affected_Customer__c.object-meta.xml
<CustomObject>
    <label>Affected Customer</label>
    <nameField>
        <label>Affected Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Customer__c/fields/uom_Affected_Market_Identifier__c.field-meta.xml
<CustomField>
    <fullName>uom_Affected_Market_Identifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affected Market Identifier</label>
    <referenceTo>Affected_Market_Identifier__c</referenceTo>
    <relationshipLabel>Affected Customers</relationshipLabel>
    <relationshipName>Affected_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Customer__c/fields/uom_Incident__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Affected Customers</relationshipLabel>
    <relationshipName>Affected_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Market_Identifier__c/Affected_Market_Identifier__c.object-meta.xml
<CustomObject>
    <label>Affected Market Identifier</label>
    <nameField>
        <label>Affected Market Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected Market Identifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Market_Identifier__c/fields/IncidentIdText__c.field-meta.xml
<CustomField>
    <fullName>IncidentIdText__c</fullName>
    <label>Incident Id Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Market_Identifier__c/fields/uom_Incident__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Affected Market Identifiers</relationshipLabel>
    <relationshipName>Affected_Market_Identifiers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Market_Identifier__c/fields/uom_Status__c.field-meta.xml
<CustomField>
    <fullName>uom_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Restored</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affected_Market_Identifier__c/fields/uom_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>uom_Status_Code__c</fullName>
    <label>Status Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRED</fullName>
                <default>true</default>
                <label>PRED</label>
            </value>
            <value>
                <fullName>COMP</fullName>
            </value>
            <value>
                <fullName>DEAD</fullName>
            </value>
            <value>
                <fullName>DELG</fullName>
            </value>
            <value>
                <fullName>PLAN</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident/fields/uom_Incident_Id__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident_Id__c</fullName>
    <externalId>true</externalId>
    <label>Incident Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Incident_Setup__c/Incident_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global kill-switch for Outage Management automated notifications</description>
    <label>Incident Setup</label>
</CustomObject>

force-app/main/default/objects/Incident_Setup__c/fields/Multi_Incident_Mode_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Multi_Incident_Mode_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disable switch for Multi-Incident Mode</description>
    <label>Multi-Incident Mode Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TrigSettings__c/fields/Affected_Market_Ident_Trigger_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Affected_Market_Ident_Trigger_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Affected Market Ident Trigger Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Trig_AffectedNMI.cls
public with sharing class Trig_AffectedNMI implements UtilTrigHandle
{

	// *********************************************************************
	// *** Disable logic
	public static Boolean TrigDisabled = false;
	public static Boolean MultiIncModeDisabled = false;

	public Boolean IsDisabled()
	{
		if (TrigSettings__c.getInstance().Affected_Market_Ident_Trigger_Disabled__c)
			return true;
		else
			return TrigDisabled;
	}



	// *********************************************************************
	// *** Trigger contexts
	public void BeforeInsert(List<SObject> newSObjs)
	{
		insertCheckIncidentLookup(newSObjs); // must be first.
		insertUpdateCheckNMILength(newSObjs);

		insertSetStatusField(newSObjs);
		insertCheckNMIMultiIncident(newSObjs);
	}

	public void AfterInsert(Map<Id, SObject> newSObjs)
	{
		// System.debug('*** Trig_AffectedNMI.AfterInsert');
		createAffectedCustomer(newSObjs.values());
	}

	public void BeforeUpdate(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		insertUpdateCheckNMILength(newSObjs.values());

		updateSetStatusField(newSObjs.values(), (Map<Id, Affected_Market_Identifier__c>)oldSObjs);
	}

	public void AfterUpdate(Map<Id, SObject> newSObjs, Map<Id, SObject> oldSObjs)
	{
		updateCheckNMIMultiIncident(newSObjs.values(), (Map<Id, Affected_Market_Identifier__c>)oldSObjs);
		updateAffectedCustomer(oldSObjs, newSObjs);
	}

	public void BeforeDelete(Map<Id, SObject> oldSObjs)
	{
		deleteAffectedCustomer(oldSObjs.values());
	}

	// if context is not implemented, condense into one-liners
	public void AfterDelete(Map<Id, SObject> oldSObjs) {}
	public void AfterUndelete(Map<Id, SObject> oldSObjs) {}


	// *********************************************************************
	// *** Trigger methods

	// setStatusField profile:
	// Runs in before context
	// 0 SOQLs
	// 0 DMLs
	public static void insertSetStatusField(List<Affected_Market_Identifier__c> affNMIs)
	{
		if (affNMIs == null || affNMIs.isEmpty())
			return;

		// We are now setting the AffectNMI Status field based on the Status Code value.
		for (Affected_Market_Identifier__c affNMI: affNMIs)
		{
			String statusCode = affNMI.uom_Status_Code__c;

			if (statusCode == null)
			{
				affNMI.uom_Status_Code__c.addError('Error: uom_Status_Code__c is null.');
				continue;
			}

			if (!Outage_IncidentProcessor.AFF_NMI_CODE_STATUS.containsKey(statusCode) &&
				affNMI.uom_Status__c == null)
			{
				// affNMI.uom_Status_Code__c.addError('Error: Unknown uom_Status_Code__c value.');
				affNMI.uom_Status__c = Outage_IncidentProcessor.AFF_NMI_IN_PROG; // default value.
				continue;
			}

			affNMI.uom_Status__c = Outage_IncidentProcessor.AFF_NMI_CODE_STATUS.get(statusCode);
		}
	}

	public static void insertUpdateCheckNMILength(List<Affected_Market_Identifier__c> affNMIs)
	{
		if (affNMIs == null || affNMIs.isEmpty())
			return;

		for (Affected_Market_Identifier__c affNMI: affNMIs)
		{
			if (affNMI.Name == null || affNMI.Name.length() != 10) continue;

			String nmiNum10 = affNMI.Name;
			String nmiNum11 = Outage_NMITools.getNMI11(nmiNum10);
			affNMI.Name = nmiNum11;
		}
	}

	public static void insertCheckIncidentLookup(List<Affected_Market_Identifier__c> affNMIs)
	{
		if (affNMIs == null || affNMIs.isEmpty())
			return;

		// Check for field 
		Map<String, Id> IncIds = new Map<String, Id>();
		for (Affected_Market_Identifier__c affNMI: affNMIs)
		{
			if (affNMI.IncidentIdText__c != null && affNMI.uom_Incident__c == null)
				IncIds.put(affNMI.IncidentIdText__c, null);
		}

		if (IncIds.isEmpty())
		{
			// nothing to do
			return;
		}

		for (Incident inc: [SELECT Id, uom_Incident_Id__c FROM Incident WHERE uom_Incident_Id__c IN :IncIds.keySet()])
		{
			IncIds.put(inc.uom_Incident_Id__c, inc.Id);
		}

		for (Affected_Market_Identifier__c affNMI: affNMIs)
		{
			if (affNMI.IncidentIdText__c != null && affNMI.uom_Incident__c == null)
			{
				if (!IncIds.containsKey(affNMI.IncidentIdText__c))
				{
					affNMI.addError('Incident Id not found.');
					continue;
				}

				affNMI.uom_Incident__c = IncIds.get(affNMI.IncidentIdText__c);
				affNMI.IncidentIdText__c = null;
			}
		}
	}

	public static void updateSetStatusField(List<Affected_Market_Identifier__c> newAffNMIs, Map<Id, Affected_Market_Identifier__c> oldAffNMIs)
	{
		if (newAffNMIs == null || newAffNMIs.isEmpty() || oldAffNMIs == null || oldAffNMIs.isEmpty())
			return;

		// We are now setting the AffectNMI Status field based on the Status Code value.
		for (Affected_Market_Identifier__c newAffNMI: newAffNMIs)
		{
			Affected_Market_Identifier__c oldAffNMI = oldAffNMIs.get(newAffNMI.Id);

			// check which has changed
			if (newAffNMI.uom_Status_Code__c != oldAffNMI.uom_Status_Code__c)
			{
				String statusCode = newAffNMI.uom_Status_Code__c;

				if (statusCode == null)
				{
					newAffNMI.uom_Status_Code__c.addError('Error: uom_Status_Code__c is null.');
					continue;
				}

				if (!Outage_IncidentProcessor.AFF_NMI_CODE_STATUS.containsKey(statusCode) &&
					newAffNMI.uom_Status__c == null)
				{
					// affNMI.uom_Status_Code__c.addError('Error: Unknown uom_Status_Code__c value.');
					newAffNMI.uom_Status__c = Outage_IncidentProcessor.AFF_NMI_IN_PROG; // default value.
					continue;
				}

				newAffNMI.uom_Status__c = Outage_IncidentProcessor.AFF_NMI_CODE_STATUS.get(statusCode);
			}

			else if (newAffNMI.uom_Status__c != oldAffNMI.uom_Status__c)
			{
				String status = newAffNMI.uom_Status__c;

				if (status == null)
				{
					newAffNMI.uom_Status__c.addError('Error: uom_Status__c is null.');
					continue;
				}

				if (!Outage_IncidentProcessor.AFF_NMI_STATUS_CODE.containsKey(status))
				{
					newAffNMI.uom_Status__c.addError('Error: Unknown uom_Status__c value.');
					continue;
				}

				newAffNMI.uom_Status_Code__c = Outage_IncidentProcessor.AFF_NMI_STATUS_CODE.get(status);
			}
		}
	}

	public static void createAffectedCustomer(List<Affected_Market_Identifier__c> newAffNMIs)
	{
		if (newAffNMIs == null || newAffNMIs.isEmpty())
			return;

		System.debug(
			Outage_IncidentProcessor.AffNMICreateAffCust(newAffNMIs)
		);
	}

	public static void updateAffectedCustomer(Map<Id, SObject> oldAffNMIs, Map<Id, SObject> newAffNMIs)
	{
		if (oldAffNMIs == null || oldAffNMIs.isEmpty() || newAffNMIs == null || newAffNMIs.isEmpty())
			return;

		System.debug(
			Outage_IncidentProcessor.AffNMIUpdAffCust((Map<Id, Affected_Market_Identifier__c>)oldAffNMIs, (Map<Id, Affected_Market_Identifier__c>)newAffNMIs)
		);
	}

	public static void deleteAffectedCustomer(List<Affected_Market_Identifier__c> delAffNMIs)
	{
		if (delAffNMIs == null || delAffNMIs.isEmpty())
			return;

		List<Affected_Customer__c> delAffCusts = new List<Affected_Customer__c>();
		for (Affected_Customer__c affCust: [SELECT Id FROM Affected_Customer__c WHERE uom_Affected_Market_Identifier__c IN :delAffNMIs])
		{
			delAffCusts.add(affCust);
		}

		if (!delAffCusts.isEmpty())
			delete delAffCusts;
	}

	public static void insertCheckNMIMultiIncident(List<Affected_Market_Identifier__c> affNMIs)
	{
		if (affNMIs == null || affNMIs.isEmpty())
			return;

		if (Incident_Setup__c.getInstance().Multi_Incident_Mode_Disabled__c || MultiIncModeDisabled)
		{
			System.debug('* Multi-Incident Mode is Disabled');
			return;
		}

		Outage_IncidentProcessor.insertCheckNMIMultiIncident(affNMIs);
	}

	public static void updateCheckNMIMultiIncident(List<Affected_Market_Identifier__c> newAffNMIs, Map<Id, Affected_Market_Identifier__c> oldAffNMIs)
	{
		if (newAffNMIs == null || newAffNMIs.isEmpty())
			return;

		if (Incident_Setup__c.getInstance().Multi_Incident_Mode_Disabled__c || MultiIncModeDisabled)
		{
			System.debug('* Multi-Incident Mode is Disabled');
			return;
		}

		Outage_IncidentProcessor.updateCheckNMIMultiIncident(newAffNMIs, oldAffNMIs);
	}
}