force-app/main/default/objects/Affected_Customer__c/Affected_Customer__c.object-meta.xml
<CustomObject>
    <label>Affected Customer</label>
    <nameField>
        <label>Affected Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_Customer__c/fields/uom_Incident__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Incident</label>
    <referenceTo>Incident</referenceTo>
    <relationshipLabel>Affected Customers</relationshipLabel>
    <relationshipName>Affected_Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_Customer__c/fields/uom_Incident_Status__c.field-meta.xml
<CustomField>
    <fullName>uom_Incident_Status__c</fullName>
    <label>Incident Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affected_Customer__c/fields/uom_Life_Support__c.field-meta.xml
<CustomField>
    <fullName>uom_Life_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Please verify if not on contact</description>
    <label>Life support</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Trig_AffectedCustomer_Test.cls
@isTest
public class Trig_AffectedCustomer_Test {

	public static testMethod void affCust_insert_success()
	{
			Outage_DataFactory odf = Outage_DataFactory.getODF();
			odf.generateCustomers(1,true, true);
			odf.generateIncidents(1);

			List<Affected_Customer__c> affCusts = [SELECT Id, Name, uom_Life_Support__c
										   FROM Affected_Customer__c
										   WHERE uom_Incident__c = :odf.incidents[0].Id];

			if (affCusts == null || affCusts.isEmpty())
			{
				// Error
				System.debug('Error: Affected Customers not found');
				return;
			}


			affCusts[0].uom_Incident_Status__c=Outage_IncidentProcessor.INCIDENT_STS_7_RESTORED;

			update affCusts[0];
			delete affCusts[0];
			undelete affCusts[0];


	}

}