force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Application__c/fields/Post_Installation_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Installation_Date__c</fullName>
    <label>Post Installation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Parent_Device__c.field-meta.xml
<CustomField>
    <fullName>Parent_Device__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateChildDeviceRecordsBatch.cls
global class UpdateChildDeviceRecordsBatch implements Database.Batchable<SObject>,Schedulable {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, DER_Application__c, (SELECT Id,CreatedDate, Parent_Device__c, DER_Application__c FROM Devices__r) FROM Device__c WHERE Parent_Device__c = null';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Device__c> parentRecords) {
        List<Device__c> childRecordsToUpdate = new List<Device__c>();
		List<DER_Application__c> derRecordsToUpdate = new List<DER_Application__c>();
        Map<Id,Datetime> idDateMap = new Map<Id,Datetime>();
        for (Device__c parentRecord : parentRecords) {
            if(!parentRecord.Devices__r.isEmpty()) {
               for (Device__c childRecord : parentRecord.Devices__r) {
                idDateMap.put(parentRecord.DER_Application__c,childRecord.CreatedDate); 
                childRecord.DER_Application__c = parentRecord.DER_Application__c; // Update child record data from parent record data
                childRecordsToUpdate.add(childRecord);
               }
            }
        }
        for (Id s : idDateMap.keySet()) {
                            
                           
                               DER_Application__c dApp = new DER_Application__c(); 
                               dApp.Id =s;
                               dApp.Post_Installation_Date__c = idDateMap.get(s);              			 
                               derRecordsToUpdate.add(dApp);
                            
         }
        if(!childRecordsToUpdate.isEmpty()) { 
           update childRecordsToUpdate;
        }  
        if(!derRecordsToUpdate.isEmpty()) { 
           UtilFieldCalcs.isRunning_CalcDERAppPhaseTotals = true;
           update derRecordsToUpdate;
        }  
    }

    global void finish(Database.BatchableContext BC) {
        // Optional finish logic
    }
    
     global void execute(SchedulableContext sc)
     {
      	UpdateChildDeviceRecordsBatch b = new UpdateChildDeviceRecordsBatch(); 
        database.executeBatch(b,200);
     }
}