force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Default__c/DER_Default__c.object-meta.xml
<CustomObject>
    <description>Sets the default values of DER Applications and Devices</description>
    <label>DER Default</label>
    <nameField>
        <displayFormat>DEF-{0000}</displayFormat>
        <label>DER Default Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Defaults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DER_Default__c/fields/Equip_Inverter__c.field-meta.xml
<CustomField>
    <fullName>Equip_Inverter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Equipment Type - Inverter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Equip_Non_Inverter__c.field-meta.xml
<CustomField>
    <fullName>Equip_Non_Inverter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Equipment Type - Non-Inverter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Islandable_Installation__c</fullName>
            </value>
            <value>
                <fullName>Over_Freq_Protection__c</fullName>
            </value>
            <value>
                <fullName>Overvolt_Protection_2__c</fullName>
            </value>
            <value>
                <fullName>Under_Freq_Protection__c</fullName>
            </value>
            <value>
                <fullName>Under_Freq_Protection_Delay__c</fullName>
            </value>
            <value>
                <fullName>Undervolt_Protection__c</fullName>
            </value>
            <value>
                <fullName>Undervolt_Protection_Delay__c</fullName>
            </value>
            <value>
                <fullName>Volt_Vector_Shift__c</fullName>
            </value>
            <value>
                <fullName>DRED_Enabled__c</fullName>
            </value>
            <value>
                <fullName>Non_Inv_Generator_Freq_Response_Mode__c</fullName>
            </value>
            <value>
                <fullName>Non_Inv_Gen_Ramp_Rate__c</fullName>
            </value>
            <value>
                <fullName>Inv_Reactive_Power_Mode__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_Q_at_V1__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_Q_at_V2__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_Q_at_V3__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_Q_at_V4__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_V1__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_V2__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_V3__c</fullName>
            </value>
            <value>
                <fullName>Inv_Var_Response_V4__c</fullName>
            </value>
            <value>
                <fullName>Inv_Volt_Var_Response_Mode__c</fullName>
            </value>
            <value>
                <fullName>Inv_Volt_Watt_Response_Mode__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_P_at_V1__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_P_at_V2__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_P_at_V3__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_P_at_V4__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_V1__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_V2__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_V3__c</fullName>
            </value>
            <value>
                <fullName>Inv_Watt_Response_V4__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DER_Application__c</fullName>
            </value>
            <value>
                <fullName>Device__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Offer_MSO__c.field-meta.xml
<CustomField>
    <fullName>Offer_MSO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offer - MSO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Offer_Neg_0__c.field-meta.xml
<CustomField>
    <fullName>Offer_Neg_0__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offer - Negotiated 0-5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DER_Default__c/fields/Offer_Neg_5__c.field-meta.xml
<CustomField>
    <fullName>Offer_Neg_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offer - Negotiated 5+</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>Device-{0000000}</displayFormat>
        <label>Device ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AC_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>AC_Equip_Type__c</fullName>
    <description>DER Register Level 2 – AC Connection

Indicates whether the DER device is connected via an inverter (and what category of inverter it is) or not (e.g. rotating machine).</description>
    <label>AC Equipment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inverter</fullName>
            </value>
            <value>
                <fullName>Non-Inverter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/DER_Application__c.field-meta.xml
<CustomField>
    <fullName>DER_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DER Application</label>
    <referenceTo>DER_Application__c</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Existing_Device__c.field-meta.xml
<CustomField>
    <fullName>Existing_Device__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Existing Device</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DER_Defaults.cls
/*
@author  : Rohit.Middha@ausnetservices.com.au 
@created : 14 Oct 2019
@Description : For setting default values to device and der application object.
-----------------------------------------------------------------------------------------
Change log
-----------------------------------------------------------------------------------------
Date                  Name                           Description
-----------------------------------------------------------------------------------------
NA                    NA                              NA
-----------------------------------------------------------------------------------------
*/
public with sharing class DER_Defaults {
    
    PRIVATE STATIC Schema.SObjectType t = Schema.getGlobalDescribe().get('DER_Application__c');
    PRIVATE STATIC Schema.DescribeSObjectResult r = t.getDescribe();
    
    PRIVATE STATIC Schema.SObjectType t1 = Schema.getGlobalDescribe().get('Device__c');
    PRIVATE STATIC Schema.DescribeSObjectResult r1 = t1.getDescribe();
    
    public static void applyDefaults(Map<Id,String> derAppIdOfferTypeMap)
    {
        Map<Id,List<Device__c>> derIdDevicesMap = new  Map<Id,List<Device__c>>();
        Map<Id,DER_Application__c> derIdObjMap = new Map<Id,DER_Application__c>();
        Set<Id> derAppIdOfferTypeMapKeySet = derAppIdOfferTypeMap.keySet();
        
        String queryApp = '';
        queryApp += UtilDatabase.getAllFields('DER_Application__c');
        queryApp += ' FROM DER_Application__c ';
        queryApp += 'WHERE Id in :derAppIdOfferTypeMapKeySet';  
        
        List<SObject> objList = Database.query(queryApp);
        
        String queryDevice = '';
        queryDevice += UtilDatabase.getAllFields('Device__c');
        queryDevice += ' FROM Device__c ';
        queryDevice += 'WHERE DER_Application__c in :derAppIdOfferTypeMapKeySet';  
        queryDevice += ' AND Existing_Device__c = false'; 
        
        String queryDerDefaults = '';
        queryDerDefaults += UtilDatabase.getAllFields('DER_Default__c');
        queryDerDefaults += ' FROM DER_Default__c ';
        List<SObject> derDefaults = Database.query(queryDerDefaults);
        
        for(DER_Application__c derapp :(List<DER_Application__c>) objList)
        {
            derIdObjMap.put(derapp.Id,derapp);
        }
        
        
        for(Device__c dev : (List<Device__c>) Database.query(queryDevice))
        {
            List<Device__c> temp = derIdDevicesMap.get(dev.DER_Application__c);
            if(temp == null) {
                derIdDevicesMap.put(dev.DER_Application__c, new List<Device__c>{dev});
            } else {
                temp.add(dev);
            }
        }
        Set<DER_Application__c> derAppList = new Set<DER_Application__c>();
        Set<Device__c> devList = new Set<Device__c>();
        
        for(Id appId :derAppIdOfferTypeMap.keySet() )
        {
            if(derAppIdOfferTypeMap.get(appId) == 'Basic Micro EG MSO')
            { 
                DER_Application__c  derApp = derIdObjMap.get(appId);
                blankOutDerAppFields(derApp,(List<DER_Default__c>)derDefaults);
                for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                 if(def.Offer_MSO__c == true && def.Object__c == 'DER_Application__c')
                                {
                                    getDerAppAfterFieldUpdate(def,derApp);
                                }
                            }
                List<Device__c> devList1 = (List<Device__c>) derIdDevicesMap.get(appId);
                if(devList1 != null)
                {
                    for(Device__c dev :  devList1)
                    {
                        blankOutDeviceFields(dev,(List<DER_Default__c>)derDefaults);
                        if(dev.AC_Equip_Type__c == 'Inverter')
                        {
                            for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                if(def.Offer_MSO__c == true)
                                {
                                    if(def.Object__c == 'Device__c' && def.Equip_Inverter__c == true)
                                    {   
                                        getDeviceAfterFieldUpdate(def, dev);
                                    }
                                 }
                            }
                            if(dev != null)
                            {
                                devList.add(dev);
                            }
                        }
                        else if(dev.AC_Equip_Type__c == 'Non-Inverter')
                        {
                            for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                if(def.Equip_Non_Inverter__c== true && def.Offer_MSO__c == true)
                                {
                                   if(def.Object__c == 'Device__c' && def.Equip_Non_Inverter__c == true)
                                    { 
                                        getDeviceAfterFieldUpdate(def, dev);
                                    }
                                }

                            }
                            if(dev != null)
                            {
                                devList.add(dev);
                            }
                        }
                    }
                }
                 if(derApp != null)
                            {
                                derAppList.add(derApp);
                            }
            }
            else if (derAppIdOfferTypeMap.get(appId) == 'Negotiated >5MW NEA' || derAppIdOfferTypeMap.get(appId) == 'Negotiated 0-5MW'
                     || derAppIdOfferTypeMap.get(appId) == 'Negotiated >5MW NEA&NMA')
            {
                DER_Application__c  derApp = derIdObjMap.get(appId);
                blankOutDerAppFields(derApp,(List<DER_Default__c>)derDefaults);
                   for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                 if((def.Offer_Neg_0__c == true || def.Offer_Neg_5__c == true)  && def.Object__c == 'DER_Application__c')
                                {
                                    getDerAppAfterFieldUpdate(def,derApp);
                                }
                            }
                List<Device__c> devList2 = derIdDevicesMap.get(appId);
                if(devList2 != null)
                {
                    for(Device__c dev : devList2)
                    {
                        blankOutDeviceFields(dev,(List<DER_Default__c>)derDefaults);
                        if(dev.AC_Equip_Type__c == 'Inverter')
                        { 
                            for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                 if(def.Object__c == 'Device__c' && def.Equip_Inverter__c == true && (def.Offer_Neg_0__c == true || def.Offer_Neg_5__c == true))
                                    { 
                                        getDeviceAfterFieldUpdate(def, dev);
                                    }
                            }
                            if(dev != null)
                            {
                                devList.add(dev);
                            }
                        }
                        else if(dev.AC_Equip_Type__c == 'Non-Inverter')
                        {
                            for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                            {
                                if(def.Equip_Non_Inverter__c== true && def.Object__c == 'Device__c' && (def.Offer_Neg_0__c == true || def.Offer_Neg_5__c == true))
                                {
                                    getDeviceAfterFieldUpdate(def, dev);
                                }
                            }
                            if(dev != null)
                            {
                                devList.add(dev);
                            }
                        }
                    }
                }
                if(derApp != null)
                            {
                                derAppList.add(derApp);
                            }
            }
        }
        List<DER_Application__c> derList  = new  List<DER_Application__c>() ;
        derList.addAll(derAppList);
        List<Device__c> deviceList  = new  List<Device__c>() ;
        deviceList.addAll(devList);
        if(deviceList != null)
            update deviceList;
        if(derList != null)
            update derList;
        
        
    }
    
    
      public static void applyDefault(Map<Device__c,String> deviceOfferTypeMap)
    {
        
        List<Device__c> devList = new List<Device__c>();
        
        String queryDerDefaults = '';
        queryDerDefaults += UtilDatabase.getAllFields('DER_Default__c');
        queryDerDefaults += ' FROM DER_Default__c ';
        List<SObject> derDefaults = Database.query(queryDerDefaults);        
        for(Device__c dev : deviceOfferTypeMap.keySet())
        {
            String aggrementType = deviceOfferTypeMap.get(dev);
            blankOutDeviceFields(dev,(List<DER_Default__c>)derDefaults);
            if(aggrementType == 'Basic Micro EG MSO')
            {
                if(dev.AC_Equip_Type__c == 'Inverter')
                {
                    for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                    {
                        if(def.Equip_Inverter__c == true && def.Offer_MSO__c == true )
                        {
                            
                            if(def.Object__c == 'Device__c')
                            {
                                getDeviceAfterFieldUpdate(def, dev);
                            }
                        }
                    }
                    if(dev != null)
                            {
                                devList.add(dev);
                            }
                }
                else if(dev.AC_Equip_Type__c == 'Non-Inverter')
                {
                    for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                    {
                        if(def.Equip_Non_Inverter__c == true && def.Offer_MSO__c == true )
                        {
                            
                            if(def.Object__c == 'Device__c')
                            {
                                getDeviceAfterFieldUpdate(def, dev);
                            }
                        }
                    }
                    if(dev != null)
                            {
                                devList.add(dev);
                            }
                }
              
            }
            else if(aggrementType == 'Negotiated >5MW NEA' || aggrementType == 'Negotiated 0-5MW'
                    || aggrementType == 'Negotiated >5MW NEA&NMA')
            {
                if(dev.AC_Equip_Type__c == 'Inverter')
                {
                    for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                    {
                        if(def.Equip_Inverter__c == true && (def.Offer_Neg_0__c == true || def.Offer_Neg_5__c == true))
                        {
                            
                            if(def.Object__c == 'Device__c')
                            {
                                getDeviceAfterFieldUpdate(def, dev);
                            }
                        }
                    }
                }
                else if(dev.AC_Equip_Type__c == 'Non-Inverter')
                {
                    for(DER_Default__c def : (List<DER_Default__c>)derDefaults)    
                    {
                        if(def.Equip_Non_Inverter__c == true && (def.Offer_Neg_0__c == true || def.Offer_Neg_5__c == true))
                        {
                            
                            if(def.Object__c == 'Device__c')
                            {
                                getDeviceAfterFieldUpdate(def, dev);
                            }
                        }
                    }
                }
              
            }
            
        }
       
    }

    public static DER_Application__c blankOutDerAppFields(DER_Application__c derApp,List<DER_Default__c> derDefaults)
    {
        for(DER_Default__c def : derDefaults)
        {
            if(def.Object__c == 'DER_Application__c')
            {
                derApp.put(def.Field__c,null);
            }
        }
        return derApp;
    }

    public static Device__c blankOutDeviceFields(Device__c dev,List<DER_Default__c> derDefaults)
    {
        for(DER_Default__c def : derDefaults)
        {
            if(def.Object__c == 'Device__c')
            {
                dev.put(def.Field__c,null);
            }
        }
        return dev;
    }
    
    public static DER_Application__c getDerAppAfterFieldUpdate(DER_Default__c def,DER_Application__c derApp)
    {
        Schema.DescribeFieldResult f = r.fields.getMap().get(def.Field__c).getDescribe();
        
        if(f.getType() == Schema.DisplayType.Boolean)
        {
            derApp.put(def.Field__c, Boolean.valueOf(def.Value__c) );  
        }
        else if(f.getType() == Schema.DisplayType.Double)
        {
            derApp.put(def.Field__c, Double.valueOf(def.Value__c) );
        }
        else if (f.getType() == Schema.DisplayType.Integer)
        {
            derApp.put(def.Field__c, Integer.valueOf(def.Value__c) );
        }       
        else if (f.getType() == Schema.DisplayType.String)
        {
            derApp.put(def.Field__c, String.valueOf(def.Value__c) );
        }  
        else if (f.getType() == Schema.DisplayType.Picklist)
        {
            derApp.put(def.Field__c, String.valueOf(def.Value__c) );
        }  
        else
        {
            derApp.put(def.Field__c, Decimal.valueOf(def.Value__c) );
        }
        return derApp;
    }
    
    public static Device__c getDeviceAfterFieldUpdate(DER_Default__c def,Device__c device)
    {
        Schema.DescribeFieldResult f = r1.fields.getMap().get(def.Field__c).getDescribe();
        if(f.getType() == Schema.DisplayType.Boolean)
        {
            device.put(def.Field__c, Boolean.valueOf(def.Value__c) );  
        }
        else if(f.getType() == Schema.DisplayType.Double)
        {
            device.put(def.Field__c, Double.valueOf(def.Value__c) );
        }
        else if (f.getType() == Schema.DisplayType.Integer)
        {
            device.put(def.Field__c, Integer.valueOf(def.Value__c) );
        }       
        else if (f.getType() == Schema.DisplayType.String)
        {
            device.put(def.Field__c, String.valueOf(def.Value__c) );
        } 
        else if (f.getType() == Schema.DisplayType.Picklist)
        {
            device.put(def.Field__c, String.valueOf(def.Value__c) );
        } 
        else
        {
            device.put(def.Field__c, Decimal.valueOf(def.Value__c) );
        }
        return device;
    }
}