force-app/main/default/objects/DER_Application__c/DER_Application__c.object-meta.xml
<CustomObject>
    <label>DER Application</label>
    <nameField>
        <displayFormat>DER-{00000000}</displayFormat>
        <label>DER Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <label>Message ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Integration error message</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Integration_Task__c.field-meta.xml
<CustomField>
    <fullName>Integration_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Task</label>
    <referenceTo>Integration_Task__c</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/ReqBody__c.field-meta.xml
<CustomField>
    <fullName>ReqBody__c</fullName>
    <label>Json ReqBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Integration status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Success_Id__c.field-meta.xml
<CustomField>
    <fullName>Success_Id__c</fullName>
    <description>Stores the Id of the successfully created Record</description>
    <label>Success_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Success_Json__c.field-meta.xml
<CustomField>
    <fullName>Success_Json__c</fullName>
    <description>Stores the Success record details</description>
    <label>Success_Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Azure create customer</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
            <value>
                <fullName>upsertRecordData</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/recordTypes/ElectricalFormRecordType.recordType-meta.xml
<RecordType>
    <fullName>ElectricalFormRecordType</fullName>
    <active>true</active>
    <label>ElectricalFormRecordType</label>
</RecordType>

force-app/main/default/objects/Integration_Log__c/recordTypes/SolarFormRecordType.recordType-meta.xml
<RecordType>
    <fullName>SolarFormRecordType</fullName>
    <active>true</active>
    <label>SolarFormRecordType</label>
</RecordType>

force-app/main/default/objects/Integration_Task__c/Integration_Task__c.object-meta.xml
<CustomObject>
    <description>To track the integration items so that SAP licensed users can execute them. Also used for error handling, tracking integration progress and reporting.</description>
    <label>Integration Task</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Task__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Integration operation type</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Get</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <description>SF ID of the record to integrate.</description>
    <label>ParentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>SF object name of the record to integrate.</description>
    <label>SObject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
            </value>
            <value>
                <fullName>Artefact__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>WorkOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CreateCustomer</fullName>
            </value>
            <value>
                <fullName>GetCustomer</fullName>
            </value>
            <value>
                <fullName>CreateMasterNoti</fullName>
            </value>
            <value>
                <fullName>CreateWork</fullName>
            </value>
            <value>
                <fullName>UpdateCM</fullName>
            </value>
            <value>
                <fullName>CreateArtefact</fullName>
            </value>
            <value>
                <fullName>GetCM</fullName>
            </value>
            <value>
                <fullName>GetConstNoti</fullName>
            </value>
            <value>
                <fullName>GetConstWO</fullName>
            </value>
            <value>
                <fullName>GetInvoice</fullName>
            </value>
            <value>
                <fullName>GetArtefact</fullName>
            </value>
            <value>
                <fullName>GetCMArtefact</fullName>
            </value>
            <value>
                <fullName>RequestInvoice</fullName>
            </value>
            <value>
                <fullName>postPaymentWestPac</fullName>
            </value>
            <value>
                <fullName>getFirmOfferForElecForm</fullName>
            </value>
            <value>
                <fullName>getInverters</fullName>
            </value>
            <value>
                <fullName>createDERApplication</fullName>
            </value>
            <value>
                <fullName>validateNMIandMeterNum</fullName>
            </value>
            <value>
                <fullName>getDERApplicationDetails</fullName>
            </value>
            <value>
                <fullName>updateDERApplication</fullName>
            </value>
            <value>
                <fullName>toPopulateInverter</fullName>
            </value>
            <value>
                <fullName>toMergeInverterLists</fullName>
            </value>
            <value>
                <fullName>insertIntoCECInvertersMDT</fullName>
            </value>
            <value>
                <fullName>updateAndDeployMetadata</fullName>
            </value>
            <value>
                <fullName>invokeMethod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount (in. GST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status for the landing page of the community</description>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SAPStatus__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>ProjectStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/FnP_ExtUserObjAccessUtility.cls
global without sharing class FnP_ExtUserObjAccessUtility implements vlocity_cmt.VlocityOpenInterface {
    public static string workTaskId ='workTaskId';
	public static string sobjectData ='sobjectData';
    public static string getRecordData = 'getRecordData';
	public static string upsertRecordData = 'upsertRecordData';
	public static string sObjectFieldLst = 'sObjectFieldLst';
	public static string orderBy = 'orderBy';
	public static string querylimit = 'querylimit';
	public static string sobjectApiName = 'sobjectApiName';
	public static string strQuery = 'SELECT Id';
	public static string strFrm = 'FROM ';
	public static string strComma = ' , ';
	public static string strWhereCondition = 'whereCondition';
	public static string strSpace = ' ';
	public static string objRecordTypeId = 'objRecordTypeId';
	public static string dateRegex = '[0-9]{4}-[0-9]{0,2}-[0-9]{0,2}';
	public static string erroMsg = 'Error Message: ';
    public static string nextLineStr = '\n';

	global static Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        string recordId;
        try
        {
            if (methodName.equals('getRecordData')){
                getRecordData(inputMap,outMap,options);
            }
			else if (methodName.equals('upsertRecordData')){
                SObject sObjRecord = upsertRecordData(inputMap,outMap,options);
                recordId=(String)sObjRecord.Id;
                integrationLogSuccess(sObjRecord.Id,JSON.serialize(sObjRecord),'ElectricalFormRecordType','upsertRecordData',JSON.serialize(inputMap),'Create');
                outMap.put('Id',sObjRecord.Id);    
            }
            else if (methodName.equals('insertIntegrationlog')){
                insertIntegrationlog(inputMap,outMap,options);
            }
        }
        catch(Exception excep)
        {
            System.debug('ExtUserWTAccessUtility:invokeMethod -> exception: '+excep);
            System.debug('linenumber -> exception: '+excep.getLinenumber());
            System.debug('recordId: '+recordId);
            // Prepare a response body and set the output. 
            String exceptionResult = excep.getMessage()+'\n'+excep.getStackTraceString()+'\n'+excep.getLineNumber();
            System.debug(LoggingLevel.ERROR, 'Exception upsertRecordData :\n'+exceptionResult);
            String recType = (methodName.equals('insertIntegrationlog')?'SolarFormRecordType':'ElectricalFormRecordType');
            
            integrationlog(exceptionResult,recType, methodName,JSON.serialize(inputMap), 'Create');
            if(recordId==null){
                outMap.put('DMLError',exceptionResult); 
            } 
        }
        return result;
    }

    public static void getRecordData(Map<String, Object> inputMap,Map<String, Object> outMap,Map<String, Object> options) {
        
        System.debug('inputMap1'+inputMap);
        System.debug('outMap1'+outMap);
        System.debug('options1'+options);
        Map<String, Object> fieldValueMap = new Map<String, Object>();
		List<Object> lstfieldMapping = new List<Object>();
		
        if(inputMap.containsKey(sObjectFieldLst)){
            String query;
			lstfieldMapping = (List<Object>)inputMap.get(sObjectFieldLst);
			
			fieldValueMap = getFieldValues(lstfieldMapping);
			system.debug('fieldValues map '+fieldValueMap);
			
			query = strQuery;
			
			//Query record fields
			if(fieldValueMap != null && !fieldValueMap.isEmpty()){
				query+=strComma;
				for(String fieldName : fieldValueMap.keySet()){
					query+=((String)fieldValueMap.get(fieldName)) + strComma;
				}
                query = query.removeEnd(strComma) + strSpace;
			}
			
			query+= strFrm +(String)inputMap.get(sobjectApiName);
			
			//where condition
			if(inputMap.containsKey(strWhereCondition)){
				query+= strSpace + (String)inputMap.get(strWhereCondition);
			}
			
			//orderBy condition
			if(inputMap.containsKey(orderBy)){
				query+= strSpace + (String)inputMap.get(orderBy);
			}
			
			//limit value
			if(inputMap.containsKey(querylimit)){
				query+= strSpace + (String)inputMap.get(querylimit);
			}
			
            if(String.isNOTBlank(query)){
                system.debug('str Query '+query);
                outMap.put(sobjectData,Database.query(query)); //NOPMD
            }
        }
    }
	
	public static SObject upsertRecordData(Map<String, Object> inputMap,Map<String, Object> outMap,Map<String, Object> options) {

        System.debug('inputMap2'+inputMap);
        System.debug('outMap2'+outMap);
        System.debug('options2'+options);  
        
        double paymentamt;
        List<Object> lstfieldMapping = new List<Object>();
        sObject sObjRecord;
        String objectName = (String)inputMap.get(sobjectApiName);
        Pattern datePattern = Pattern.compile(dateRegex);
			 System.debug('(Id)inputMap.get(objRecordTypeId)'+(Id)inputMap.get(objRecordTypeId));
        if(inputMap.containsKey(objRecordTypeId)){
           System.debug('RecordType input is present');
            sObjRecord = Schema.getGlobalDescribe().get(objectName).newSObject((Id)inputMap.get(objRecordTypeId), true);
        }
        else {
            System.debug('Taking default RT');
            sObjRecord = Schema.getGlobalDescribe().get(objectName).newSObject();
        }	
        
        if(inputMap.containsKey(sObjectFieldLst)) {

            lstfieldMapping = (List<Object>)inputMap.get(sObjectFieldLst);
            Map<String, Object> fieldValueMap = new Map<String, Object>();
            fieldValueMap = getFieldValues(lstfieldMapping);
        
            //Upsert sObject Data
            if(fieldValueMap != null && !fieldValueMap.isEmpty()){
                for(String fieldName : fieldValueMap.keySet()){
                    if(String.ValueOf(fieldValueMap.get(fieldName)) != ''){
                        
                        Matcher matchDate = datePattern.matcher(String.ValueOf(fieldValueMap.get(fieldName)));
                        //   Matcher matchNum = numPattern.matcher(String.ValueOf(fieldValueMap.get(fieldName)));
                        //   system.debug('str Match num val  :: '+ fieldName + '::' + matchNum.matches() );
                        if(matchDate.matches() == true){
                            Date dateValue = Date.ValueOf((String)fieldValueMap.get(fieldName));
                            sObjRecord.put(fieldName, dateValue);
                        }
                        else {
                            System.debug('str Exception  :: '+ fieldName + '::' + fieldValueMap.get(fieldName) );
                            try {
                                sObjRecord.put(fieldName, fieldValueMap.get(fieldName));
                            } catch(Exception e){
                                system.debug('Exception e----->'+ fieldName + '::' + e.getStackTraceString());
                                sObjRecord.put(fieldName, Integer.valueOf(fieldValueMap.get(fieldName)));
                                
                            }
                        }
                    }
                    else {
                        System.debug('Field doesnt have value: ' + fieldName);
                    }
                }
                
                if(sObjRecord != null) {
                    upsert sObjRecord;
                }
            }
        }
        
        return sObjRecord;
    }
	
	//dynamic field values map
	public static Map<String,Object> getFieldValues(List<Object> lstfieldMapping){
        
        System.debug('lstfieldMapping'+lstfieldMapping);
		Map<String,Object> fieldValuesMap = new Map<String,Object>();
		if(!lstfieldMapping.isEmpty()){
			Set<String> keySet = new Set<String>();
			Map<String,Object> listMap = new Map<String,Object>();
			for(Object listobj:lstfieldMapping){
                // Listobj.PaymentAmount__c='';
				Map<String,Object> listMapKey = (Map<String, Object>)listobj;
				// String payAmtStr = (String)listMapKey.get('PaymentAmount__c');
				listMap.putall(listMapKey);
				keySet.addAll(listMapKey.keySet());
			}
			if(!keySet.isEmpty()) {
				for(String keyVal:keySet){
					System.debug('keyHeader '+keyVal);
					System.debug('headerValue '+listMap.get(keyVal));
					fieldValuesMap.put(keyVal,listMap.get(keyVal));
                    System.debug('fieldValuesMap###'+fieldValuesMap.values());
				}
			}
            for (String paymentAmount: fieldValuesMap.keyset()){
                System.debug('test'+fieldValuesMap.get(paymentAmount));
            }
		}
		
		return fieldValuesMap;
	}
    
    
    public static void insertIntegrationlog(Map<String, Object> inputMap,Map<String, Object> outMap,Map<String, Object> options) {
        /*
         *  "rec": "%amderAssessmentRequest:sales_force_id%",
            "res": "%PayloadResponse%",
            "recType": "SolarFormRecordType",
            "methodName": "IP_FnP_SendDeviceDetailsToAmder",
            "mapDetails": "%amderAssessmentRequest%",
            "operation": "CREATE"
         */
        System.debug('inputMap1'+inputMap);
        System.debug('inputMap.containsKey(inputMap)'+inputMap.containsKey('inputMap'));
        if(inputMap.containsKey('inputMap') ){
            Map<String, Object> inpmapdetails = (Map<String, Object>) inputMap.get('inputMap');
            System.debug('inpmapdetails'+JSON.serializePretty(inpmapdetails));
        	if(inpmapdetails.containsKey('rec')){
                System.debug('success');
                // rec is populated for success logs.. so invoke success log.
                integrationLogSuccess(String.valueOf(inpmapdetails.get('rec')),String.valueOf(inpmapdetails.get('res')),String.valueOf(inpmapdetails.get('recType')),String.valueOf(inpmapdetails.get('methodName')),String.valueOf(inpmapdetails.get('mapDetails')),String.valueOf(inpmapdetails.get('operation')));
                
            }
            else{
                
                System.debug('failure');
                
                // rec is populated for success logs.. so invoke failure log.
                integrationlog(String.valueOf(inpmapdetails.get('res')),String.valueOf(inpmapdetails.get('recType')),String.valueOf(inpmapdetails.get('methodname')),String.valueOf(inpmapdetails.get('mapdetails')),String.valueOf(inpmapdetails.get('operation')));
                
            }
        
    }
    }
    public static void integrationlog(string res,string recType , string methodname,string mapdetails,string operation) {
		System.debug('inputs:::'+'::'+operation+'::');
        Id recordtypeId = Schema.SObjectType.Integration_Log__c.getRecordTypeInfosByName().get(recType).getRecordTypeId();
        //Integration Task & log insertion starts here//
        list<Integration_Task__c> integrationTasks = new list<Integration_Task__c>();
        Integration_Task__c intgTask = new Integration_Task__c();
        intgTask.Operation__c=operation;
        intgTask.Status__c='Failed';
        Integer maxLength = 131072;
        Integer reqBodyLength;
        switch on recType {
            when 'ElectricalFormRecordType' {
                intgTask.SObject__c='Project__c'; 
            }
            when 'SolarFormRecordType' {
                intgTask.SObject__c='DER_Application__c'; 
            }
        }
        
        intgTask.type__c=methodname;
        integrationTasks.add(intgTask);

        insert integrationTasks;

        list<Integration_Log__c> loglist= new list<Integration_Log__c>();
        for(Integration_Task__c Task:integrationTasks) {

            Integration_Log__c log= new Integration_Log__c();
            log.Integration_Task__c=Task.id;
            log.Type__c=Task.Type__c;
            switch on recType {
                when 'ElectricalFormRecordType' {
                    log.Application_Type__c ='Electrical Form';
                }
                when 'SolarFormRecordType' {
                    log.Application_Type__c ='Solar Form';
                }
            }

         //   log.RecordTypeId=recordtypeId;
            log.Status__c=Task.Status__c;
            log.ReqBody__c=mapdetails;
            reqBodyLength = mapDetails.length();
            System.debug('Request body length::::'+reqBodyLength);
            
            /* Added to test no success log creation on salesforce: start */
            log.ReqBody__c = mapDetails.length() > maxLength ? mapDetails.substring(0, maxLength) : mapDetails;
            if(res!=null & res!=''){
            log.Error_Message__c = res.length() > maxLength ? res.substring(0, maxLength) : res;
        }
            log.Error_Message__c=res;
            loglist.add(log);
        }

        insert loglist;
    } 

    public static void integrationLogSuccess(string rec, string res,string recType , string methodName,string mapDetails,string operation) {

        Id recordtypeId=Schema.SObjectType.Integration_Log__c.getRecordTypeInfosByName().get(recType).getRecordTypeId();
        //Integration Task & log insertion starts here//
        Integration_Task__c intgTask = new Integration_Task__c();
        intgTask.Operation__c=operation;
        intgTask.Status__c='Successful';
        intgTask.ParentId__c = rec;
        Integer maxLength = 131072;
        switch on recType {
            when 'ElectricalFormRecordType' {
                intgTask.SObject__c='Project__c'; 
            }
            when 'SolarFormRecordType' {
                intgTask.SObject__c='DER_Application__c'; 
            }
        }

        intgTask.type__c=methodname;
        insert intgTask;

        Integration_Log__c log= new Integration_Log__c();
        log.Integration_Task__c=intgTask.id;
        log.Type__c=intgTask.Type__c;

        switch on recType {
            when 'ElectricalFormRecordType' {
                log.Application_Type__c ='Electrical Form';
            }
            when 'SolarFormRecordType' {
                log.Application_Type__c ='Solar Form';
            }
        }
        
        log.RecordTypeId=recordtypeId;
        log.Status__c=intgTask.Status__c;
        //log.ReqBody__c=mapdetails;
        log.ReqBody__c = mapDetails.length() > maxLength ? mapDetails.substring(0, maxLength) : mapDetails;
        if(res!=null & res!=''){
            log.Error_Message__c = res.length() > maxLength ? res.substring(0, maxLength) : res;
        }
        //Integer reqBodyLength = mapDetails.length();
        //System.debug('Request body length::::'+reqBodyLength);
        log.Success_Json__c=res;
        log.Success_Id__c = rec;
        insert log;
    } 
}