force-app/main/default/objects/TVE_AzureB2CAuthProvider__mdt/TVE_AzureB2CAuthProvider__mdt.object-meta.xml
<CustomObject>
    <description>Information required by the Custom Auth. Provider AzureB2C</description>
    <label>TVE_AzureB2CAuthProvider</label>
    <pluralLabel>TVE_AzureB2CAuthProviders</pluralLabel>
</CustomObject>

force-app/main/default/objects/TVE_AzureB2CAuthProvider__mdt/fields/Partner_Community_URL__c.field-meta.xml
<CustomField>
    <fullName>Partner_Community_URL__c</fullName>
    <label>Partner Community URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TVEChangePasswordController.cls
public without sharing class TVEChangePasswordController {
    @AuraEnabled 
    public static string changePasswordLink()
    {
        String changePasswordUrl='';
        User uObj = [Select id,Profile.UserLicense.Name from User where Id=: UserInfo.getUserId()];
        system.debug('user info:'+uObj.Profile.UserLicense.Name);
        String userLicense=uObj.Profile.UserLicense.Name;
        if(userLicense == 'Customer Community Plus Login'){
         changePasswordUrl=RedirectOAuthExt.constructB2CPasswordURL();
         system.debug('changePasswordUrl:'+changePasswordUrl);
        }
        else if (userLicense =='Partner Community')
        {
            changePasswordUrl=[SELECT Partner_Community_URL__c from TVE_AzureB2CAuthProvider__mdt WHERE DeveloperName = 'Ausnet_AzureAD'].Partner_Community_URL__c;
            system.debug('changePasswordUrl:'+changePasswordUrl);
        }
        return changePasswordUrl;
    }

}